import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import appCss from "../styles.css?url";
import "../pvd-theme.css";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { Toaster } from "@/components/ui/sonner";
import { MetalCursor } from "@/components/metal-cursor";
import { ScrollProgress } from "@/components/motion";
import { getPageSeo } from "@/lib/page-seo";

function NotFoundComponent(){return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-7xl font-bold text-foreground">404</h1><h2 className="mt-4 text-xl font-semibold text-foreground">Page not found</h2><p className="mt-2 text-sm text-muted-foreground">The page you're looking for doesn't exist or has been moved.</p><div className="mt-6"><Link to="/" className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Go home</Link></div></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){console.error(error);const router=useRouter();useEffect(()=>{reportLovableError(error,{boundary:"tanstack_root_error_component"})},[error]);return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-xl font-semibold tracking-tight text-foreground">This page didn't load</h1><p className="mt-2 text-sm text-muted-foreground">Something went wrong on our end. You can try refreshing or head back home.</p><button onClick={()=>{router.invalidate();reset()}} className="mt-6 rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground">Try again</button></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{title:"SteelXDecor"},{name:"description",content:"Architectural stainless steel surfaces, PVD finishes and engineered metal solutions by SteelXDecor."},{name:"author",content:"SteelXDecor"},{property:"og:title",content:"SteelXDecor"},{property:"og:description",content:"Architectural stainless steel surfaces, PVD finishes and engineered metal solutions."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"stylesheet",href:appCss},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&family=Playfair+Display:wght@500;600;700&display=swap"},{rel:"icon",href:"/favicon.ico",type:"image/x-icon"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function SeoRuntime(){useEffect(()=>{const apply=()=>{const seo=getPageSeo(window.location.pathname);document.title=seo.title;const set=(selector:string,attr:string,value:string)=>{let el=document.querySelector(selector) as HTMLMetaElement|HTMLLinkElement|null;if(!el){el=document.createElement(selector.startsWith("link")?"link":"meta");document.head.appendChild(el)}el.setAttribute(attr,value)};set('meta[name="description"]','content',seo.description);set('meta[name="keywords"]','content',seo.keywords);set('meta[name="robots"]','content',seo.robots);set('meta[property="og:title"]','content',seo.ogTitle);set('meta[property="og:description"]','content',seo.ogDescription);set('link[rel="canonical"]','href',seo.canonical);let schema=document.getElementById("steelx-page-schema") as HTMLScriptElement|null;if(!schema){schema=document.createElement("script");schema.id="steelx-page-schema";schema.type="application/ld+json";document.head.appendChild(schema)}schema.textContent=seo.schema};apply();window.addEventListener("steelx-seo-updated",apply);return()=>window.removeEventListener("steelx-seo-updated",apply)},[]);return null}
function RootComponent(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><SeoRuntime/><ScrollProgress/><MetalCursor/><Outlet/><Toaster position="bottom-right"/></QueryClientProvider>}
