import { createFileRoute } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { useMemo, useState } from "react";

export const Route = createFileRoute("/marble")({ component: MarblePage });

type Stone = { name: string; kind: "Marble" | "Granite" | "Quartzite"; origin: string; price: string; image: string; finish: string };

const stones: Stone[] = [
  { name: "Calacatta Oro", kind: "Marble", origin: "Carrara, Italy", price: "₹1,850 / sq.ft", finish: "Polished", image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=90" },
  { name: "Nero Marquina", kind: "Marble", origin: "Basque Country", price: "₹1,650 / sq.ft", finish: "Honed", image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=90" },
  { name: "Bianco Carrara", kind: "Marble", origin: "Tuscany, Italy", price: "₹980 / sq.ft", finish: "Polished", image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=90" },
  { name: "Verde Alpi", kind: "Marble", origin: "Northern Italy", price: "₹2,250 / sq.ft", finish: "Leathered", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=90" },
  { name: "Black Galaxy", kind: "Granite", origin: "Andhra Pradesh, India", price: "₹720 / sq.ft", finish: "Polished", image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1400&q=90" },
  { name: "Alaska White", kind: "Granite", origin: "Brazil", price: "₹1,050 / sq.ft", finish: "Polished", image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=90" },
  { name: "Blue Roma", kind: "Quartzite", origin: "Brazil", price: "₹2,450 / sq.ft", finish: "Polished", image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=90" },
  { name: "Taj Mahal", kind: "Quartzite", origin: "Brazil", price: "₹1,950 / sq.ft", finish: "Leathered", image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1400&q=90" },
];

const spaces = [
  ["Kitchen", "Calacatta Gold, Taj Mahal & engineered surfaces", "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=90"],
  ["Bathroom", "Sculptural stone, vanity tops & statement walls", "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=90"],
  ["Living", "Bookmatched feature walls & architectural slabs", "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1600&q=90"],
  ["Facade", "Durable granite and natural stone exteriors", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=90"],
];

const process = [
  ["01", "Consult", "Tell us about your space, taste and project requirements."],
  ["02", "Curate", "We shortlist slabs by movement, colour, origin and budget."],
  ["03", "Measure", "Our team coordinates site dimensions and fabrication details."],
  ["04", "Fabricate", "Precision cutting, bookmatching, edge profiles and finishing."],
  ["05", "Install", "Experienced craftsmen bring every vein and junction together."],
  ["06", "Complete", "Final inspection, care guidance and long-term support."],
];

function MarblePage() {
  const [filter, setFilter] = useState<"All" | Stone["kind"]>("All");
  const [selected, setSelected] = useState<Stone | null>(null);
  const [cart, setCart] = useState<Stone[]>([]);
  const [menu, setMenu] = useState(false);
  const [faq, setFaq] = useState<number | null>(0);
  const filtered = useMemo(() => filter === "All" ? stones : stones.filter((s) => s.kind === filter), [filter]);
  const add = (stone: Stone) => { setCart((items) => items.some((item) => item.name === stone.name) ? items : [...items, stone]); setSelected(stone); };

  return (
    <main className="min-h-screen bg-[#f7f6f3] text-[#1b1b1b] selection:bg-[#d4af37] selection:text-white">
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@500;600;700&family=Lato:wght@300;400;500;700&family=Playfair+Display:ital,wght@0,500;0,600;1,500;1,600&display=swap');html{scroll-behavior:smooth}.stone-serif{font-family:'Playfair Display',serif}.stone-cinzel{font-family:'Cinzel',serif}.stone-body{font-family:'Lato',sans-serif}.hide-scroll::-webkit-scrollbar{display:none}.hide-scroll{scrollbar-width:none}`}</style>

      <nav className="fixed left-0 right-0 top-0 z-50 border-b border-black/5 bg-white/75 backdrop-blur-xl">
        <div className="mx-auto flex h-[76px] max-w-[1600px] items-center justify-between px-5 md:px-10 lg:px-16">
          <a href="#top" className="stone-cinzel text-lg font-semibold tracking-[.22em]">AURELIA<span className="text-[#b8860b]">.</span></a>
          <div className={`${menu ? "flex" : "hidden"} absolute left-0 right-0 top-[76px] flex-col gap-6 border-b bg-white p-7 md:static md:flex md:flex-row md:items-center md:border-0 md:bg-transparent md:p-0`}>
            {[['Collections','#collections'],['Spaces','#spaces'],['Craft','#craft'],['Journal','#journal']].map(([label, href]) => <a key={label} href={href} onClick={() => setMenu(false)} className="stone-body text-xs uppercase tracking-[.2em] text-black/60 transition hover:text-[#b8860b]">{label}</a>)}
          </div>
          <div className="flex items-center gap-3"><button onClick={() => setSelected(cart[0] ?? stones[0])} className="hidden border border-black/10 px-4 py-2 text-xs uppercase tracking-[.18em] md:block">Selection {cart.length > 0 && <span className="ml-2 text-[#b8860b]">{cart.length}</span>}</button><button onClick={() => setMenu(!menu)} className="border border-black/10 px-3 py-2 text-xs md:hidden">{menu ? 'Close' : 'Menu'}</button></div>
        </div>
      </nav>

      <section id="top" className="relative flex min-h-[78vh] items-end overflow-hidden bg-[#171716] pt-[76px] text-white"><img src={stones[0].image} alt="Calacatta Oro marble interior" className="absolute inset-0 h-full w-full object-cover opacity-55" /><div className="absolute inset-0 bg-gradient-to-r from-[#111]/90 via-[#111]/45 to-[#111]/20" /><div className="relative mx-auto w-full max-w-[1500px] px-5 pb-20 md:px-10 lg:px-16 lg:pb-28"><p className="stone-cinzel text-[10px] uppercase tracking-[.35em] text-[#e3c875]">Natural stone · Curated collection</p><h1 className="stone-serif mt-5 max-w-5xl text-6xl leading-[.88] tracking-[-.05em] md:text-8xl lg:text-[9rem]">Stone with<br /><i>presence.</i></h1><p className="mt-8 max-w-xl stone-body text-sm leading-7 text-white/60">Rare marble, granite and quartzite selected for architecture that deserves to be remembered.</p></div></section>

      <section id="collections" className="px-5 py-24 md:px-10 lg:px-16 lg:py-32"><div className="mx-auto max-w-[1500px]">
        <div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="stone-cinzel text-[10px] uppercase tracking-[.35em] text-[#b8860b]">Curated by master artisans</p><h2 className="stone-serif mt-4 text-5xl leading-none tracking-[-.04em] md:text-7xl">Marble <i>& Granite</i><br />Collections</h2></div><p className="max-w-md stone-body text-sm leading-7 text-black/50">Every slab is selected for its natural movement, rarity, tone and ability to transform a space. Explore our hand-picked catalogue.</p></div>
        <div className="mt-12 flex flex-wrap gap-2 border-b border-black/10 pb-4">{(['All','Marble','Granite','Quartzite'] as const).map((item) => <button key={item} onClick={() => setFilter(item)} className={`px-5 py-3 stone-body text-[10px] uppercase tracking-[.22em] transition ${filter === item ? 'bg-[#1b1b1b] text-white' : 'text-black/50 hover:text-black'}`}>{item}</button>)}</div>
        <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{filtered.map((stone, i) => <motion.article layout key={stone.name} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.05}} className="group relative overflow-hidden bg-[#e8e5df]"><div className="aspect-[.78] overflow-hidden"><img src={stone.image} alt={stone.name} className="h-full w-full object-cover transition duration-1000 group-hover:scale-110" /><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-transparent to-transparent opacity-80" /></div><div className="absolute inset-x-0 bottom-0 p-6 text-white"><div className="flex justify-between gap-3"><div><p className="stone-cinzel text-[9px] tracking-[.2em] text-white/50">{stone.kind} · {stone.origin}</p><h3 className="stone-serif mt-2 text-2xl">{stone.name}</h3></div><span className="stone-body text-xs text-[#e3c875]">{stone.price}</span></div><div className="mt-4 flex items-center justify-between opacity-0 transition group-hover:opacity-100"><span className="text-[10px] uppercase tracking-[.18em] text-white/50">{stone.finish} finish</span><button onClick={() => add(stone)} className="border border-white/30 px-3 py-2 text-[9px] uppercase tracking-[.18em] hover:border-[#d4af37] hover:text-[#d4af37]">Add to Selection</button></div></div></motion.article>)}</div>
      </div></section>

      <section className="overflow-hidden bg-[#1b1b1b] py-24 text-white md:py-32"><div className="mx-auto grid max-w-[1500px] gap-16 px-5 md:grid-cols-[.75fr_1.25fr] md:px-10 lg:px-16"><div><p className="stone-cinzel text-[10px] uppercase tracking-[.35em] text-[#d4af37]">The Aurelia difference</p><h2 className="stone-serif mt-5 text-5xl leading-[.92] md:text-7xl">A slab is<br /><i>a composition.</i></h2><p className="mt-8 max-w-md stone-body text-sm leading-7 text-white/50">We do not sell stone by the square foot alone. We help you understand its story, movement, scale and light—then make it belong to your architecture.</p></div><div className="relative min-h-[500px] overflow-hidden"><img src={stones[0].image} alt="Luxury stone interior" className="absolute inset-0 h-full w-full object-cover opacity-70 transition duration-[1400ms] hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-tr from-[#1b1b1b]/70 via-transparent to-[#d4af37]/10" /><div className="absolute bottom-7 left-7"><p className="stone-cinzel text-[9px] tracking-[.3em] text-[#d4af37]">MATERIAL STUDY / 001</p><p className="mt-2 stone-serif text-3xl">Vein. Light. Silence.</p></div></div></div></section>

      <section id="spaces" className="px-5 py-24 md:px-10 lg:px-16 lg:py-32"><div className="mx-auto max-w-[1500px]"><div className="text-center"><p className="stone-cinzel text-[10px] uppercase tracking-[.35em] text-[#b8860b]">Inspired living spaces</p><h2 className="stone-serif mt-4 text-5xl md:text-7xl">Stone <i>in context.</i></h2><p className="mx-auto mt-5 max-w-xl stone-body text-sm leading-7 text-black/50">See how different materials create different moods—from quiet residential luxury to dramatic architectural statements.</p></div><div className="hide-scroll mt-14 flex snap-x gap-5 overflow-x-auto pb-4">{spaces.map(([name, desc, image]) => <article key={name} className="group relative min-w-[78vw] snap-start overflow-hidden md:min-w-[43vw] lg:min-w-[31vw]"><div className="aspect-[1.08] overflow-hidden"><img src={image} alt={name} className="h-full w-full object-cover transition duration-1000 group-hover:scale-105" /></div><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-transparent to-transparent" /><div className="absolute bottom-0 p-7 text-white"><p className="stone-cinzel text-[9px] tracking-[.3em] text-[#e3c875]">SPACE</p><h3 className="stone-serif mt-2 text-4xl">{name}</h3><p className="mt-2 max-w-xs stone-body text-xs leading-6 text-white/60">{desc}</p></div></article>)}</div></div></section>

      <section id="craft" className="bg-[#eeece7] px-5 py-24 md:px-10 lg:px-16 lg:py-32"><div className="mx-auto max-w-[1500px]"><div className="grid gap-12 md:grid-cols-2 md:items-end"><div><p className="stone-cinzel text-[10px] uppercase tracking-[.35em] text-[#b8860b]">From selection to perfection</p><h2 className="stone-serif mt-4 text-5xl leading-none md:text-7xl">The art of<br /><i>bringing stone home.</i></h2></div><p className="stone-body max-w-lg text-sm leading-7 text-black/50">A seamless experience from the first conversation to the final polish, delivered with obsessive attention to detail.</p></div><div className="mt-16 grid gap-px bg-black/10 md:grid-cols-3">{process.map(([n,title,desc]) => <div key={n} className="group bg-[#eeece7] p-8 transition hover:bg-white md:min-h-64"><span className="stone-cinzel text-[10px] text-[#b8860b]">{n}</span><h3 className="stone-serif mt-14 text-3xl">{title}</h3><p className="mt-3 max-w-xs stone-body text-sm leading-6 text-black/50">{desc}</p></div>)}</div></div></section>

      <section id="journal" className="px-5 py-24 md:px-10 lg:px-16"><div className="mx-auto max-w-[1500px]"><div className="flex items-end justify-between gap-5"><div><p className="stone-cinzel text-[10px] uppercase tracking-[.35em] text-[#b8860b]">The stone journal</p><h2 className="stone-serif mt-4 text-5xl md:text-7xl">Stories in <i>stone.</i></h2></div><span className="hidden text-xs uppercase tracking-[.2em] text-black/40 md:block">Insights · Materials · Architecture</span></div><div className="mt-12 grid gap-8 md:grid-cols-3">{[["How to choose the right marble for your kitchen","Material Guide",stones[0].image],["Bookmatching: when a slab becomes artwork","Craft & Detail",stones[2].image],["Marble vs granite: choosing by lifestyle","Stone Intelligence",stones[7].image]].map(([title,tag,image]) => <article key={title} className="group"><div className="aspect-[1.35] overflow-hidden bg-[#ddd]"><img src={image} alt="" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div><p className="mt-5 stone-cinzel text-[9px] tracking-[.25em] text-[#b8860b]">{tag}</p><h3 className="stone-serif mt-2 text-2xl leading-tight">{title}</h3><span className="mt-4 inline-block border-b border-black/20 pb-1 text-[10px] uppercase tracking-[.2em]">Read story ↗</span></article>)}</div></div></section>

      <section className="bg-[#171716] px-5 py-24 text-white md:px-10 lg:px-16 lg:py-32"><div className="mx-auto grid max-w-[1500px] gap-12 md:grid-cols-2"><div><p className="stone-cinzel text-[10px] uppercase tracking-[.35em] text-[#d4af37]">What our clients say</p><h2 className="stone-serif mt-5 text-5xl leading-none md:text-7xl">Quietly<br /><i>exceptional.</i></h2></div><blockquote className="border-l border-[#d4af37]/40 pl-7"><p className="stone-serif text-3xl leading-snug text-white/85">“The stone selection changed the entire feeling of our home. Aurelia understood the material before we even knew how to describe what we wanted.”</p><footer className="mt-7 stone-body text-xs uppercase tracking-[.18em] text-white/40">Private Residence · Mumbai</footer></blockquote></div></section>

      <section className="px-5 py-24 md:px-10 lg:px-16"><div className="mx-auto max-w-5xl text-center"><p className="stone-cinzel text-[10px] uppercase tracking-[.35em] text-[#b8860b]">Frequently asked</p><h2 className="stone-serif mt-4 text-5xl md:text-7xl">Stone, <i>answered.</i></h2><div className="mt-12 border-t border-black/10 text-left">{[["How do I choose between marble and granite?","Marble offers softer veining and a timeless, expressive surface. Granite is generally harder and highly practical for demanding applications."],["Can I see a slab before ordering?","Absolutely. We encourage clients to view full slabs where possible because natural stone varies in movement, tone and veining."],["Do you provide fabrication and installation?","Yes. Our service can cover selection, measurement, fabrication, finishing, delivery coordination and professional installation."],["Can I request a custom quote?","Yes. Add materials to your selection and contact us with your project dimensions, application and preferred finish for a tailored quotation."]].map(([q,a],i) => <div key={q} className="border-b border-black/10"><button onClick={() => setFaq(faq === i ? null : i)} className="flex w-full items-center justify-between gap-6 py-6 text-left stone-serif text-xl md:text-2xl"><span>{q}</span><span className="text-[#b8860b]">{faq === i ? '−' : '+'}</span></button>{faq === i && <p className="max-w-3xl pb-7 stone-body text-sm leading-7 text-black/50">{a}</p>}</div>)}</div></div></section>

      <section id="consult" className="relative overflow-hidden bg-[#d9d2c7] px-5 py-24 md:px-10 lg:px-16 lg:py-32"><div className="absolute right-[-10%] top-[-35%] h-[800px] w-[800px] rounded-full border border-white/50" /><div className="relative mx-auto grid max-w-[1500px] gap-14 md:grid-cols-[1fr_.8fr] md:items-end"><div><p className="stone-cinzel text-[10px] uppercase tracking-[.35em] text-[#7b5b00]">Begin your project</p><h2 className="stone-serif mt-5 text-6xl leading-[.88] tracking-[-.05em] md:text-8xl">Make room<br /><i>for something</i><br />extraordinary.</h2></div><div><p className="stone-body text-sm leading-7 text-black/55">Tell us what you are creating. We will help you find the stone, finish and fabrication approach that makes it exceptional.</p><button onClick={() => setSelected(cart[0] ?? stones[0])} className="mt-8 bg-[#1b1b1b] px-8 py-4 stone-body text-xs uppercase tracking-[.2em] text-white transition hover:-translate-y-1">Start a Conversation ↗</button></div></div></section>

      <footer className="bg-[#171716] px-5 py-16 text-white md:px-10 lg:px-16"><div className="mx-auto max-w-[1500px]"><div className="grid gap-12 md:grid-cols-[1.5fr_1fr_1fr_1fr]"><div><div className="stone-cinzel text-xl tracking-[.22em]">AURELIA<span className="text-[#d4af37]">.</span></div><p className="mt-5 max-w-xs stone-body text-sm leading-6 text-white/40">Natural stone for extraordinary architecture.</p></div><div><p className="stone-cinzel text-[9px] tracking-[.25em] text-white/40">EXPLORE</p><div className="mt-5 space-y-3 text-sm text-white/60"><a href="#collections" className="block hover:text-white">Collections</a><a href="#spaces" className="block hover:text-white">Spaces</a><a href="#craft" className="block hover:text-white">Craft</a></div></div><div><p className="stone-cinzel text-[9px] tracking-[.25em] text-white/40">CONTACT</p><div className="mt-5 space-y-3 text-sm text-white/60"><p>Mumbai · India</p><p>+91 00000 00000</p><p>hello@aurelia.stone</p></div></div><div><p className="stone-cinzel text-[9px] tracking-[.25em] text-white/40">VISIT</p><p className="mt-5 text-sm leading-6 text-white/60">By appointment only.<br />Mon–Sat · 10:00–18:00</p></div></div><div className="mt-14 border-t border-white/10 pt-6 text-[10px] uppercase tracking-[.16em] text-white/25">© 2026 Aurelia Stone Studio · Crafted with intention.</div></div></footer>

      {selected && <div className="fixed inset-0 z-[100] grid place-items-center bg-black/60 p-5 backdrop-blur-sm" onClick={() => setSelected(null)}><div className="w-full max-w-xl bg-[#f7f6f3] p-7" onClick={(e) => e.stopPropagation()}><div className="flex items-start justify-between"><div><p className="stone-cinzel text-[9px] tracking-[.25em] text-[#b8860b]">SELECTED STONE</p><h3 className="stone-serif mt-2 text-3xl">{selected.name}</h3></div><button onClick={() => setSelected(null)} className="text-2xl">×</button></div><img src={selected.image} alt={selected.name} className="mt-6 aspect-[1.7] w-full object-cover" /><div className="mt-6 grid grid-cols-2 gap-4 text-sm"><p><span className="text-black/40">Type</span><br />{selected.kind}</p><p><span className="text-black/40">Origin</span><br />{selected.origin}</p><p><span className="text-black/40">Finish</span><br />{selected.finish}</p><p><span className="text-black/40">Guide price</span><br />{selected.price}</p></div><button onClick={() => setSelected(null)} className="mt-7 w-full bg-[#1b1b1b] py-4 text-xs uppercase tracking-[.2em] text-white">Request this stone ↗</button></div></div>}
    </main>
  );
}
