import { createFileRoute } from "@tanstack/react-router";
import { Calculator, Upload } from "lucide-react";
import { PageHero, PageShell, Section } from "@/components/page-shell";
import { Reveal } from "@/components/reveal";

const title = "SS 304 Decorative Mesh Price Per Sq Ft in India | SteelX";
const description = "Get the exact factory price for SS 304 decorative metal screens. Compare SS 304 wire mesh partition prices and request a custom architectural quote.";
export const Route = createFileRoute("/pricing")({ head: () => ({ meta: [{ title }, { name: "description", content: description }, { name: "robots", content: "index,follow" }, { property: "og:title", content: title }, { property: "og:description", content: description }] }), component: PricingPage });
const rows = [["Natural Silver / Hairline", "₹350–₹550", "—", "₹350–₹550"], ["PVD Titanium Gold", "₹350–₹550", "+ ₹250–₹400", "₹600–₹950"], ["PVD Rose Gold / Copper", "₹350–₹550", "+ ₹300–₹500", "₹650–₹1,050"], ["PVD Titanium Black", "₹350–₹550", "+ ₹350–₹600", "₹700–₹1,150+"]];
function PricingPage() { return <PageShell><PageHero eyebrow="Commercial Pricing / RFQ" title="SS 304 Decorative Mesh Price Per Sq Ft in India" lead="A factory-direct pricing hub for architects, designers, procurement teams and contractors specifying stainless-steel architectural mesh, PVD finishes and fabricated partitions." /><Section>
<Reveal variant="up"><div className="relative overflow-hidden rounded-2xl border border-yellow-500/60 bg-gradient-to-br from-amber-50 via-orange-50 to-yellow-100 p-8 shadow-xl lg:p-10"><div className="relative"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.28em] text-amber-800"><Calculator className="h-4 w-4" /> AI Quick Answer</div><h2 className="mt-4 font-display text-2xl text-gray-900 lg:text-3xl">What is the SS 304 decorative mesh price per sq ft in India?</h2><p className="mt-4 max-w-5xl text-lg leading-8 text-gray-800">In India, indicative factory pricing for SS 304 decorative mesh typically ranges from <strong>₹350 to ₹550 per square foot</strong> for natural hairline or silver finishes. PVD Titanium Gold or Black can range from approximately <strong>₹600 to ₹1,150+ per square foot</strong>, depending on mesh density, wire gauge, finish, quantity and fabrication scope.</p></div></div></Reveal>
<article className="prose prose-lg mt-16 max-w-none prose-headings:font-display prose-headings:tracking-tight prose-a:text-yellow-700 prose-a:font-semibold"><h1>SS 304 Wire Mesh Partition Pricing &amp; Estimator</h1><p>SteelX Decor manufactures architectural products around exact blueprint specifications. Because every room divider, cabinet insert, suspended ceiling and feature screen can differ, standard e-commerce pricing rarely represents the final commercial scope.</p><p>Factory-direct pricing should be evaluated against substrate, wire weight, weave, PVD finish, cutting, framing, packing and logistics. Published numbers are budgeting ranges; final quotations depend on approved technical and commercial scope.</p><h2>Indicative SS 304 Decorative Mesh Pricing Matrix</h2></article>
<Reveal variant="up" className="my-10 overflow-x-auto rounded-2xl border border-gray-200 bg-white shadow-xl"><table className="w-full min-w-[820px] border-collapse text-left"><thead className="bg-gray-950 text-white"><tr><th className="p-5">Finish</th><th className="p-5">Base Mesh / sq ft</th><th className="p-5">PVD Premium / sq ft</th><th className="bg-amber-500/20 p-5 text-amber-300">Finished / sq ft</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r[0]} className={`border-b border-gray-200 ${i%2 ? "bg-amber-50/60" : "bg-white"}`}><td className="p-5 font-semibold">{r[0]}</td><td className="p-5">{r[1]}</td><td className="p-5 text-amber-700">{r[2]}</td><td className="bg-[#fff7e6] p-5 text-lg font-bold text-[#8b6517]">{r[3]}</td></tr>)}</tbody></table></Reveal>
<article className="prose prose-lg max-w-none prose-headings:font-display prose-headings:tracking-tight"><h2>How Custom SS 304 Designer Partition Costs are Calculated</h2><ol><li><strong>Raw Material Weight:</strong> Wire gauge and aperture determine stainless consumption.</li><li><strong>PVD Color Choice:</strong> Coating recipe and colour control affect the finish premium.</li><li><strong>Framing and Fabrication:</strong> Raw mesh and fully TIG-welded framed partitions have different production economics.</li><li><strong>Quantity &amp; Batch:</strong> Production volume and setup requirements influence unit cost.</li></ol><h2>What to Include in an RFQ</h2><ul><li>Project location and application</li><li>Approximate area and panel schedule</li><li>Mesh type, wire diameter and aperture</li><li>SS grade and PVD finish reference</li><li>Frame/fixing requirements</li><li>AutoCAD, PDF, elevations or BOQ/BOM</li><li>Target delivery date and installation scope</li></ul><h2>Value Engineering</h2><p>Cost can often be optimized through panel-size standardization, open-area adjustments, readily available weaves, simplified edge details and coordinated fabrication without abandoning the design intent.</p></article>
<Reveal variant="up" className="mt-14"><div className="relative overflow-hidden rounded-2xl bg-gray-950 p-8 text-white shadow-2xl lg:p-11"><div className="relative"><div className="flex items-center gap-3 text-amber-300"><Upload className="h-5 w-5" /><span className="text-xs font-bold uppercase tracking-[.28em]">Project RFQ</span></div><h3 className="mt-4 font-display text-3xl lg:text-4xl">Get a Custom Project Estimate</h3><p className="mt-4 max-w-3xl text-gray-300">Upload your AutoCAD drawings, elevation sketches or PDF blueprints for an itemized project quotation.</p><div className="mt-7 rounded-xl border border-dashed border-white/20 bg-white/5 p-6"><p className="text-sm text-white/60">[Inject Placeholder: Multi-step Lead Gen / RFQ Form with File Upload for CAD/PDFs]</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="h-11 rounded-lg border border-white/10 bg-white/5" /><div className="h-11 rounded-lg border border-white/10 bg-white/5" /><div className="h-11 rounded-lg border border-white/10 bg-white/5" /></div></div><p className="mt-4 text-xs text-white/40">Indicative pricing only. Final quotation depends on approved scope.</p></div></div></Reveal>
</Section></PageShell>; }
