import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, Check, ChevronDown } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { ScrollProgress } from "@/components/motion";
import { PvdHeroRebuilt } from "@/components/pvd-hero-rebuilt";
import { pvdImages, tones, textures, applications } from "@/data/pvd";
import { EditableSection, SiteEditorProvider, type EditorSection, type PageDocument } from "@/components/site-editor";
import "@/pvd-surfaces.css";

const title = "PVD Coated Stainless Steel Surfaces | SteelXDecor — Architectural Metal Specialist";
const description = "Explore SteelXDecor's PVD-coated stainless steel surfaces. Champagne, Gold, Rose Gold, Bronze, Black, Gunmetal, Titanium and Silver tones. Vacuum-deposited colour bonded to SS 304/316 Grade. Custom fabrication and global installation.";

export const Route = createFileRoute("/pvd-surfaces")({
  head: () => ({ meta: [
    { title }, { name: "description", content: description },
    { name: "keywords", content: "PVD coated stainless steel surfaces, PVD stainless steel panels, architectural PVD finish, designer stainless steel surfaces, PVD coated metal for interiors, vacuum PVD stainless steel, SS 304 Grade" },
    { property: "og:title", content: title }, { property: "og:description", content: description },
    { property: "og:type", content: "website" }, { name: "robots", content: "index,follow" },
  ]}), component: PvdSurfacesPage,
});

const sectionIds = ["introduction","overview","features","colours","textures","applications","grade","process","customization","buying","comparison","finder","alternatives","projects","specification","faqs","related","final"];
const defaults: PageDocument = { sections: sectionIds.map((id) => ({ id, type: id, visible: true } as EditorSection)), overrides: {} };

const projects = [
  ["The Vira Hotel Lobby", "Dubai, UAE", "Hospitality · 8,600 sq ft", "Champagne PVD — mirror, hairline, woven mesh", pvdImages.architecture],
  ["Aurum Flagship Store", "Mumbai, India", "Retail · 3,200 sq ft", "Rose Gold PVD — mitred frames, invisible fixings", pvdImages.architecture],
  ["Meridian Tower Facade", "Singapore", "Commercial · 64,000 sq ft", "Gunmetal PVD — bead-blasted, non-reflective", pvdImages.facade],
  ["Nikhil Gupta Residence", "Rajkot, Gujarat", "Residential · 9,400 sq ft", "Black PVD — hairline finish", pvdImages.cta],
  ["Atelier Nine Interiors", "London, UK", "Interiors · 5,100 sq ft", "Champagne / Vibration finish", pvdImages.architecture],
  ["SS Decorative Mesh", "International", "Architectural Mesh", "PVD-coated woven wire mesh", pvdImages.architecture],
];

const faqs = [
  ["What is PVD coating on stainless steel?", "PVD (Physical Vapour Deposition) is a vacuum-based process where vaporised metal condenses onto stainless-steel substrate and bonds at an atomic level. The resulting coating is measured in microns and is integral to the surface — not a paint, film, or electroplated layer."],
  ["What grade of stainless steel is used for PVD surfaces?", "SteelXDecor's standard substrate is SS 304 Grade stainless steel. SS 316 Grade is available on request for exterior or high-corrosion environments. All standard PVD surfaces are manufactured on SS PVD Coated 304 Grade unless otherwise specified."],
  ["Is PVD-coated stainless steel suitable for exterior use?", "SS 304 Grade PVD surfaces are suitable for sheltered exterior applications. For direct weather exposure, coastal environments, or high-humidity conditions, SS 316 Grade substrate is recommended."],
  ["Can PVD finishes be customised?", "Yes. SteelXDecor offers eight standard PVD tones — Champagne, Gold, Rose Gold, Bronze, Black, Gunmetal, Titanium, and Silver — plus custom colour matching. Surface textures and dimensions can also be customized per project."],
  ["How is PVD different from electroplating or painting?", "PVD deposits colour through physical vapour deposition in a vacuum chamber, bonding at an atomic level to the stainless-steel substrate. Electroplating and painting apply colour on top of the surface."],
  ["Where are PVD surfaces commonly used in architecture?", "PVD-coated stainless-steel surfaces are used for facades, hospitality lobbies, retail interiors, residential feature walls, commercial ceilings, decorative screens, room dividers, lift jamb cladding, and joinery."],
  ["How are PVD surfaces installed?", "SteelXDecor crates panels in installation sequence and deploys own in-house installation teams globally. Installation methodology is coordinated during the specification phase."],
  ["How should PVD-coated stainless steel be maintained?", "Regular cleaning with non-abrasive methods preserves finish quality. Avoid chloride-based cleaners on 304 Grade stainless steel. Mirror finishes may require more frequent cleaning."],
  ["Can PVD surfaces be custom fabricated after coating?", "Yes. Cutting, bending, welding, and edge finishing are performed after PVD coating to preserve colour continuity across joints and edges."],
  ["What is the minimum order quantity for PVD surfaces?", "Project quantities range from single-room interiors to multi-site developments. Batch colour-matching is controlled against a signed sample for every project. Contact SteelXDecor for project-specific requirements and lead times."],
];

const schema = { "@context": "https://schema.org", "@type": "WebPage", name: "PVD Coated Stainless Steel Surfaces", description, url: "https://steelxdecor.com/pvd-surfaces", publisher: { "@type": "Organization", name: "SteelXDecor", url: "https://steelxdecor.com" }, mainEntity: { "@type": "ItemList", name: "PVD Surface Colour Range", itemListElement: tones.map((t, i) => ({ "@type": "ListItem", position: i + 1, item: { "@type": "Product", name: `${t.name} PVD Stainless Steel` } })) }, hasPart: { "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) } };

function Section({ id, children, dark = false }: { id: string; children: React.ReactNode; dark?: boolean }) { return <EditableSection id={id}><section id={id} className={`pvd-seo-section ${dark ? "pvd-dark" : ""}`}>{children}</section></EditableSection>; }
function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="pvd-eyebrow">{children}</p>; }
function Heading({ children }: { children: React.ReactNode }) { return <h2 className="pvd-heading">{children}</h2>; }
function CTA({ href, children, filled = false }: { href: string; children: React.ReactNode; filled?: boolean }) { return <Link to={href} className={`pvd-button ${filled ? "pvd-button-filled" : ""}`}>{children}<ArrowUpRight size={15}/></Link>; }

function PvdSurfacesPage() {
  return <SiteEditorProvider slug="pvd-surfaces" defaults={defaults}>{() => <div className="pvd-category min-h-screen bg-background text-foreground">
    <ScrollProgress /><SiteHeader />
    <main>
      <PvdHeroRebuilt />
      <Section id="introduction"><div className="pvd-narrow"><Eyebrow>01 · INTRODUCTION</Eyebrow><Heading>What Are PVD Surfaces?</Heading><p>PVD coating transforms bare stainless-steel sheet into an architectural surface with embedded colour. Unlike paint, electroplating, or film laminate, PVD bonds metal atoms directly to the stainless-steel substrate inside a vacuum chamber. The result is a finish measured in microns that behaves like the material it coats and performs at architectural scale — from a single hotel lobby panel to a 64,000 sq ft commercial facade.</p><p>SteelXDecor supplies PVD-coated stainless-steel surfaces designed for architects, interior designers, contractors, and fabricators who require colour consistency, material integrity, and technical specification at project scale. Every surface begins with mill-checked SS 304 or 316 Grade stainless steel, moves through precision surface preparation, and completes with vacuum PVD colour bonding controlled against a signed sample per batch.</p><CTA href="#final">Discuss Your Project Requirements</CTA></div></Section>
      <Section id="overview" dark><div className="pvd-split"><div><Eyebrow>02 · PRODUCT OVERVIEW</Eyebrow><Heading>PVD Coated Stainless Steel Surfaces</Heading><p>PVD-coated stainless-steel surfaces are architectural panels, sheets, mesh, and profiles manufactured by depositing vapourised metal onto stainless-steel substrate in a vacuum environment. The PVD layer bonds atomically to the surface — it is not a paint, a film, or a coating applied on top.</p></div><ul className="pvd-spec-list">{["Substrate: SS 304 Grade stainless steel (316 available on request)","Process: Physical Vapour Deposition in vacuum chamber","Coating thickness: Measured in microns","Bond type: Atomic bond to substrate — not surface-applied","Base textures: Hairline, Mirror, Vibration, Bead Blast, Satin","Finish colours: Silver, Champagne, Gold, Rose Gold, Bronze, Gunmetal, Black, Titanium"].map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul></div></Section>
      <Section id="features"><Eyebrow>03 · KEY FEATURES</Eyebrow><Heading>Engineered From Substrate to Surface</Heading><div className="pvd-feature-grid">{[["Vacuum PVD Colour Bonding","Colour is deposited through vaporisation of solid metal inside a vacuum chamber, where ionised vapour condenses onto the stainless-steel panel and bonds at an atomic level."],["SS 304 Grade Stainless Steel Substrate","Every surface begins with mill-checked SS 304 Grade stainless steel. For exterior installations, SS 316 Grade is available on request."],["Eight Standard PVD Colour Tones","Champagne, Gold, Rose Gold, Bronze, Black, Gunmetal, Titanium, and Silver — plus custom colour matching."],["Five Surface Textures","Hairline, Mirror, Vibration, Bead Blast, and Satin change how light interacts with the same PVD colour."],["Custom Fabrication","Panels, sheets, mesh, profiles, and bespoke elements can be cut, bent, welded and finished for project requirements."],["Global Installation","Panels are crated in installation sequence and SteelXDecor deploys installation crews globally."]].map(([h,p],i)=><article className="pvd-feature" key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p></article>)}</div></Section>
      <Section id="colours" dark><Eyebrow>04 · COLOUR COLLECTION</Eyebrow><Heading>PVD Finish Colours</Heading><p className="pvd-lead">SteelXDecor applies PVD colour across eight standard tones plus custom colour matching on request. Each tone carries distinct architectural characteristics — reflectivity, warmth, and visual reading at distance.</p><div className="pvd-colour-grid">{tones.map(t=><article className="pvd-colour-card" key={t.id}><img src={t.image} alt={`${t.name} PVD stainless steel finish`} loading="lazy"/><div className="pvd-colour-overlay"><span>SS PVD Coated 304 Grade</span><h3>{t.name}</h3><p>{t.note}</p><small>{t.textures.join(" · ")} · {t.applications.join(" · ")}</small></div></article>)}</div></Section>
      <Section id="textures"><Eyebrow>05 · TEXTURE OPTIONS</Eyebrow><Heading>Surface Textures</Heading><p className="pvd-lead">Mechanical preparation before PVD deposition defines how light interacts with the finished surface.</p><div className="pvd-texture-grid">{textures.map(t=><article className="pvd-texture" key={t.id}><img src={t.image} alt={`${t.name} stainless steel texture`} loading="lazy"/><div><span>{t.name}</span><p>{({hairline:"Directional reflection. Light stretches along the grain, creating soft luminosity that moves with the viewer's angle.",mirror:"High-gloss reflection creating near-perfect reflective surface. Mirror finishes amplify light and space.",vibration:"Textured micro-reflection that breaks up light into subtle movement. Reduces glare while maintaining colour depth.","bead-blast":"Matte diffusion through spherical bead particle impact. Produces a uniform, non-directional surface.",satin:"A balanced sheen between hairline and mirror — enough reflectivity to feel polished, enough diffusion to remain understated."} as Record<string,string>)[t.id]}</p></div></article>)}</div></Section>
      <Section id="applications" dark><Eyebrow>06 · APPLICATIONS</Eyebrow><Heading>Designed for Architecture</Heading><p className="pvd-lead">Each application requires different performance characteristics from a PVD surface — reflectivity, texture, corrosion resistance, and fabrication complexity vary by use case.</p><div className="pvd-application-grid">{applications.map(a=><article key={a.name}><img src={a.image} alt={a.alt} loading="lazy"/><div><span>{a.index}</span><h3>{a.name}</h3><p>{a.line}</p><small>{a.name === "Facades" ? "Exterior cladding for commercial buildings and hospitality exteriors; Bronze and Gunmetal are frequently specified for their architectural character." : a.name === "Hospitality" ? "Champagne and Gold finishes bring warmth to lobbies, restaurants, bars, wall panels and reception features." : `PVD surfaces engineered for ${a.name.toLowerCase()} applications with application-specific texture and fabrication.`}</small></div></article>)}</div></Section>
      <Section id="grade"><div className="pvd-split pvd-grade"><div><Eyebrow>07 · MATERIAL & GRADE</Eyebrow><Heading>Material & Grade Specifications</Heading><h3>SS 304 Grade — Standard Substrate</h3><p>SteelXDecor's primary material specification is SS 304 Grade stainless steel — an austenitic chromium-nickel alloy widely specified for architectural interiors. 304 Grade offers excellent formability, weldability, and corrosion resistance for indoor and sheltered applications.</p></div><div><h3>SS 316 Grade — Available on Request</h3><p>For exterior or high-corrosion environments, SS 316 Grade stainless steel is available on request. 316 Grade contains molybdenum, which enhances corrosion resistance against chlorides and marine environments.</p><div className="pvd-callout"><strong>SS PVD Coated 304 Grade</strong><br/>All standard PVD surfaces are manufactured on SS PVD Coated 304 Grade stainless steel unless 316 Grade is explicitly requested.</div></div></div></Section>
      <Section id="process" dark><Eyebrow>08 · HOW PVD WORKS</Eyebrow><Heading>The Process</Heading><p className="pvd-lead">PVD is a vacuum-based coating process that bonds metal colour directly to stainless-steel substrate. The process differs fundamentally from electroplating, painting, or film lamination.</p><div className="pvd-process">{[["01","Raw Steel","Mill sheet 304 or 316 Grade is selected and checked for flatness, surface condition, and material integrity."],["02","Surface Preparation","Hairline, Vibration, Bead Blast, or Mirror defines the base surface the PVD coating will bond to."],["03","Vacuum Chamber","The chamber is evacuated so nothing sits between the metal source and the panel surface."],["04","Vapourisation","Solid target metal is vaporised inside the vacuum chamber."],["05","Ionisation & Deposition","The vapour is ionised and directed toward the panel. PVD layer condenses and bonds atomically."],["06","Finished Surface","A coloured architectural surface — not a paint, not a film, not an electroplated layer."]].map(([n,h,p])=><article key={n}><b>{n}</b><h3>{h}</h3><p>{p}</p></article>)}</div><div className="pvd-why"><h3>Why PVD Over Electroplating?</h3><p>Electroplating deposits colour through an electrical chemical process onto the surface. PVD deposits colour through physical vapour deposition in vacuum — the coating bonds at an atomic level and is integral to the surface.</p></div></Section>
      <Section id="customization"><Eyebrow>09 · DESIGN & CUSTOMIZATION</Eyebrow><Heading>Made to the Project</Heading><p className="pvd-lead">SteelXDecor fabricates PVD surfaces to project-specific requirements.</p><div className="pvd-detail-grid">{[["Pattern","Solid panels, perforated patterns, expanded mesh, woven wire mesh, and laser-cut designs"],["Dimensions","Panels and sheets fabricated to project-specific dimensions and fabrication tolerances"],["Finish","Five textures across eight PVD colour tones, plus custom colour matching on request"],["Frame & Edging","Panels with or without framing, mitred edges, concealed fixings, and integrated frame profiles"],["Fabrication","Cutting, bending, welding, and edge finishing performed after PVD coating"],["Application-Specific Customization","Facade panels, lift jamb cladding, ceiling baffles, room dividers, screens, and furniture elements"]].map(([h,p])=><article key={h}><h3>{h}</h3><p>{p}</p></article>)}</div></Section>
      <Section id="buying" dark><Eyebrow>10 · BUYING CONSIDERATIONS</Eyebrow><Heading>Specify With Confidence</Heading><p className="pvd-lead">Before specifying PVD-coated stainless-steel surfaces for a project, consider the following factors:</p><div className="pvd-buying">{["Application","Indoor or Outdoor Use","Dimensions","Pattern & Opening","Material Grade","Finish & Texture","Frame Requirements","Installation Method","Maintenance","Project Quantity"].map((h,i)=><article key={h}><b>0{i+1}</b><h3>{h}</h3><p>{["Determine whether the surface is for interior or exterior use.","Outdoor installations require SS 316 Grade substrate.","Define panel dimensions and fabrication tolerances early.","Specify pattern type, opening size, and construction method.","Confirm SS 304 or SS 316 Grade for the project environment.","Select texture based on desired light interaction and maintenance requirements.","Determine whether panels will be supplied with or without framing.","Confirm on-site fabrication or pre-fabricated installation requirements.","PVD-coated surfaces are maintenance-friendly with non-abrasive cleaning.","Larger quantities require batch colour-matching against a signed control sample."][i]}</p></article>)}</div></Section>
      <Section id="comparison"><Eyebrow>11 · COMPARISON</Eyebrow><Heading>Colour Comparison</Heading><div className="pvd-table-wrap"><table><thead><tr><th>Specification</th><th>Champagne</th><th>Gunmetal</th><th>Black</th></tr></thead><tbody>{[["Colour Character","Warm neutral","Cool graphite","Near-black"],["Reflectivity","Medium","Low","High or low"],["Texture Options","Hairline / Vibration","Bead blast / Hairline","Mirror / Bead blast / Satin"],["Key Applications","Hospitality, Luxury interiors","Commercial, Screens, Facades","Luxury interiors, Joinery, Screens"],["Best For","Quiet, luminous","Structural","Absolute"]].map(r=><tr key={r[0]}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></div></Section>
      <Section id="finder" dark><div className="pvd-finder"><div><Eyebrow>12 · FINISH FINDER</Eyebrow><Heading>Find Your Finish</Heading><p>Answer the three questions below and we'll suggest three PVD surfaces worth sampling.</p></div>{[["Where is it going?","Façade · Hotel · Retail · Residence · Office · Screen · Ceiling · Feature wall"],["What should it feel like?","Warm · Reflective · Dark · Tactile · Quiet · Statement"],["How should light behave?","Soft · Directional · Reflective · Diffused"]].map(([h,p],i)=><div className="pvd-question" key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p><ChevronDown size={17}/></div>)}<div className="pvd-finder-result">Answer the three questions and we'll suggest three surfaces worth sampling.</div></div></Section>
      <Section id="alternatives"><Eyebrow>13 · WHY PVD</Eyebrow><Heading>Why PVD Over Alternatives</Heading><div className="pvd-alternatives">{[["PVD vs Paint","Paint sits on the surface and can chip, peel, or fade. PVD colour bonds at an atomic level to the stainless-steel substrate."],["PVD vs Electroplating","Electroplating deposits colour through an electrical chemical process. PVD deposits colour through physical vapour deposition in vacuum."],["PVD vs Film Laminate","Film laminate applies a decorative film onto the substrate. PVD colour is deposited directly onto the stainless-steel surface."],["PVD vs Raw Stainless Steel","Raw stainless steel is naturally silver-toned. PVD adds the full colour spectrum while preserving the underlying material properties."]].map(([h,p])=><article key={h}><h3>{h}</h3><p>{p}</p></article>)}</div></Section>
      <Section id="projects" dark><Eyebrow>14 · FEATURED PROJECTS</Eyebrow><Heading>Projects Completed Worldwide</Heading><p className="pvd-lead">SteelXDecor has delivered PVD-coated stainless-steel surfaces for commercial, hospitality, retail, residential, and institutional projects across India, UAE, UK, and Singapore.</p><div className="pvd-project-grid">{projects.map(([h,loc,meta,finish,img])=><article key={h}><img src={img} alt={`${h} PVD stainless steel project`} loading="lazy"/><div><span>{loc}</span><h3>{h}</h3><small>{meta}</small><p>{finish}</p></div></article>)}</div></Section>
      <Section id="specification"><div className="pvd-spec-cta"><div><Eyebrow>15 · SPECIFICATION DOWNLOAD</Eyebrow><Heading>Download the Material Guide</Heading><p>A comprehensive material specification document covering substrate grades, PVD coating properties, texture options, colour references, fabrication tolerances, installation methodology, and maintenance protocols.</p></div><CTA href="#final" filled>Download Material Guide</CTA></div></Section>
      <Section id="faqs" dark><Eyebrow>16 · FAQs</Eyebrow><Heading>Frequently Asked Questions</Heading><div className="pvd-faqs">{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={17}/></summary><p>{a}</p></details>)}</div></Section>
      <Section id="related"><Eyebrow>17 · RELATED PRODUCTS</Eyebrow><Heading>Explore the Full Product Range</Heading><div className="pvd-related">{[["PVD Marble Collection","PVD-coated marble-effect panels for feature walls, reception counters, and luxury residential surfaces.","/marble"],["Vintex Web","Specialty woven wire mesh with PVD coating for architectural screens, partitions, and ceilings.","/vintex-web"],["Designer Sheets","Finished stainless-steel sheets in Mirror, Hairline, Vibration, and Bead Blast textures.","/designer-sheets"],["SS Decorative Mesh PVD","Woven wire mesh with vacuum PVD coating for decorative partitions and screens.","/ss-decorative-mesh-pvd"],["PVD Profiles — T, U & L Patti","Decorative stainless-steel profiles for edge detailing, cladding frames, and architectural trim.","/materials"],["PVD Lift Jamb & Cladding Panels","PVD-coated panels designed for lift jamb cladding and elevator interiors.","/materials"],["PVD Coated Pipes","Decorative stainless-steel pipes with PVD surface finishes for architectural railings and furniture frames.","/materials"],["TI-PVD Furniture Surfaces","Tabletops, consoles, showcases, and partition panels with full PVD surface treatment.","/materials"]].map(([h,p,to])=><Link to={to} key={h}><span>{h}</span><p>{p}</p><ArrowUpRight size={17}/></Link>)}</div></Section>
      <Section id="final" dark><div className="pvd-final"><Eyebrow>18 · START A PROJECT</Eyebrow><Heading>Ready to Specify a PVD Surface?</Heading><p>Every project starts with a specification conversation. Share your dimensions, application, desired finish, and grade requirement and the SteelXDecor team will recommend the right material, construction, and PVD finish for your project.</p><div className="pvd-actions"><CTA href="/contact" filled>Start a Project Consultation</CTA><CTA href="/contact">Request Samples</CTA><CTA href="#specification">Download Material Guide</CTA></div></div></Section>
    </main><SiteFooter /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
  </div>}</SiteEditorProvider>;
}
