import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, Check, X } from "lucide-react";
import { PageHero, PageShell, Section } from "@/components/page-shell";

const title = "Premium PVD Coated SS 304 Decorative Mesh | SteelX Decor";
const description = "Premium PVD coated SS 304 decorative mesh for luxury partitions, ceilings, hospitality interiors, retail displays and architectural metalwork.";
export const Route = createFileRoute("/pvd-coated-mesh")({ head: () => ({ meta: [{ title }, { name: "description", content: description }, { name: "robots", content: "index,follow" }, { property: "og:title", content: title }, { property: "og:description", content: description }] }), component: PvdCoatedMeshPage });
const colors = [["PVD Gold","Brilliant, timeless metallic warmth"],["PVD Rose Gold","Warm copper-inflected architectural tone"],["PVD Titanium Black","Deep contemporary statement finish"]] as const;
function PvdCoatedMeshPage() { const [quoteColor,setQuoteColor] = useState<string | null>(null); return <PageShell>
<PageHero eyebrow="Core Finish Hub / PVD" title="Premium PVD Coated SS 304 Decorative Mesh" lead="A finish-led architectural material hub for designers, architects, fabricators and procurement teams specifying stainless steel mesh in luxury interiors and commercial spaces." /><Section>
<div className="rounded-xl border border-yellow-400 bg-gradient-to-r from-yellow-50 to-amber-100 p-8 shadow-sm"><h2 className="mb-3 text-2xl font-bold text-gray-900">AI Quick Answer: Can stainless steel wire mesh be PVD coated in gold?</h2><p className="text-lg text-gray-800"><strong>Yes.</strong> SS 304 is a widely used substrate for PVD architectural finishes. The final performance depends on substrate preparation, coating system, environment and maintenance.</p></div>
<article className="prose prose-lg mt-14 max-w-none prose-headings:font-display prose-headings:tracking-tight prose-a:text-yellow-700 prose-a:font-semibold"><h1>Premium PVD Coated SS 304 Decorative Mesh</h1><p>At SteelX Decor, we engineer metallic luxury for architects, interior designers and furniture fabricators. Standard silver stainless steel can become the starting point for gold, rose gold, champagne, bronze or black architectural expressions.</p><p>PVD applies a controlled decorative coating to a prepared metal substrate. The specification combines stainless steel with a finish system selected around the environment, geometry and desired visual effect.</p><h2>The SteelX PVD Color Palette</h2><p>Finish selection should be made against physical samples whenever possible because lighting, adjacent materials, viewing angle and mesh geometry influence perceived colour.</p></article>
<div className="my-10 grid gap-5 md:grid-cols-3">{colors.map(([name,body],i)=><div key={name} className="group rounded-2xl border border-border bg-card p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className={`h-28 rounded-xl ${i===0?"bg-gradient-to-br from-[#f6e2a5] via-[#c99d4c] to-[#8f6823]":i===1?"bg-gradient-to-br from-[#f4c4b8] via-[#b86f61] to-[#70433d]":"bg-gradient-to-br from-[#505050] via-[#1d1d1d] to-[#050505]"} shadow-inner`} /><p className="mt-5 text-xs uppercase tracking-[.22em] text-gold">PVD Finish</p><h3 className="mt-2 font-display text-2xl">{name}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{body}</p><button type="button" onClick={()=>setQuoteColor(name)} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-full bg-gray-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-gray-800">Get Quote for {name.replace("PVD ","")} Mesh <ArrowUpRight className="h-4 w-4" /></button></div>)}</div>
<article className="prose prose-lg max-w-none prose-headings:font-display prose-headings:tracking-tight prose-a:text-yellow-700 prose-a:font-semibold"><h2>Why PVD is Different from Paint or Powder Coating</h2><p>Powder coating is an applied polymer finish; PVD is a vacuum-deposited coating system on a prepared metal substrate. PVD can provide excellent adhesion, wear resistance and colour stability when the substrate, coating and environment are correctly specified. It should not be marketed as universally indestructible or immune to corrosion, staining or finish change.</p><h2>PVD Mesh for Architectural Applications</h2><p>Typical applications include room dividers, wardrobe inserts, elevator surrounds, reception features, bar fronts, ceiling drapery, retail displays and feature screens. Open area can be selected to balance privacy, transparency, light transmission and airflow.</p><ol><li>Select grade and mesh construction.</li><li>Confirm wire diameter, aperture and open area.</li><li>Approve a physical PVD finish sample.</li><li>Define framing, fixing, cleaning and installation requirements.</li></ol><h2>Technical Specification Checklist</h2><div className="not-prose my-8 overflow-x-auto rounded-lg border border-border"><table className="w-full min-w-[720px] border-collapse text-left text-sm"><thead className="bg-gray-900 text-white"><tr><th className="p-4">Parameter</th><th className="p-4">Typical Direction</th><th className="p-4">Project Decision</th></tr></thead><tbody className="text-gray-700"><tr className="border-b"><td className="p-4 font-semibold">Base material</td><td className="p-4">SS 304; SS 316 where warranted</td><td className="p-4">Confirm grade and exposure</td></tr><tr className="border-b bg-gray-50"><td className="p-4 font-semibold">Finish</td><td className="p-4">Gold, rose gold, champagne, bronze, black</td><td className="p-4">Approve physical sample</td></tr><tr><td className="p-4 font-semibold">Mesh geometry</td><td className="p-4">Woven, crimped, spiral, cable/rod</td><td className="p-4">Coordinate with application</td></tr></tbody></table></div></article>
{quoteColor ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="relative w-full max-w-lg rounded-2xl bg-white p-7 shadow-2xl"><button type="button" aria-label="Close" onClick={()=>setQuoteColor(null)} className="absolute right-4 top-4 rounded-full p-2 text-gray-500 hover:bg-gray-100"><X className="h-5 w-5" /></button><p className="text-xs font-bold uppercase tracking-[.25em] text-gold">Quick Inquiry</p><h2 className="mt-3 font-display text-3xl">Quote for {quoteColor.replace("PVD ","")} Mesh</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Tell us your approximate area, mesh construction and project location. This placeholder is ready to be replaced by the connected lead form.</p><div className="mt-6 grid gap-3"><input aria-label="Name" placeholder="Your name" className="rounded-lg border border-gray-200 px-4 py-3 outline-none focus:border-amber-500" /><input aria-label="Phone" placeholder="Phone / WhatsApp" className="rounded-lg border border-gray-200 px-4 py-3 outline-none focus:border-amber-500" /><input aria-label="Area" placeholder="Approx. area (sq ft)" className="rounded-lg border border-gray-200 px-4 py-3 outline-none focus:border-amber-500" /><textarea aria-label="Project details" placeholder="Project / mesh requirements" rows={3} className="rounded-lg border border-gray-200 px-4 py-3 outline-none focus:border-amber-500" /></div><button type="button" onClick={()=>setQuoteColor(null)} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-full bg-gray-950 px-6 py-3.5 text-sm font-bold text-white hover:bg-gray-800">Submit Inquiry <Check className="h-4 w-4" /></button></div></div> : null}
</Section></PageShell>; }
