import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, ShoppingBag } from "lucide-react";
import { PageHero, PageShell, Section } from "@/components/page-shell";
import { Reveal } from "@/components/reveal";
import { img } from "@/data/mesh";

const title = "SS 304 Decorative Mesh | Buy Online India | SteelX Decor";
const description = "Browse SS 304 decorative architectural mesh for partitions, ceilings, cabinetry and feature screens. Request samples or a project quotation from SteelX Decor.";
export const Route = createFileRoute("/ss-decorative-mesh")({ head: () => ({ meta: [{ title }, { name: "description", content: description }, { name: "robots", content: "index,follow" }, { property: "og:title", content: title }, { property: "og:description", content: description }] }), component: SsDecorativeMeshPage });
const products = [["SXD-M01","SS 304 Woven Architectural Mesh",img.meshHero,"Plain, leno and decorative woven constructions for partitions, cabinetry and feature screens."],["SXD-M02","PVD Gold Decorative Mesh",img.pvdSteel,"Premium gold-toned SS 304 mesh for hospitality, luxury retail and residential interiors."],["SXD-M03","Crimped Architectural Mesh",img.meshApplication,"Rigid textured mesh for framed partitions, screens and statement architectural surfaces."]];
function SsDecorativeMeshPage(){return <PageShell><PageHero eyebrow="Material Category / SS 304" title="SS 304 Decorative Mesh" lead="Architectural stainless-steel mesh for partitions, ceilings, cabinetry, retail displays and feature screens — with sample requests and project quotation pathways."/><Section><div className="grid gap-6 md:grid-cols-3">{products.map(([sku,name,image,body],i)=><Reveal key={sku} variant="up" delay={i*80}><article className="group overflow-hidden rounded-2xl border border-border bg-card shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="aspect-[4/3] overflow-hidden bg-gray-100"><img src={image} alt={name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div><div className="p-6"><p className="text-[10px] uppercase tracking-[.25em] text-muted-foreground">{sku}</p><h2 className="mt-2 font-display text-2xl">{name}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{body}</p><div className="mt-6 grid grid-cols-2 gap-2"><button type="button" className="inline-flex items-center justify-center gap-2 rounded-full bg-gray-950 px-4 py-3 text-xs font-bold text-white transition hover:bg-gray-800"><ShoppingBag className="h-4 w-4" /> Add to Cart</button><Link to="/contact" className="inline-flex items-center justify-center gap-2 rounded-full border border-gray-300 px-4 py-3 text-xs font-bold text-gray-900 transition hover:border-gray-900">Request Sample <ArrowUpRight className="h-4 w-4" /></Link></div></div></article></Reveal>)}</div><Reveal variant="up" className="mt-14"><div className="rounded-2xl border border-amber-200 bg-gradient-to-r from-amber-50 to-orange-50 p-8 lg:p-10"><p className="text-xs font-bold uppercase tracking-[.28em] text-amber-800">Transactional / Project RFQ</p><h2 className="mt-3 font-display text-3xl">Need a larger quantity or custom construction?</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-amber-950/70">For architectural projects, request a sample or submit your drawings for a custom quotation. Final price depends on mesh geometry, wire gauge, area, finish and fabrication.</p><Link to="/pricing" className="mt-6 inline-flex items-center gap-2 rounded-full bg-gray-950 px-6 py-3.5 text-sm font-bold text-white">Get Project Pricing <ArrowUpRight className="h-4 w-4" /></Link></div></Reveal></Section></PageShell>}
