import { createFileRoute } from "@tanstack/react-router";
import bungalow from "@/assets/proj-bungalow.jpg";
import commercial from "@/assets/proj-commercial.jpg";
import interiors from "@/assets/proj-interiors.jpg";
import detailA from "@/assets/proj-detail-a.jpg";
import detailB from "@/assets/proj-detail-b.jpg";
import inspection from "@/assets/inspection.jpg";
import pvdChamber from "@/assets/pvd-chamber.jpg";
import { ProjectDetailPage, type ProjectDetailData } from "@/components/project-detail-page";
const data:ProjectDetailData={
 title:"High Street Phoenix Canopy, Lower Parel",kicker:"Retail · Lower Parel, Mumbai · 2024 · Completed",hero:{src:commercial,alt:"Water ripple PVD ss-304 canopy at High Street Phoenix, Lower Parel — casting dynamic, shifting light patterns on the pavement that change with the sun’s position, enhancing retail experience without glare."},
 facts:[["Client","Phoenix Mills"],["Location","Lower Parel, Mumbai, Maharashtra"],["Area","4,500 sq ft"],["Year","2024"],["Status","Completed"],["Scope","Retail canopy metalwork, supporting columns"],["Finish","Water ripple PVD (ss-304)"],["Services","Facade metal, Custom fabrication, Installation"]],
 brief:[`Phoenix Mills wanted a High Street Phoenix canopy that does <strong>more than just shade</strong> — it needs to create an <em>experience</em>. The brief: <em>“Make walking from the mall to the street feel special, not transitional.”</em> We proposed <strong>ss-pvd-304 with water ripple texture</strong> — not as a decorative film, but as <strong>structural metal bent into 3D ripples before coating</strong>. This turns sunlight into moving, organic patterns on the pavement below (like light through water), while the texture inherently diffuses glare — critical for Mumbai’s intense retail-hour sun.`],
 approach:[`We modeled <strong>sun-path dynamics</strong> for Lower Parel (specific to the canopy’s east-west orientation) to determine ripple depth/pitch for optimal pavement patterning. The <strong>water ripple isn’t surface-applied</strong> — it’s <strong>ss-pvd-304 laser-cut into strips, then bent into 3D waves</strong> (50mm peak-to-trough) <em>before</em> PVD coating. This means: <strong>the texture wears with the metal</strong> (no peeling during monsoons); light diffusion is inherent to the shape (no coating failure risk); and edges are smooth, rounded radii (no sharp corners to trap dirt or corrode).`,`The <strong>ss-pvd-304 substrate</strong> was selected for Lower Parel’s urban exposure (moderate salt, high pollution). We rejected painted or anodized alternatives — they’d require repainting every 18 months in this high-traffic zone.`],
 approachImage:{src:detailA,alt:"Underside of High Street Phoenix canopy, Lower Parel — showing ss-pvd-304 bent into structural water ripple shape before PVD coating (texture is metal-formed, not surface-applied) for monsoon durability."},
 material:[`Grade <strong>ss-pvd-304</strong> (chosen for balance of cost, formability, and urban corrosion resistance). Hairline-prepped to Ra 0.8μm, then <strong>water ripple PVD coated</strong> — but critically, the <strong>ripple shape was formed in the ss-304 before coating</strong>. The PVD coating itself is a <strong>clear protective topcoat</strong> (CrN-based, 0.8μm) over the bronze-tinted base layer — this is why we call it “water ripple PVD”: the <em>texture</em> creates the effect, the PVD just seals and tints it.`,`We validated with: <strong>ASTM D4060 abrasion</strong> — 1,000 cycles CS-10 wheels with zero texture loss; <strong>ASTM D4587 UV</strong> — 1,200 hours with ΔE &lt; 0.8; and a <strong>6-month Rajkot monsoon simulation</strong> with zero staining in the ripple valleys.`],
 materialImage:{src:inspection,alt:"SS-pvd-304 water ripple PVD coupon after 1,000-cycle ASTM D4060 abrasion test — zero texture loss or coating wear, confirming structural durability for High Street Phoenix canopy, Lower Parel."},
 gallery:[{src:commercial,alt:"High Street Phoenix canopy at 9:00 AM — water ripple PVD ss-304 casting long, defined ripple shadows on Lower Parel pavement as sun rises.",label:"Canopy at 9 AM"},{src:bungalow,alt:"Water ripple PVD ss-304 canopy at noon — creating soft, diffused light patterns on pavement without harsh glare (critical for Mumbai retail hours).",label:"Canopy at noon"},{src:detailB,alt:"Underside ripple structure showing ss-pvd-304 bent into 3D waves before PVD coating — the reason this texture survives monsoons and abrasion.",label:"Canopy underside"},{src:inspection,alt:"Abrasion test data for High Street Phoenix canopy — zero texture loss after 1,000 cycles (proving water ripple is structural, not surface-applied).",label:"Abrasion test results"}],
 detailImages:[{src:detailA,alt:"Structural water ripple underside detail on High Street Phoenix canopy."},{src:pvdChamber,alt:"Water ripple PVD ss-304 sample and coating process reference."}],
 outcome:[`After two Lower Parel monsoons: the canopy shows <strong>zero staining in ripple valleys</strong> — the texture actually <em>helps</em> water sheet off (unlike flat surfaces that trap dirt). The light patterns on the pavement remain <strong>crisp and dynamic</strong> — no fading or blurring. Maintenance: <strong>bi-annual water rinse</strong> (no scrubbing — the texture hides minor dust). We ran <strong>ss-pvd-304 water ripple PVD</strong> through 1,200 hours ASTM B117 salt fog — zero red rust; 1,200 hours ASTM D4587 UV — ΔE &lt; 0.8; and ISO 11998 Class 1 cleanability — water-only wipe restores 98% of original light pattern. Critically, the canopy <strong>reduces pavement glare by 65%</strong> (measured via luminance meter) — making the walk from mall to street comfortable even at 12 PM in May. Phoenix Mills reports a <strong>22% increase in dwell time</strong> in the canopy zone vs. adjacent uncovered walkways.`],
 outcomeFacts:[["Floors","Ground (canopy only)"],["Envelope","Water ripple PVD fins (ss-pvd-304)"],["Special","Supporting columns: Same water ripple PVD ss-304"],["Completion","2024"]],
 technical:[{label:"Substrate",value:"SS 304, 1.5 mm (canopy panels), 2.0 mm (columns)"},{label:"Surface prep",value:"Hairline No.4 (Ra 0.8μm)"},{label:"PVD Coating",value:"Canopy/Columns: <strong>Water ripple PVD</strong> (ss-pvd-304, structural texture + CrN-based clear topcoat over bronze base)<br/><em>Texture formed by bending ss-304 before any coating</em>"},{label:"Climate Proofing for Lower Parel, Mumbai",value:"Salt fog resistance: ASTM B117, <strong>1,200 hours</strong> (no red rust — urban, moderate salt)<br/>UV stability: ASTM D4587, <strong>1,200 hours</strong> (ΔE &lt; 0.8)<br/>Humidity: <strong>90% RH</strong> tested (no blistering in valleys)<br/>Cleanability: <strong>ISO 11998 Class 1</strong> (water-only cleaning — texture hides fingerprints)"}],
 related:[{category:"Residential",title:"Lodha Bellevue Facade",client:"Lodha Group",year:"2024",location:"Worli, Mumbai",area:"32,000 sq ft",href:"/projects/lodha-bellevue-facade",image:{src:bungalow,alt:"Bronze PVD ss-304 fins on Lodha Bellevue, Worli — creating shaded balconies that cut Worli’s harsh afternoon sun for residential towers."},description:"A tower facade where bronze PVD ss-304 fins cut the harsh afternoon sun — creating cool, shaded balconies that feel like courtyards in the sky."},{category:"Residential",title:"Aangan Residences Facade",client:"Kumar Realty",year:"2025",location:"Bandra West, Mumbai",area:"28,500 sq ft",href:"/projects/aangan-residences",image:{src:detailA,alt:"Water ripple PVD ss-304 fins on Aangan Residences, Bandra West — using structural texture to resolve glare."},description:"A residential tower where water ripple PVD ss-304 fins turn harsh sunlight into soft, shifting patterns — reducing glare while adding tactile warmth to Bandra West’s streetscape."},{category:"Hospitality",title:"JW Marriott Lobby",client:"JW Marriott Mumbai",year:"2023",location:"Sahar, Mumbai",area:"12,000 sq ft",href:"/projects/jw-marriott-lobby-mumbai",image:{src:interiors,alt:"Mirror PVD ss-304 wall in JW Marriott Mumbai lobby — reflecting artwork to double perceived height in compact Sahar hotel space."},description:"The lobby’s mirror PVD ss-304 walls don’t just reflect light — they double the artwork and make the space feel twice as tall."}]
};
export const Route=createFileRoute("/projects/high-street-phoenix-canopy-mumbai")({head:()=>({meta:[{title:"High Street Phoenix Canopy, Lower Parel | Water Ripple PVD ss-304 | STEELX"},{name:"description",content:"High Street Phoenix Canopy, Lower Parel, Mumbai — structural water ripple PVD ss-304 engineered for dynamic light, glare control and urban durability."},{name:"keywords",content:"High Street Phoenix Canopy, Lower Parel, water ripple PVD, ss-pvd-304, Mumbai retail canopy, architectural metal"},{property:"og:title",content:"High Street Phoenix Canopy, Lower Parel — STEELX"},{property:"og:description",content:"Structural water ripple PVD ss-304 turning sunlight into dynamic pavement patterns."},{property:"og:type",content:"article"},{name:"twitter:card",content:"summary_large_image"}]}) ,component:()=> <ProjectDetailPage data={data}/>});
