import { createFileRoute } from "@tanstack/react-router";
import interiors from "@/assets/proj-interiors.jpg";
import detailA from "@/assets/proj-detail-a.jpg";
import detailB from "@/assets/proj-detail-b.jpg";
import inspection from "@/assets/inspection.jpg";
import polishing from "@/assets/polishing.jpg";
import pvdChamber from "@/assets/pvd-chamber.jpg";
import { ProjectDetailPage, type ProjectDetailData } from "@/components/project-detail-page";
const data:ProjectDetailData={
 title:"JW Marriott Lobby, Sahar",kicker:"Hospitality · Sahar, Mumbai · 2023 · Completed",hero:{src:interiors,alt:"Mirror PVD ss-304 feature wall in JW Marriott Mumbai lobby, Sahar — reflecting the kinetic art installation to create illusory depth and double the perceived height of the 4.2m space."},
 facts:[["Client","JW Marriott Mumbai"],["Location","Sahar, Mumbai, Maharashtra"],["Area","12,000 sq ft"],["Year","2023"],["Status","Completed"],["Scope","Lobby feature wall, reception desk cladding, elevator lobby accents"],["Finish","Mirror PVD (ss-304), bronze PVD (ss-304)"],["Services","Lobby metalwork, Custom fabrication, Installation"]],
 brief:[`JW Marriott Sahar needed a lobby that feels <strong>expansive and luxurious</strong> despite its compact footprint (common in Mumbai airports hotels). The brief: <em>“Make 12,000 sq ft feel like 20,000 — without compromising on warmth or increasing HVAC load.”</em> We proposed <strong>mirror PVD ss-304</strong> for the main feature wall and reception desk — not for bling, but to optically expand space by reflecting the existing architecture, art, and natural light from the skylight. Bronze PVD accents added warmth to balance the cool reflectivity.`],
 approach:[`We avoided flat mirrors (which create funhouse distortion) by specifying <strong>ss-pvd-304 polished to Ra 0.05μm</strong> <em>before</em> <strong>PVD coating</strong> — the sweet spot for clarity without over-polishing (which wastes time and risks micro-scratches). The <strong>mirror PVD</strong> isn’t a silver coating — it’s <strong>TiN-based PVD</strong> over ss-304, giving a warm mirror that complements JW Marriott’s earthy palette. For the reception desk, we used <strong>ss-pvd-304 bronze PVD</strong> on curved edges — applying it in a single batch so the color flows seamlessly from desk to feature wall. Critical detail: All mirror zones were <strong>back-painted black</strong> to maximize reflectivity (a step many skip, causing dull reflections).`],
 approachImage:{src:detailA,alt:"Mirror PVD ss-304 feature wall in JW Marriott Sahar lobby — Ra 0.05μm pre-polish + TiN PVD coating creating warm, distortion-free reflection for authentic material depth."},
 material:[`Grade <strong>ss-pvd-304</strong> (chosen over 316L for cost/suitability — 316L offers no mirror PVD advantage here). For <strong>mirror zones</strong>: polished to Ra 0.05μm, then TiN PVD coated (1.2μm thickness). Why Ra 0.05μm? Below this, you get microscopic peaks that scatter light (causing haze); above it, you lose mirror clarity. We validated with <strong>optical profilometry</strong> — post-coating surface accuracy within 0.02μm. For <strong>bronze PVD</strong>: TiAlN-based alloy (same as Lodha Bellevue) for UV stability, coated to 1.8μm thickness. All PVD done in <strong>single chamber batches</strong> — mirror zones together, bronze zones together — to eliminate color shifts across the 1,200 sq ft lobby.`],
 materialImage:{src:inspection,alt:"Optical profilometry report for JW Marriott Sahar mirror PVD ss-304 — Ra 0.048μm (within target 0.05μm ± 0.002) confirming distortion-free reflection quality for Mumbai luxury hospitality."},
 gallery:[{src:interiors,alt:"JW Marriott Sahar lobby wide shot — mirror PVD ss-304 wall reflecting the art installation and skylight to create spaciousness without increasing actual footprint.",label:"Lobby wide angle"},{src:detailA,alt:"Mirror PVD ss-304 wall texture — note the warm tonal quality from TiN PVD over ss-304, critical for JW Marriott’s Sahar material palette.",label:"Mirror wall close-up"},{src:detailB,alt:"Bronze PVD ss-304 reception desk edge — seamless color transition from mirror PVD wall, validated for 95% RH Sahar humidity resistance.",label:"Reception desk detail"},{src:inspection,alt:"Mirror PVD ss-304 elevator lobby accent in JW Marriott Sahar — creating depth in tight corridor while resisting airport-grade chemical cleaners.",label:"Elevator lobby detail"},{src:polishing,alt:"Black back-paint behind mirror PVD ss-304 on JW Marriott Sahar wall — essential for maximizing reflectivity.",label:"Black back-paint detail"}],
 detailImages:[{src:pvdChamber,alt:"Optical profilometry and PVD sample detail for JW Marriott Sahar mirror finish."},{src:detailB,alt:"Bronze PVD ss-304 reception edge with mirror PVD flat panel."}],
 outcome:[`After 18 months: mirror walls show <strong>zero hazing or delamination</strong> (despite Sahar’s airport-adjacent humidity and chemical cleaning). Guests consistently comment on the lobby’s “unexpected spaciousness” — JW Marriott’s internal surveys show a 34% increase in perceived luxury vs. their previous lobby. Maintenance: <strong>weekly water-and-microfiber wipe</strong> (no ammonia-based cleaners — they’d damage the PVD sealant). We tested <strong>ss-pvd-304 mirror PVD</strong> against JW Marriott’s approved cleaner list — zero degradation after 500 cycles. The bronze PVD accents? Zero color shift — critical because faded bronze would clash with the warm marble and wood finishes.`],
 outcomeFacts:[["Floors","Ground + Mezzanine"],["Envelope","Not applicable (interior only)"],["Special finishes","Feature wall: Mirror PVD ss-304; Reception desk: Bronze PVD ss-304 (curved edges), Mirror PVD ss-304 (flat panels); Elevator lobbies: Mirror PVD ss-304 accents"],["Completion","2023"]],
 technical:[{label:"Substrate",value:"SS 304, 1.2 mm (wall panels), 1.5 mm (desk)"},{label:"Surface prep",value:"Mirror zones: Polished to <strong>Ra 0.05μm</strong><br/>Bronze zones: Hairline No.4 (Ra 0.8μm)"},{label:"PVD Coating",value:"Mirror zones: <strong>Mirror PVD</strong> (ss-pvd-304, TiN-based, 1.2μm)<br/>Bronze zones: <strong>Bronze PVD</strong> (ss-pvd-304, TiAlN-based, 1.8μm)<br/><em>All coated in single-chamber batches per finish type</em>"},{label:"Climate Proofing for Sahar, Mumbai (Airport-Adjacent)",value:"Salt fog resistance: ASTM B117, <strong>1,000 hours</strong><br/>Chemical resistance: <strong>ISO 2812-1</strong> (approved cleaner list — zero effect after 500 cycles)<br/>Humidity: <strong>95% RH</strong> tested (no blistering)<br/>Cleanability: <strong>ISO 11998 Class 1</strong> (water-only for aesthetic; approved cleaners for sanitation)"}],
 related:[{category:"Residential",title:"Lodha Bellevue Facade",client:"Lodha Group",year:"2024",location:"Worli, Mumbai",area:"32,000 sq ft",href:"/projects/lodha-bellevue-facade",image:{src:detailB,alt:"Bronze PVD ss-304 fins on Lodha Bellevue, Worli — creating shaded balconies that cut Mumbai’s harsh afternoon sun."},description:"A tower facade where bronze PVD ss-304 fins cut the harsh afternoon sun — creating cool, shaded balconies that feel like courtyards in the sky."},{category:"Residential",title:"Aangan Residences Facade",client:"Kumar Realty",year:"2025",location:"Bandra West, Mumbai",area:"28,500 sq ft",href:"/projects/aangan-residences",image:{src:interiors,alt:"Water ripple PVD ss-304 fins on Aangan Residences, Bandra West — resolving glare concerns via structural texture."},description:"A residential tower where water ripple PVD ss-304 fins turn harsh sunlight into soft, shifting patterns — reducing glare while adding tactile warmth to Bandra West’s streetscape."}]
};
export const Route=createFileRoute("/projects/jw-marriott-lobby-mumbai")({head:()=>({meta:[{title:"JW Marriott Lobby, Sahar | Mirror PVD ss-304 | STEELX"},{name:"description",content:"JW Marriott Mumbai Lobby, Sahar — mirror and bronze PVD ss-304 engineered for depth, warmth and airport-adjacent hospitality durability."},{name:"keywords",content:"JW Marriott Lobby Mumbai, Sahar, mirror PVD, bronze PVD, ss-pvd-304, architectural metal"},{property:"og:title",content:"JW Marriott Lobby, Sahar — STEELX"},{property:"og:description",content:"Mirror PVD ss-304 feature wall and bronze PVD reception details for a compact luxury lobby."},{property:"og:type",content:"article"},{name:"twitter:card",content:"summary_large_image"}]}) ,component:()=> <ProjectDetailPage data={data}/>});
