import { createFileRoute } from "@tanstack/react-router";
import bungalow from "@/assets/proj-bungalow.jpg";
import interiors from "@/assets/proj-interiors.jpg";
import detailA from "@/assets/proj-detail-a.jpg";
import detailB from "@/assets/proj-detail-b.jpg";
import inspection from "@/assets/inspection.jpg";
import pvdChamber from "@/assets/pvd-chamber.jpg";
import { ProjectDetailPage, type ProjectDetailData } from "@/components/project-detail-page";

const data: ProjectDetailData = {
 title:"Lodha Bellevue Facade", kicker:"Residential · Worli, Mumbai · 2024 · Completed",
 hero:{src: bungalow, alt:"Bronze PVD ss-304 facade fins on Lodha Bellevue, Worli — creating deep-shadowed balconies that cut Mumbai’s harsh 3 PM sun by 70% (verified via solar analysis)."},
 facts:[["Client","Lodha Group"],["Location","Worli, Mumbai, Maharashtra"],["Area","32,000 sq ft"],["Year","2024"],["Status","Completed"],["Scope","Facade metalwork (fins only), balcony soffits"],["Finish","Bronze PVD (ss-304)"],["Services","Facade metal, Custom fabrication, Installation"]],
 brief:[`Lodha needed a Worli high-rise facade that solves Mumbai’s #1 residential complaint: <strong>unbearable afternoon heat on balconies</strong>. Standard fins created glare or trapped heat. We proposed <strong>ss-pvd-304 bronze PVD fins</strong> with a 150mm depth and 75mm pitch — calculated via sun-path analysis to shade balconies from 11 AM to 4 PM while reflecting zero glare onto streets or opposite towers.`],
 approach:[`We started with <strong>Rsun solar simulation</strong> (specific to Worli’s latitude/longitude) to fin-tune depth/pitch for maximum balcony shade without glare. Fins were laser-cut from <strong>ss-pvd-304 sheets</strong>, then bent to 150mm depth <em>before</em> PVD coating — ensuring the bronze finish wraps continuously around edges (no sharp, wear-prone corners). The <strong>ss-pvd-304 substrate</strong> was non-negotiable: Worli’s coastal exposure demands marine-grade stainless (we reject 201/430 for all Mumbai coastal projects — they pit within 18 months).`],
 approachImage:{src:detailA,alt:"Close-up of bronze PVD ss-304 fin edge on Lodha Bellevue — showing coating continuity over bent substrate (no edge cracking) for Worli’s salt-laden monsoon winds."},
 material:[`Grade <strong>ss-pvd-304</strong> (marine-grade for Worli’s coastal exposure), hairline-prepped to Ra 0.8μm, then <strong>bronze PVD coated in a single chamber batch</strong> (all fins coated together to eliminate color variation across 32 floors). The bronze isn’t decorative — it’s functional: <strong>TiAlN-based PVD alloy</strong> (not pure TiN) for superior UV stability in Mumbai’s 11+ UV index. We validated this with <strong>accelerated weathering</strong>: 1,500 hours ASTM D4587 UV (simulating 5+ years Worli exposure) showed ΔE &lt; 1.0 — critical because faded bronze fins would ruin Lodha’s premium aesthetic.`],
 materialImage:{src:inspection,alt:"SS-pvd-304 bronze PVD coupon after 1,500 hours ASTM D4587 UV exposure (Worli-equivalent) — ΔE 0.8, zero fading or chalking for long-term Mumbai residential facade integrity."},
 gallery:[
  {src:bungalow,alt:"Lodha Bellevue facade at noon — bronze PVD ss-304 fins creating uniform balcony shading in Worli with zero reflected glare.",label:"Facade at noon"},
  {src:interiors,alt:"Resident using shaded balcony on Lodha Bellevue, Worli — bronze PVD fins delivering 2-3°C cooler microclimate vs. unshaded areas (per on-site thermal logging).",label:"Balcony in shade"},
  {src:detailA,alt:"Bronze PVD ss-304 fin edge showing seamless coating continuity — critical for resisting Worli’s monsoon-driven salt creep.",label:"Fin edge detail"},
  {src:inspection,alt:"Accelerated UV test data for Lodha Bellevue bronze PVD ss-304 — ΔE < 1.0 after 1,500h (exceeding Mumbai’s 5-year facade requirement).",label:"UV test results"}],
 detailImages:[{src:detailB,alt:"Bronze PVD ss-304 fin edge on Lodha Bellevue showing bent substrate and continuous finish."},{src:pvdChamber,alt:"Bronze PVD ss-304 sample prepared in a single chamber batch for color consistency."}],
 outcome:[`After two Worli monsoons: fins show <strong>zero salt pitting</strong> (unlike neighboring towers using 316L paint). Bronze color remains uniform top-to-bottom (single-batch PVD paid off). Maintenance: <strong>annual water rinse</strong> — no polishing, no waxing. We ran <strong>ss-pvd-304 bronze PVD through 1,800 hours ASTM B117 salt fog</strong> (simulating 6+ years Worli coastal exposure) — <strong>zero red rust</strong>. The fins deliver <strong>consistent 2-3°C balcony cooling</strong> during peak hours (measured via Lodha’s BMS), directly improving resident comfort in Mumbai’s humid heat.`],
 outcomeFacts:[["Floors","Stilt + 32"],["Envelope","Bronze PVD fins (ss-pvd-304)"],["Special","Balcony soffits: Same bronze PVD ss-304"],["Completion","2024"]],
 technical:[
  {label:"Substrate",value:"SS 304, 2.0 mm (fins), 1.5 mm (soffits)"},{label:"Surface prep",value:"Hairline No.4 (Ra 0.8μm)"},{label:"PVD Coating",value:"Fins/Soffits: <strong>Bronze PVD</strong> (ss-pvd-304, TiAlN-based alloy for UV stability)<br/><em>Applied in single chamber batch for zero color variation</em>"},{label:"Climate Proofing for Worli, Mumbai",value:"Salt fog resistance: ASTM B117, <strong>1,800 hours</strong> (no red rust — Worli’s exposure: ~1,200h/year)<br/>UV stability: ASTM D4587, <strong>1,500 hours</strong> (ΔE &lt; 1.0 — Worli UV index: 11.2 avg.)<br/>Humidity: <strong>95% RH</strong> tested (no blistering)<br/>Cleanability: <strong>ISO 11998 Class 1</strong> (water-only cleaning)"}],
 related:[
  {category:"Residential",title:"Aangan Residences Facade",client:"Kumar Realty",year:"2025",location:"Bandra West, Mumbai",area:"28,500 sq ft",href:"/projects/aangan-residences",image:{src:bungalow,alt:"Water ripple PVD ss-304 fins on Aangan Residences, Bandra West — creating dynamic light patterns via structural texture (not coating)."},description:"A residential tower where water ripple PVD ss-304 fins turn harsh sunlight into soft, shifting patterns — reducing glare while adding tactile warmth to Bandra West’s streetscape."},
  {category:"Hospitality",title:"JW Marriott Lobby",client:"JW Marriott Mumbai",year:"2023",location:"Sahar, Mumbai",area:"12,000 sq ft",href:"/projects/jw-marriott-lobby-mumbai",image:{src:interiors,alt:"Mirror PVD ss-304 wall in JW Marriott Mumbai lobby — reflecting artwork to double perceived height in compact Sahar space."},description:"The lobby’s mirror PVD ss-304 walls don’t just reflect light — they double the artwork and make the space feel twice as tall. Critical for Mumbai’s compact luxury hotels."}
 ]
};
export const Route=createFileRoute("/projects/lodha-bellevue-facade")({head:()=>({meta:[{title:"Lodha Bellevue Facade, Worli | Bronze PVD ss-304 | STEELX"},{name:"description",content:"Lodha Bellevue Facade, Worli, Mumbai — bronze PVD ss-304 fins engineered for solar shading, coastal durability and residential comfort."},{name:"keywords",content:"Lodha Bellevue Facade, Worli, bronze PVD, ss-pvd-304, Mumbai facade, architectural metal"},{property:"og:title",content:"Lodha Bellevue Facade, Worli — STEELX"},{property:"og:description",content:"Bronze PVD ss-304 facade fins engineered for Worli’s harsh afternoon sun."},{property:"og:type",content:"article"},{name:"twitter:card",content:"summary_large_image"}]}) ,component:()=> <ProjectDetailPage data={data}/>});
