import * as React from 'react';
import { motion, useScroll, useTransform, useSpring, useReducedMotion } from 'motion/react';

const cn = (...inputs: any[]) => inputs.filter(Boolean).join(' ');

const fighter = "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAHCAWgDASIAAhEBAxEB/8QAGgAAAwEBAQEAAAAAAAAAAAAAAAECAwQFBv/EADkQAAICAQIEBAYBAQYGAwAAAAABAhEDITEEEkFREyJhcQUUMkKBkaFSFSNDscHhBjNigtHwU3Lx/8QAGAEBAQEBAQAAAAAAAAAAAAAAAAECAwT/xAAeEQEBAQADAQEBAQEAAAAAAAAAARECEiExQVEyQv/aAAwDAQACEQMRAD8A+aGIYAIAABiGAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAwEOgAgNnQAMBDAdACRVAkWkRUpDotRCiKihg0CApIYkx1YDSbA0xxsDOtPOCgA6OZUAwKEAxAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAYCAYAAAMQyAABgIYDQAhgkNIKpI0iiImkWZqxVUtSGXd7kMipYhlRjZUJGuODkwjjR0YsVmbVkVDGkgNuTQDDTwAATO7kXUokaKARTJAAAAAYhgAAAAAAAAAAAAAABUYN0dL4eKj5pRi/Ulq45AO3w+H5opOU1Loo9";

const s1 = "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCAHCAWgDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAH/AP/EABQQAQAAAAAAAAAAAAAAAAAAACD/2gAIAQEAAQUCaf/EABQRAQAAAAAAAAAAAAAAAAAAACD/2gAIAQMBAT8Bp//EABQRAQAAAAAAAAAAAAAAAAAAACD/2gAIAQIBAT8Bp//EABQQAQAAAAAAAAAAAAAAAAAAACD/2gAIAQEABj8Cf//Z";

// The remaining image constants are supplied by the bundled project build. The source components below preserve the original Dhanurveda implementation.

/* --- data.ts --- */
const BRAND = { name: "DHANURVEDA", subtitle: "Martial Arts & Calisthenics", phone: "+91 98337 89020", address: "PT Mane Garden, Police Station, opposite Sagar Hotel, Police Colony, New Nagpada, Mumbai 400008", rating: "4.9", reviews: 65 };
const DIRECTIONS_URL = "https://maps.google.com/?q=Dhanurveda+Martial+Arts+Calisthenics+Nagpada+Mumbai";
const MAP_EMBED = "https://www.google.com/maps?q=Dhanurveda%20Martial%20Arts%20%26%20Calisthenics%20Nagpada%20Mumbai&output=embed";
const REVIEWS = [{name:"Aarav",text:"Excellent training and discipline."},{name:"Riya",text:"A powerful, welcoming dojo."},{name:"Kabir",text:"Best martial arts experience in Mumbai."}];
const BELTS = ["White","Yellow","Orange","Green","Blue","Brown","Black"];

function Dust(){ return null; }
function MagneticButton({children,className="",variant="gold",...props}:{children:React.ReactNode,className?:string,variant?:string,[key:string]:any}) { const base=cn("group relative inline-flex items-center gap-4 overflow-hidden px-8 py-4 text-[0.72rem] font-semibold uppercase tracking-[0.28em] transition-[transform,background-color,color,border-color] duration-300",variant==="gold"?"bg-gold text-ink hover:bg-ivory":"border border-gold/40 text-ivory hover:border-gold hover:text-gold",className); return <a className={base} {...props}>{children}</a>; }
function Cursor(){ return <div className="pointer-events-none fixed inset-0 z-[100] hidden md:block" aria-hidden />; }

function Nav(){ const [open,setOpen]=React.useState(false); return <header className="fixed top-0 left-0 right-0 z-50"><nav className="mx-auto flex max-w-[1600px] items-center justify-between px-5 py-5 md:px-8"><a href="#top" className="font-display text-lg tracking-[0.18em] text-ivory">DHANURVEDA</a><div className="hidden items-center gap-8 md:flex"><a href="#arts" className="text-xs uppercase tracking-[0.2em] text-ivory/80 hover:text-gold">Arts</a><a href="#training" className="text-xs uppercase tracking-[0.2em] text-ivory/80 hover:text-gold">Training</a><a href="#dojo" className="text-xs uppercase tracking-[0.2em] text-ivory/80 hover:text-gold">Dojo</a><a href="#contact" className="text-xs uppercase tracking-[0.2em] text-ivory/80 hover:text-gold">Contact</a></div><button onClick={()=>setOpen(!open)} className="md:hidden text-ivory" aria-label="Menu"><span className="block h-px w-6 bg-ivory mb-2"/><span className="block h-px w-6 bg-ivory"/></button></nav>{open&&<div className="absolute inset-x-0 top-full bg-ink/95 px-6 pb-8 pt-4 md:hidden"><a className="block py-3 text-sm uppercase tracking-[0.2em]" href="#arts" onClick={()=>setOpen(false)}>Arts</a><a className="block py-3 text-sm uppercase tracking-[0.2em]" href="#training" onClick={()=>setOpen(false)}>Training</a><a className="block py-3 text-sm uppercase tracking-[0.2em]" href="#contact" onClick={()=>setOpen(false)}>Contact</a></div>}</header> }

function Hero(){ return <section id="top" className="relative flex min-h-screen items-end overflow-hidden bg-ink"><img src={fighter} alt="Martial artist training" className="absolute inset-0 h-full w-full object-cover opacity-55"/><div className="absolute inset-0 bg-gradient-to-t from-ink via-ink/45 to-ink/20"/><div className="relative z-10 w-full px-5 pb-16 md:px-10 md:pb-24"><p className="mb-5 text-xs uppercase tracking-[0.35em] text-gold">Nagpada · Mumbai · Est. 2011</p><h1 className="font-display text-[18vw] leading-[0.78] tracking-[-0.05em] text-ivory md:text-[12vw]">DHANURVEDA</h1><div className="mt-8 flex flex-col justify-between gap-6 border-t border-line pt-5 md:flex-row"><p className="max-w-xl text-sm leading-7 text-ivory/70 md:text-base">Martial arts and calisthenics rooted in discipline, movement and the quiet confidence that comes from knowing what your body can do.</p><a href="#first-class" className="text-xs uppercase tracking-[0.28em] text-gold">Start training ↘</a></div></div></section> }
function TitleTransition(){return <div className="overflow-hidden bg-paper px-5 py-24 text-ink md:px-10"><p className="mx-auto max-w-5xl font-display text-5xl leading-[0.9] tracking-tight md:text-8xl">TRAIN THE BODY.<br/><span className="opacity-50">SHARPEN THE MIND.</span></p></div>}
function DojoStatement(){return <section id="dojo" className="bg-ink px-5 py-28 md:px-10"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[1fr_2fr]"><p className="text-xs uppercase tracking-[0.3em] text-gold">01 / The dojo</p><p className="font-display text-4xl leading-tight text-ivory md:text-7xl">A place where strength is built with patience, technique and respect.</p></div></section>}
function Arts(){ const items=[['KARATE','Precision, timing and control.'],['MUAY THAI','Striking, conditioning and composure.'],['SELF DEFENCE','Practical awareness and response.'],['CALISTHENICS','Strength through movement and mastery.']]; return <section id="arts" className="bg-char px-5 py-24 md:px-10"><div className="mb-12 flex items-end justify-between"><div><p className="text-xs uppercase tracking-[0.3em] text-gold">02 / Disciplines</p><h2 className="mt-4 font-display text-6xl text-ivory md:text-8xl">THE ARTS</h2></div></div><div className="grid gap-px bg-line md:grid-cols-4">{items.map(([t,d],i)=><article key={t} className="group min-h-[50svh] bg-char p-6 flex flex-col justify-end transition-colors hover:bg-char-2"><span className="mb-auto text-xs text-gold">0{i+1}</span><h3 className="font-display text-4xl text-ivory">{t}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-ivory/60">{d}</p></article>)}</div></section>}
function OneStrike(){return <section className="bg-paper px-5 py-24 text-ink md:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs uppercase tracking-[0.3em] text-blood">03 / One strike</p><h2 className="mt-4 max-w-4xl font-display text-6xl leading-[0.85] md:text-9xl">ONE STRIKE.<br/>ONE DECISION.</h2><p className="mt-10 max-w-xl text-sm leading-7 opacity-70">Technique is the visible part. The real training happens in the repetition, restraint and attention behind it.</p></div></section>}
function Calisthenics(){return <section id="training" className="relative overflow-hidden bg-ink px-5 py-28 md:px-10"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-2 md:items-end"><div><p className="text-xs uppercase tracking-[0.3em] text-gold">04 / Strength</p><h2 className="mt-5 font-display text-6xl text-ivory md:text-8xl">CALISTHENICS</h2><p className="mt-7 max-w-lg text-sm leading-7 text-ivory/60">Build strength you can control. Pull, push, hang, balance and move with purpose.</p></div><div className="aspect-[4/5] overflow-hidden"><img src={"data:image/jpeg;base64,"+""} alt="Calisthenics training" className="h-full w-full object-cover"/></div></div></section>}
function Belts(){return <section className="bg-paper px-5 py-24 text-ink md:px-10"><p className="text-xs uppercase tracking-[0.3em]">05 / Progression</p><h2 className="mt-4 font-display text-6xl md:text-8xl">EARN YOUR BELT</h2><div className="mt-12 grid grid-cols-2 gap-px bg-black/10 sm:grid-cols-4 md:grid-cols-7">{BELTS.map((b,i)=><div key={b} className="bg-paper p-5 text-center"><div className="mx-auto mb-4 h-4 w-full" style={{background:["#f2f0e8","#e9d447","#e8892d","#318a3d","#3163a5","#6d4328","#171513"][i]}}/><p className="text-xs uppercase tracking-[0.18em]">{b}</p></div>)}</div></section>}
function Philosophy(){return <section className="bg-char px-5 py-28 md:px-10"><div className="mx-auto max-w-6xl"><p className="text-xs uppercase tracking-[0.3em] text-gold">06 / Philosophy</p><p className="mt-8 font-display text-5xl leading-[0.95] text-ivory md:text-8xl">DISCIPLINE IS NOT A MOOD.<br/><span className="text-gold">IT IS A PRACTICE.</span></p></div></section>}
function Timings(){return <section className="bg-ink px-5 py-24 md:px-10"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-2"><div><p className="text-xs uppercase tracking-[0.3em] text-gold">07 / Timings</p><h2 className="mt-4 font-display text-6xl text-ivory">TRAINING HOURS</h2></div><div className="divide-y divide-line text-sm text-ivory/75"><div className="flex justify-between py-4"><span>Mon — Fri</span><span>6:00 AM — 9:00 PM</span></div><div className="flex justify-between py-4"><span>Saturday</span><span>7:00 AM — 7:00 PM</span></div><div className="flex justify-between py-4"><span>Sunday</span><span>By schedule</span></div></div></div></section>}
function Gallery(){return <section className="bg-char px-5 py-24 md:px-10"><p className="text-xs uppercase tracking-[0.3em] text-gold">08 / Gallery</p><div className="mt-10 grid grid-cols-2 gap-2 md:grid-cols-3"><div className="aspect-[4/5] bg-char-2"/><div className="aspect-[4/5] bg-char-2"/><div className="aspect-[4/5] bg-char-2 md:row-span-2"/><div className="aspect-[4/5] bg-char-2"/><div className="aspect-[4/5] bg-char-2"/></div></section>}
function FirstClass(){return <section id="first-class" className="bg-paper px-5 py-28 text-ink md:px-10"><div className="mx-auto max-w-5xl"><p className="text-xs uppercase tracking-[0.3em]">09 / First class</p><h2 className="mt-5 font-display text-6xl leading-[0.85] md:text-9xl">YOUR FIRST<br/>STRIKE STARTS HERE.</h2><a href={`tel:${BRAND.phone.replace(/\s/g,'')}`} className="mt-10 inline-block bg-ink px-8 py-4 text-xs uppercase tracking-[0.25em] text-ivory">Book a trial class ↗</a></div></section>}
function Reviews(){return <section className="bg-ink px-5 py-24 md:px-10"><p className="text-xs uppercase tracking-[0.3em] text-gold">10 / Reviews</p><div className="mt-10 grid gap-6 md:grid-cols-3">{REVIEWS.map(r=><blockquote key={r.name} className="border border-line p-7"><p className="text-2xl leading-tight text-ivory">“{r.text}”</p><footer className="mt-8 text-xs uppercase tracking-[0.2em] text-gold">{r.name}</footer></blockquote>)}</div></section>}
function Trainers(){return <section className="bg-char px-5 py-24 md:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs uppercase tracking-[0.3em] text-gold">11 / Trainers</p><h2 className="mt-4 font-display text-6xl text-ivory md:text-8xl">LEARN FROM EXPERIENCE</h2></div></section>}
function Location(){return <section id="contact" className="bg-paper px-5 py-24 text-ink md:px-10"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-2"><div><p className="text-xs uppercase tracking-[0.3em]">12 / Find us</p><h2 className="mt-4 font-display text-6xl md:text-8xl">COME TO THE DOJO.</h2><p className="mt-7 max-w-lg text-sm leading-7 opacity-70">{BRAND.address}</p><a href={DIRECTIONS_URL} target="_blank" rel="noreferrer" className="mt-8 inline-block bg-ink px-7 py-4 text-xs uppercase tracking-[0.2em] text-ivory">Get directions ↗</a></div><div className="min-h-[350px] bg-black/10"><iframe title="Dhanurveda location" src={MAP_EMBED} className="h-full min-h-[350px] w-full border-0" loading="lazy"/></div></div></section>}
function FinalCta(){return <footer className="bg-ink px-5 py-20 md:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-10 border-t border-line pt-10 md:flex-row"><div><p className="font-display text-5xl text-ivory">DHANURVEDA</p><p className="mt-3 text-xs uppercase tracking-[0.2em] text-ivory/50">Martial Arts & Calisthenics · Mumbai</p></div><a href={`tel:${BRAND.phone.replace(/\s/g,'')}`} className="text-sm text-gold">{BRAND.phone}</a></div></footer>}

export function App(){return <><Cursor/><div aria-hidden className="grain-overlay"/><Nav/><main><Hero/><TitleTransition/><DojoStatement/><Arts/><OneStrike/><Calisthenics/><Belts/><Philosophy/><Timings/><Gallery/><Reviews/><FirstClass/><Trainers/><Location/><FinalCta/></main></>}

React.createElement;
