import { KataEditorialPage } from "./KataEditorialPage";

const movements = [
["1","soete-uchi-uke","(bassai-uke) / added hand inside block","kosa-dachi","chudan", ""],
["2","uchi-uke","inside block","zenkutsu-dachi","chudan", ""],
["3","uchi-uke","inside block","zenkutsu-dachi","chudan", "gyaku-hanmi"],
["4","soto-uke","outside block","zenkutsu-dachi","chudan", "gyaku-hanmi"],
["5","uchi-uke","inside block","zenkutsu-dachi","chudan", ""],
["6","sukui-uke & soto-uke","scooping block & outside block","zenkutsu-dachi","gedan / chudan", "sukui natural speed"],
["7","uchi-uke","inside block","zenkutsu-dachi","chudan", "gyaku-hanmi"],
["8","ryoken-koshi-kamae","both fists hip posture","hachiji-dachi","--", "natural speed"],
["9","tate-shuto-uke","vertical knife-hand block","hachiji-dachi","chudan", "slow speed"],
["10","tsuki (choku-zuki)","punch (straight punch)","hachiji-dachi","chudan", ""],
["11","uchi-uke","inside block","hizakutsu","chudan", ""],
["12","tsuki (choku-zuki)","punch (straight punch)","hachiji-dachi","chudan", ""],
["13","uchi-uke","inside block","hizakutsu","chudan", ""],
["14","shuto-uke","knife-hand block","kokutsu-dachi","chudan", ""],
["15","shuto-uke","knife-hand block","kokutsu-dachi","chudan", ""],
["16","shuto-uke","knife-hand block","kokutsu-dachi","chudan", ""],
["17","shuto-uke","knife-hand block","kokutsu-dachi","chudan", ""],
["18","ryosho-tsukami-uke","(bassai-uke) / both palms grasping block","ashi-zenkutsu","chudan", "slow speed · gyaku-hanmi"],
["19*","sokuto-kekomi / ryosho-tsukamiyose","sword-foot thrust kick / both palms grasping-pulling","ashi-dachi","gedan", "--"],
["20","shuto-uke","knife-hand block","kokutsu-dachi","chudan", ""],
["21","shuto-uke","knife-hand block","kokutsu-dachi","chudan", ""],
["22","morote-age-uke","double-hand rising block","heisoku-dachi","jodan", "natural speed"],
["23","ryo-kentsui-hasami-uchi","both hammer-fists scissors strike","zenkutsu-dachi","chudan", ""],
["24","tsuki","punch","zenkutsu-dachi","chudan", "yori-ashi"],
["25","soto-nagashi-uke / shuto-uchikomi & gedan-uke / uchi-uke (manji-uke)","outside flowing block / sword-hand thrusting strike & down block / inside block (swirling block)","ashi-zenkutsu / ashi-zenkutsu / heisoku-dachi / heisoku-dachi","jodan / gedan / gedan / jodan", "manji-uke slow speed"],
["26","gedan-barai / fumikomi","down block / stomp kick","kiba-dachi","gedan", ""],
["27","kake-uke","hooking block","kiba-dachi","chudan", "slow speed · haishu variation"],
["28","mikazuki-geri & mae-empi-uchi","crescent kick & front elbow strike","ashi-dachi / kiba-dachi","chudan / --", ""],
["29","gedan-uke / zenwan-mune-kamae","down block / forearm chest posture","kiba-dachi","gedan / chudan", ""],
["30","gedan-uke / zenwan-mune-kamae","down block / forearm chest posture","kiba-dachi","gedan / chudan", ""],
["31","gedan-uke / zenwan-mune-kamae","down block / forearm chest posture","kiba-dachi","gedan / chudan", ""],
["32","ryoken-koshi-kamae","both fists hip posture","ashi-zenkutsu","--", ""],
["33","yama-zuki","mountain punch","ashi-zenkutsu","jodan / gedan", ""],
["34","ryoken-koshi-kamae","both fists hip posture","heisoku-dachi","--", "slow speed"],
["35","yama-zuki","mountain punch","ashi-zenkutsu","jodan / gedan", ""],
["36","ryoken-koshi-kamae","both fists hip posture","heisoku-dachi","--", "slow speed"],
["37","yama-zuki","mountain punch","ashi-zenkutsu","jodan / gedan", ""],
["38","sukui-uke","scooping block","hizakutsu","gedan", ""],
["39","sukui-uke","scooping block","hizakutsu","gedan", ""],
["40","shuto-uke","knife-hand block","kokutsu-dachi","chudan", ""],
["41","jotai-sonomama","upper body as is","kokutsu-dachi (gyaku-kokutsu)","chudan", "slow speed"],
["42*","shuto-uke","knife-hand block","kokutsu-dachi","chudan", ""],
] as [string,string,string,string,string,string][];

export function BassaiDaiPage() {
  return <KataEditorialPage title="Bassai Dai" number="09" series="Sentei Series" previous={["Tekki Sandan","tekki-sandan"]} next={["Kanku Dai","kanku-dai"]} intro={<><p><em>Bassai</em> (pronounced <em>Patsai</em> in Okinawan) is most often translated as "To Penetrate a Fortress," meaning that one must exhibit the power and spirit required to break through an enemy's castle. This is particularly evident in the kata's first movement, when the karateka launches forward with <em>soete-uchi-uke</em>. The word <em>Dai</em> means "big," describing the kata's larger movements, contrary to its counterpart <em>Bassai Sho</em>. <em>Bassai</em>, <em>Kanku</em>, and <em>Gojushiho</em> are the three Shotokan kata that each have two versions, a <em>Sho</em> version (small) and a <em>Dai</em> version (big). Most translators agree that <em>Bassai</em> can more accurately be translated as "To Extract From a Fortress." <em>Bassai Dai</em> is believed to have been created by Sokon Matsumura. Much of the <em>bunkai</em> focus on breaking the opponent's balance and defenses against grabbing attacks. Like many Shotokan kata, <em>Bassai Dai</em> is praticed in many styles of karate, having several variations. The JKA version has 42 movements.</p><p className="mt-5"><em>Bassai Dai</em> is usually the first <em>Sentei</em> kata to be learned and is the most popular choice as <em>tokui</em> kata by 1st <em>kyu</em> examinees for black belt. It is charaterized by many switching arm blocking combinations, making effective use of the <em>hanmi/gyaku-hanmi</em> positions. Performance of <em>gyaku-hanmi</em> in <em>Bassai Dai</em> is substantially more difficult than in H2 because in <em>Bassai</em>, the front stance should not be shortened to accommodate <em>gyaku-hanmi</em>. Many techniques are seen for the first time in this kata such as <em>tate-shuto-uke</em>, <em>sukui-uke</em>, and <em>hasami-uchi</em>. The <em>ryosho-tsukami-uke & gedan-sokuto-kekomi</em> combination is unique to <em>Bassai</em> kata (both versions), while the powerful <em>yama-zuki</em> can ony be found in <em>Bassai Dai</em> and <em>Wankan</em>. It is interesting to note that one of the most basic blocking techniques, <em>chudan-soto-uke</em>, is first used in this kata, and then never seen again.</p></>} movements={movements} />;
}
