import { KataEditorialPage } from "./KataEditorialPage";

const movements = [
["1","uchi-uke / gedan-uke","inside block / down block","zenkutsu-dachi","chudan / gedan",""],
["2","ryoken-kakiwake-uke","both fists wedge block","zenkutsu-dachi","chudan","slow speed"],
["3","mae-geri","front kick","ashi-dachi","chudan",""],
["4","oi-zuki","lunge punch","zenkutsu-dachi","chudan",""],
["5","gyaku-zuki","reverse punch","zenkutsu-dachi","chudan",""],
["6","tsuki","punch","zenkutsu-dachi","chudan",""],
["7","ryoken-kakiwake-uke","both fists wedge block","zenkutsu-dachi","chudan","slow speed"],
["8","mae-geri","front kick","ashi-dachi","chudan",""],
["9","oi-zuki","lunge punch","zenkutsu-dachi","chudan",""],
["10","gyaku-zuki","reverse punch","zenkutsu-dachi","chudan",""],
["11","tsuki","punch","zenkutsu-dachi","chudan",""],
["12","age-uke","rising block","zenkutsu-dachi","jodan",""],
["13","gyaku-zuki","reverse punch","zenkutsu-dachi","chudan",""],
["14","age-uke","rising block","zenkutsu-dachi","jodan",""],
["15","gyaku-zuki","reverse punch","zenkutsu-dachi","chudan",""],
["16","age-uke","rising block","zenkutsu-dachi","jodan",""],
["17*","oi-zuki","lunge punch","zenkutsu-dachi","chudan",""],
["18","uchi-uke / gedan-uke (manji-uke)","inside block / down block (swirling block)","kokutsu-dachi","jodan / gedan",""],
["19","kagi-zuki","hook punch","kiba-dachi","chudan","yori-ashi"],
["20","uchi-uke / gedan-uke (manji-uke)","inside block / down block (swirling block)","kokutsu-dachi","jodan / gedan",""],
["21","kagi-zuki","hook punch","kiba-dachi","chudan","yori-ashi"],
["22","gedan-barai","down block","zenkutsu-dachi","gedan",""],
["23","teisho-yoko-uke","sideways palm-heel block","kiba-dachi","chudan",""],
["24","teisho-yoko-uke","sideways palm-heel block","kiba-dachi","chudan",""],
["25","teisho-yoko-uke","sideways palm-heel block","kiba-dachi","chudan",""],
["26","uchi-uke / gedan-uke (manji-uke)","inside block / down block (swirling block)","kokutsu-dachi","jodan / gedan",""],
["27","morote-uke","double-hand block","heisoku-dachi","jodan",""],
["28","uchi-uke / gedan-uke (manji-uke)","inside block / down block (swirling block)","kokutsu-dachi","jodan / gedan",""],
["29","morote-uke","double-hand block","heisoku-dachi","jodan",""],
["30","ryoken-kakiwake-uke","both fists wedge block","heisoku-dachi","gedan","slow speed"],
["31","ryoken-kosa-uke (juji-uke)","both fists cross block (X-block)","kosa-dachi","gedan",""],
["32","ryoken-kakiwake-uke","both fists wedge block","zenkutsu-dachi","gedan",""],
["33","ryoken-kakiwake-uke","both fists wedge block","zenkutsu-dachi","chudan",""],
["34","ryoken-kosa-uke (juji-uke)","both fists cross block (X-block)","zenkutsu-dachi","jodan",""],
["35","tate-uraken-uchi","vertical back-fist strike","zenkutsu-dachi","jodan",""],
["36","tsuki-uke / haiwan-uchi-nagashi-uke","punch-block / back-arm inside flowing block","zenkutsu-dachi","chudan / jodan",""],
["37","tate-uraken-uchi / zenwan-mune-suhei-kamae","vertical back-fist strike / forearm chest posture","zenkutsu-dachi","jodan / --","ura-zuki variation"],
["38","uchi-uke","inside block","zenkutsu-dachi","chudan",""],
["39","oi-zuki","lunge punch","zenkutsu-dachi","chudan",""],
["40","uchi-uke","inside block","zenkutsu-dachi","chudan",""],
["41","oi-zuki","lunge punch","zenkutsu-dachi","chudan",""],
["42","gedan-barai","down block","zenkutsu-dachi","gedan",""],
["43","zenwan-uchi-otoshi / fumikomi","forearm falling strike / stomp kick","kiba-dachi","chudan",""],
["44","zenwan-uchi-otoshi / fumikomi","forearm falling strike / stomp kick","kiba-dachi","chudan",""],
["45","zenwan-uchi-otoshi / fumikomi","forearm falling strike / stomp kick","kiba-dachi","chudan",""],
["46","sokumen-zuki (yumi-zuki)","punch to side (bow punch)","kiba-dachi","chudan","yori-ashi · slow speed"],
["47*","sokumen-zuki (yumi-zuki)","punch to side (bow punch)","kiba-dachi","chudan","yori-ashi · slow variation"],
] as [string,string,string,string,string,string][];

export function JionPage() {
  return <KataEditorialPage title="Jion" number="11" series="Sentei Series" previous={["Kanku Dai","kanku-dai"]} next={["Empi","empi"]} intro={<><p><em>Jion</em> is believed to be named after the <em>Jion-ji</em>, a Buddhist temple in China. Since there are many <em>Jion-ji</em> temples in existence, it is uncertain which one the kata refers to. The actual translation of <em>Jion</em> means "Love and Goodness." Although the kata's creator is unknown, credit is usually given to Sokon Matsumura, who is presumed to have learned this kata during his travels to China. <em>Jion</em> is the simplest of the <em>Sentei</em> kata and is comprised mostly of pieces from <em>Heian</em> and <em>Tekki</em> kata. It has 47 counts and contains some of the most basic movements that Shotokan has to offer. Being a simple kata, there are no fancy moves to hide behind. If a student possesses poor basics, then the performance of <em>Jion</em> will be weak. For this reason, it is an excellent kata to judge one's overall technique. The idea when performing the kata is to be like a Buddha, with a strong yet humble spirit. The simplicity of its movements demonstrates one's humility, yet each technique should be performed with explosive power and unwavering stability. Instructors have been known to group <em>Jion</em> along with <em>Jiin</em> and <em>Jitte</em>, since each start with the same hand-over-fist salutation and have very similar movements.</p></>} movements={movements} />;
}
