import { KataEditorialPage } from "./KataEditorialPage";

const movements = [
["1","ryote-hitae-mae-ue","both hands in front and above forehead","hachiji-dachi","jodan","slow speed"],
["2","ryote-kafukubu-mae","both hands in front of abdomen","hachiji-dachi","--","slow speed"],
["3","haiwan-uke","back of arm block","kokutsu-dachi","jodan",""],
["4","haiwan-uke","back of arm block","kokutsu-dachi","jodan",""],
["5","tate-shuto-uke","vertical knife-hand block","hachiji-dachi","chudan","slow speed"],
["6","tsuki (choku-zuki)","punch (straight punch)","hachiji-dachi","chudan",""],
["7","uchi-uke","inside block","hizakutsu","chudan",""],
["8","tsuki (choku-zuki)","punch (straight punch)","hachiji-dachi","chudan",""],
["9","uchi-uke","inside block","hizakutsu","chudan",""],
["10","ryoken-koshi-kamae","both fists hip posture","ashi-dachi","--",""],
["11","uraken-yoko-mawashi-uchi / yoko-geri-keage","sideways back-fist strike / side snap kick","ashi-dachi","jodan / chudan",""],
["12","shuto-uke","knife-hand block","kokutsu-dachi","chudan",""],
["13","shuto-uke","knife-hand block","kokutsu-dachi","chudan",""],
["14","shuto-uke","knife-hand block","kokutsu-dachi","chudan",""],
["15*","osae-uke / shihon-nukite (tate-nukite)","pressing block / four finger spear-hand (vertical spear-hand)","zenkutsu-dachi","chudan / chudan",""],
["16","shuto-gedan-barai & jodan-uke / shuto-soto-mawashi-uchi","low knife-hand sweep & face block / outside sword-hand strike","ashi-zenkutsu","gedan / jodan / jodan","gyaku-hanmi"],
["17","mae-geri","front kick","ashi-dachi","jodan",""],
["18","uchi-uke / gedan-uke (manji-uke)","inside block / down block (swirling block)","kokutsu-dachi","jodan / gedan",""],
["19","nagashi-uke / shuto-uchikomi","flowing block / knife-hand thrusting strike","ashi-zenkutsu","jodan / gedan",""],
["20","gedan-barai","down block","renoji-dachi","gedan","slow speed"],
["21","shuto-gedan-barai & jodan-uke / shuto-soto-mawashi-uchi","low knife-hand sweep & face block / outside sword-hand strike","ashi-zenkutsu","gedan / jodan / jodan","gyaku-hanmi"],
["22","mae-geri","front kick","ashi-dachi","jodan",""],
["23","uchi-uke / gedan-uke (manji-uke)","inside block / down block (swirling block)","kokutsu-dachi","jodan / gedan",""],
["24","nagashi-uke / shuto-uchikomi","flowing block / knife-hand thrusting strike","ashi-zenkutsu","jodan / gedan",""],
["25","gedan-barai","down block","renoji-dachi","gedan","slow speed"],
["26","ryoken-koshi-kamae","both fists hip posture","ashi-dachi","--",""],
["27","uraken-yoko-mawashi-uchi / yoko-geri-keage","sideways back-fist strike / side snap kick","ashi-dachi","jodan / chudan",""],
["28","mae-empi-uchi","front elbow strike","zenkutsu-dachi","--",""],
["29","ryoken-koshi-kamae","both fists hip posture","ashi-dachi","--",""],
["30","uraken-yoko-mawashi-uchi / yoko-geri-keage","sideways back-fist strike / side snap kick","ashi-dachi","jodan / chudan",""],
["31","mae-empi-uchi","front elbow strike","zenkutsu-dachi","--",""],
["32","shuto-uke","knife-hand block","kokutsu-dachi","chudan",""],
["33","shuto-uke","knife-hand block","kokutsu-dachi","chudan",""],
["34","shuto-uke","knife-hand block","kokutsu-dachi","chudan",""],
["35","shuto-uke","knife-hand block","kokutsu-dachi","chudan",""],
["36","shuto-gedan-barai & jodan-uke / shuto-soto-mawashi-uchi","low knife-hand sweep & face block / outside sword-hand strike","ashi-zenkutsu","gedan / jodan / jodan","gyaku-hanmi"],
["37","mae-geri","front kick","ashi-dachi","jodan",""],
["38","uraken-tate-mawashi-uchi","vertical back-fist strike","kosa-dachi","jodan",""],
["39","uchi-uke","inside block","zenkutsu-dachi","chudan",""],
["40","gyaku-zuki","reverse punch","zenkutsu-dachi","chudan",""],
["41","tsuki","punch","zenkutsu-dachi","chudan",""],
["42","soete-ura-zuki / hiza-zuchi","added hand inverted punch / knee strike","ashi-dachi","jodan / --",""],
["43","ude-tate-fuse","arms vertically prone","ashi-zenkutsu","--",""],
["44","shuto-uke","knife-hand block","kokutsu-dachi","gedan",""],
["45","shuto-uke","knife-hand block","kokutsu-dachi","chudan",""],
["46","uchi-uke","inside block","zenkutsu-dachi","chudan",""],
["47","gyaku-zuki","reverse punch","zenkutsu-dachi","chudan",""],
["48","uchi-uke","inside block","zenkutsu-dachi","chudan",""],
["49","gyaku-zuki","reverse punch","zenkutsu-dachi","chudan",""],
["50","tsuki","punch","zenkutsu-dachi","chudan",""],
["51","ryoken-koshi-kamae","both fists hip posture","ashi-dachi","--",""],
["52","uraken-yoko-mawashi-uchi / yoko-geri-keage","sideways back-fist strike / side snap kick","ashi-dachi","jodan / chudan",""],
["53","shuto-uke","knife-hand block","kokutsu-dachi","chudan",""],
["54","osae-uke / shihon-nukite (tate-nukite)","pressing block / four finger spear-hand (vertical spear-hand)","zenkutsu-dachi","chudan / chudan",""],
["55","uraken-tate-mawashi-uchi","vertical back-fist strike","kiba-dachi","jodan",""],
["56","kentsui-uchi-mawashi-uchi","inside hammer-fist strike","kiba-dachi","chudan","yori-ashi"],
["57","sokumen-mae-empi-uchi","front elbow strike to side","kiba-dachi","--",""],
["58","ryoken-koshi-kamae","both fists hip posture","kiba-dachi","--",""],
["59","gedan-barai","down block","kiba-dachi","gedan",""],
["60","zenwan-gedan-uke / furiage","forearm down block / rising swing","kiba-dachi","gedan / jodan","fumikomi variation"],
["61","otoshi-zuki","falling punch","kiba-dachi","gedan",""],
["62","kaisho-kosa-uke (ryosho-juji-uke)","both palms crossing block (X-block)","hachiji-dachi","jodan",""],
["63","ashi-jiku-mawari","foot pivot rotation","zenkutsu-dachi","--","natural speed"],
["64","ryoken-mune-mae-kosa","both fists crossed in front of chest","zenkutsu-dachi","--","slow speed"],
["65*","nidan-geri & uraken-tate-mawashi-uchi","two level kick & vertical back-fist strike","-- / zenkutsu-dachi","chudan / jodan / jodan",""],
] as [string,string,string,string,string,string][];

export function KankuDaiPage() {
  return <KataEditorialPage title="Kanku Dai" number="10" series="Sentei Series" previous={["Bassai Dai","bassai-dai"]} next={["Jion","jion"]} intro={<><p>Having 65 movements, <em>Kanku Dai</em> is the longest of the <em>Sentei</em> kata, as well as one of the longest kata in the Shotokan syllabus. <em>Kanku</em> translates as "Looking at the Sky" or "Viewing the Sky," referring to the kata's opening sequence. The word <em>Dai</em> (big) is used to describe the kata's larger movements as compared to the kata's smaller version, <em>Kanku Sho</em>. <em>Kanku</em> is one of three Shotokan kata that have two versions, <em>Dai</em> (big) and <em>Sho</em> (small). Originally, the kata was called <em>Kushanku</em>, named after a Chinese diplomat and <em>kung fu</em> expert. It is uncertain if this diplomat actually created the kata (or if he even existed), but many credit the kata to one of his alleged students, Santunuku Sakugawa.</p><p className="mt-5"><em>Kanku Dai</em> is basically an amalgamation of the <em>Heian</em> and <em>Tekki</em> kata. When practicing this kata, one will find many pieces of H2-H5, and even some T1. It is a very energetic kata involving jumping, dropping, and spinning techniques. It is said that this was Gichin Funakoshi's favorite kata. Although the kata tends to favor the use of <em>shuto-uchi</em>, <em>Kanku Dai</em> offers two unique combinations, <em>ura-zuki & ude-tate-fuse</em> and <em>gedan-uke/furiage</em>. The very difficult jumping <em>nidan-geri</em> is also first practiced in this kata. <em>Kanku Dai</em> has many high and low techniques, requiring a certain amount of flexibility. It is a highly dynamic kata that must be performed with grace in motion.</p></>} movements={movements} />;
}
