type KataGroup = { title: string; intro?: string; items: string[] };

const groups: KataGroup[] = [
  { title: "HEIAN", intro: "The five Heian kata (or Pinan in Okinawan) were developed by Gichin Funakoshi's teacher, Yasutsune Itosu, to facilitate the teaching of karate to large groups of students. The word Heian combines heiwa, meaning calm or peaceful, and antei, meaning easy or stable. Therefore, Heian could be translated as Peace and Stability. Gichin Funakoshi uses Peaceful Mind in Karate-Do Kyohan. Heian kata are taught to beginner and intermediate students. Originally, Heian Shodan and Heian Nidan were taught in reverse order, with names reversed as well; Funakoshi switched their order to better indicate their respective difficulties.", items: ["Heian Shodan", "Heian Nidan", "Heian Sandan", "Heian Yondan", "Heian Godan"] },
  { title: "TEKKI", intro: "Tekki (also Naihanchi or Naifanchi) is usually translated as Iron Horseman. Aside from crossing the feet in kosa position a few times, all movements in the three Tekki kata are performed in horse stance. Their embusen is a lateral straight line with no forward or backward stepping motions. The idea is that you are defending against assailants with your back to a wall. Tekki develops a strong horse stance, sharp hip vibration, and stealthy lateral movement. Sokon Matsumura is believed to have learned Tekki during excursions to China; Yasutsune Itosu modified and expanded it, creating Tekki Nidan and Tekki Sandan.", items: ["Tekki Shodan", "Tekki Nidan", "Tekki Sandan"] },
  { title: "SENTEI", intro: "Sentei means selection. The four selection kata exemplify Shotokan karate. They are strong yet humble kata, usually taught at the brown belt level. A 1st kyu brown belt chooses a tokui kata from these four for the black belt exam. All black belts are expected to know the four Sentei kata for tournament elimination rounds. Although taught after Heian and Tekki, the Sentei kata predate them; Heian were created later to simplify their learning.", items: ["Bassai Dai", "Kanku Dai", "Jion", "Empi"] },
  { title: "ADVANCED (FUNAKOSHI)", intro: "These three kata represent the more advanced kata taught by Gichin Funakoshi. They require deeper understanding of breathing, muscle contraction and expansion, and timing. Although Funakoshi taught Taikyoku kata and Ten No Kata, he taught 15 of the standard 26 Shotokan kata: the 5 Heian, 3 Tekki, 4 Sentei, and 3 advanced kata.", items: ["Jitte", "Gankaku", "Hangetsu"] },
  { title: "ADVANCED (NAKAYAMA)", intro: "These nine kata were labeled Advanced Kata in Masatoshi Nakayama's Best Karate series. They require greater agility, with extravagant movements including jumping, falling, and high kicks. Most were borrowed from other karate styles and stem directly from the five animals of Shaolin kung fu. They tend to be exciting for performers and spectators and are usually tournament favorites.", items: ["Kanku Sho", "Bassai Sho", "Chinte", "Nijushiho", "Sochin", "Unsu", "Gojushiho Sho", "Gojushiho Dai", "Meikyo"] },
  { title: "ADVANCED (RARE)", intro: "These two kata are also considered advanced. They were the only kata never described in Nakayama's Best Karate series, leaving them shrouded in mystery. The JKA later included Wankan in newer kata books while Jiin was removed from the JKA kata syllabus.", items: ["Wankan", "Jiin"] },
  { title: "MODERN", intro: "These modern kata were created in the 30s by Gichin Funakoshi and his son Gigo. They are the most basic kata, feeling more like kihon, and were made to simplify teaching large groups. Although considered overly simplified and obsolete by many instructors today, Taikyoku Shodan remains a required kata for early kyu exams at several dojo, including the honbu dojo in Japan as listed by the JKA.", items: ["Taikyoku Shodan", "Taikyoku Nidan", "Taikyoku Sandan", "Ten No Kata"] },
];

const counts: Array<[string, number, number | string, number]> = [
  ["Heian Shodan",9,17,21],["Heian Nidan",11,26,26],["Heian Sandan",10,20,20],["Heian Yondan",13,25,27],["Heian Godan",12,19,23],["Tekki Shodan",15,29,29],["Tekki Nidan",16,24,24],["Tekki Sandan",16,36,36],["Bassai Dai",19,36,36],["Kanku Dai",15,42,42],["Jion",17,47,47],["Empi",15,36,37],["Jitte",13,24,24],["Gankaku",28,42,42],["Hangetsu",11,40,41],["Kanku Sho",6,48,48],["Bassai Sho",17,22,27],["Chinte",28,32,32],["Nijushiho",18,33,34],["Sochin",30,41,41],["Unsu",36,48,48],["Gojushiho Sho",57,64,65],["Gojushiho Dai",59,66,67],["Meikyo",32,33,33],["Wankan",24,"--",24],["Jiin",11,35,35]
];
const slug = (name: string) => name.toLowerCase().replace(/\s+/g, "-");

function KataCard({ name, first, second, total }: { name: string; first: number; second: number | string; total: number }) {
  return <a href={`/karate/kata/${slug(name)}`} className="group block border-t border-[#bfb5a4] py-4 transition-colors hover:border-[#9b3d18]"><div className="flex items-start justify-between gap-4"><div><h3 className="font-[var(--font-display)] text-lg font-bold uppercase leading-none tracking-[-.02em] group-hover:text-[#9b3d18]">{name}</h3><p className="mt-2 text-[.53rem] font-bold uppercase tracking-[.18em] text-[#777067]">Explore kata reference ↗</p></div><span className="text-xl text-[#9b3d18] transition-transform group-hover:translate-x-1">→</span></div><div className="mt-4 grid grid-cols-3 border-y border-[#ded6c7] py-2 text-[.55rem] font-bold uppercase tracking-[.13em] text-[#716a61]"><span>1st kiai <b className="ml-1 text-[#111]">{first}</b></span><span>2nd <b className="ml-1 text-[#111]">{second}</b></span><span># <b className="ml-1 text-[#111]">{total}</b></span></div></a>;
}

export function KataSection() {
  return <section id="kata" aria-labelledby="kata-title" className="relative overflow-hidden border-y border-[#cfc6b5] bg-[#e9e2d3] px-5 py-20 text-[#111] md:px-10 md:py-28"><div className="mx-auto max-w-[1180px]">
    <div className="mb-12 flex flex-col gap-5 border-b border-[#cfc6b5] pb-8 md:flex-row md:items-end md:justify-between"><div><p className="mb-3 text-[.62rem] font-bold uppercase tracking-[.3em] text-[#9b3d18]">Dhanurveda · Karate forms</p><h2 id="kata-title" className="font-[var(--font-display)] text-6xl font-bold uppercase leading-[.82] tracking-[-.03em] md:text-8xl">Kata</h2></div><div className="max-w-sm font-serif text-sm leading-relaxed text-[#514b44]">Pre-arranged movement, imaginary opponents, embusen, bunkai, rhythm, timing, breathing and zanshin — preserved as a living library.</div></div>
    <div className="grid gap-10 border-b border-[#cfc6b5] pb-12 lg:grid-cols-[1.35fr_.65fr]"><div className="space-y-5 font-serif text-[.94rem] leading-[1.7] text-[#3f3a34] md:text-[1rem]"><p>Kata are the pre-arranged sets of movements in which the karateka defends against several imaginary attackers. Each movement represents a self-defense technique against a potential opponent. These self-defense applications are traditionally called bunkai (analysis), although oyo (application) is also used. All kata have an embusen, or performance line — the floor plan of the kata. Movements must always be performed in the correct order, and a kata must always start and finish on the same spot.</p><p>Kata is one of the earliest forms of karate training and how karate passed from one generation to the next. Kata teach movement in all directions, sometimes jumping or dropping. Some are strong and sturdy, while others require speed and agility. Certain techniques are performed slowly and powerfully, while others are sharp and quick.</p><p>By practicing kata, students learn rhythm and timing, expansion and contraction of the body's muscles, and proper breathing. A performance must exude confidence while maintaining kata's humble nature. Zanshin means remaining mind: a relaxed state of readiness and awareness of any remaining potential danger. Only after the final bow is the kata truly finished.</p></div><aside className="border-l-2 border-[#9b3d18] pl-6"><p className="font-[var(--font-display)] text-5xl font-bold uppercase leading-[.9]">26</p><p className="mt-3 text-[.6rem] font-bold uppercase tracking-[.2em] text-[#777067]">Kata in the reference syllabus</p><p className="mt-6 font-serif text-sm leading-relaxed text-[#514b44]">The reference describes 26 kata, noted as 25 not including Jiin.</p></aside></div>
    <div className="mt-12"><div className="mb-7 flex items-end justify-between"><div><p className="text-[.58rem] font-bold uppercase tracking-[.25em] text-[#9b3d18]">The complete library</p><h3 className="mt-2 font-[var(--font-display)] text-3xl font-bold uppercase md:text-5xl">Kata syllabus</h3></div><span className="hidden text-[.55rem] font-bold uppercase tracking-[.2em] text-[#777067] md:block">Click any kata to open its reference</span></div><div className="grid gap-x-8 gap-y-12 md:grid-cols-2">{groups.map(group => <section key={group.title} className="border-t-2 border-[#111] pt-5"><div className="mb-5"><h4 className="font-[var(--font-display)] text-2xl font-bold uppercase leading-none">{group.title}</h4>{group.intro && <p className="mt-4 font-serif text-[.78rem] leading-[1.65] text-[#514b44]">{group.intro}</p>}</div><div>{group.items.map(name => { const row = counts.find(c => c[0] === name); return row ? <KataCard key={name} name={name} first={row[1]} second={row[2]} total={row[3]}/> : null; })}</div></section>)}</div></div>
    <div className="mt-14 border-t border-[#cfc6b5] pt-7"><p className="mb-5 text-[.58rem] font-bold uppercase tracking-[.25em] text-[#9b3d18]">Reference key</p><div className="grid gap-3 text-[.72rem] text-[#514b44] sm:grid-cols-2 lg:grid-cols-5"><span><b>*</b> kiai</span><span><b>/</b> simultaneous techniques</span><span><b>&amp;</b> successive techniques counted as one</span><span><b>( )</b> alternate technique names</span><span><b>1st / 2nd / #</b> kiai points and total counts</span></div></div>
  </div></section>;
}
