import { ArrowLeft, ArrowRight, ArrowUpRight } from "lucide-react";

const sections = [
  { number: "01", title: "Basic Kicks", description: "Basic kicks are simply those kicks that are practiced most often in Shotokan. These kicks are standard and are practiced almost every class. These kicks are usually learned right at the beginning of one's training. They are fairly simple and don't require too much flexibility.", techniques: [["mae-geri", "front kick"], ["yoko-geri-keage", "side snap kick"], ["yoko-geri-kekomi", "side thrust kick"], ["mawashi-geri", "roundhouse kick"]], image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Mae-geri.jpg", label: "Mae-geri" },
  { number: "02", title: "Advanced Kicks", description: "Advanced kicks are those kicks that are practiced much less often, due to their difficulty and risky nature. Advanced kicks usually leave the kicker in a very precarious position. Although use of these kicks can be very dangerous, they can often be very deceptive. These kicks are extremely difficult to perform, requiring excellent speed, timing, and balance skills. Without proper flexibility, these kicks cannot be performed at all.", techniques: [["ushiro-geri", "back kick"], ["ura-mawashi-geri", "reverse roundhouse kick"], ["mikazuki-geri", "crescent (moon) kick"], ["tobi-geri", "jump kick"]], image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Ushiro-geri.jpg", label: "Advanced kick" },
  { number: "03", title: "Advanced Leg Attacks", description: "These advanced techniques are executed with the foot, but are usually not considered as kicks in the conventional sense. They are mainly used to damage an opponent's legs or to break an assailant's balance. All targets for these attacks are below hip level (gedan).", techniques: [["fumi-komi", "thrusting step (stomping kick)"], ["ashi-barai", "foot sweep"], ["nami-gaeshi (nami-ashi-geri)", "returning wave (wave-leg kick)"]], image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Ashibarai.jpg", label: "Ashi-barai" },
  { number: "04", title: "Non-Traditional Kicks", description: "These kicks are not exactly mainstream Shotokan. Very few dojo will practice them. Many of these kicks are too difficult to control and only end up damaging your partner in class or competition. The use of some of these kicks can even result in injury to your own foot or leg. These kicks cannot be found in Shotokan kata or traditional kumite and, therefore, are not really considered as part of the modern Shotokan system.", techniques: [["ushiro-ura-mawashi-geri", "spinning back reverse roundhouse kick"], ["ura-mikazuki-geri", "reverse (inside) crescent kick"], ["kage-geri", "hook kick"], ["otoshi-kakato-geri", "dropping heel kick (axe kick / hammer kick)"], ["tsumasaki-geri", "tip of toes kick"], ["sune-geri", "shin kick"], ["kin-geri", "groin kick"], ["naname-geri", "oblique kick"]], image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Mawashi-geri.jpg", label: "Keri reference" },
];

const intro = "Kicks include all attacks performed with the legs or feet. Since the muscles of the leg are much larger and stronger than the muscles of the arm, kicking techniques are generally more powerful than hand techniques. They also have a greater attack range. However, kicking does have its drawbacks. Since the leg is bulkier than the arm, kicks tend to be a little slower. Also when kicking, the foot usually has to travel a further distance to reach its target, again sacrificing speed. Finally, kicks leave the karateka on only one leg, compromising balance. For these reasons, punches tend to be viewed more favourably in Shotokan. Keri can be separated into 4 categories:";

function Vocabulary({ items }: { items: string[][] }) {
  return <div className="mt-8 border-t border-[#cfc6b5] pt-5"><p className="mb-4 text-[0.58rem] font-bold uppercase tracking-[0.25em] text-[#9b3d18]">Keri vocabulary</p>{items.map(([name, meaning]) => <div key={name} className="grid grid-cols-[minmax(0,.8fr)_minmax(0,1.2fr)] gap-5 border-b border-[#ded6c7] py-2 text-[.78rem] md:text-[.84rem]"><span className="font-serif italic">{name}</span><span className="text-[#555048]">{meaning}</span></div>)}</div>;
}

export function KeriPage() {
  return <div className="min-h-screen bg-[#e9e2d3] text-[#111111]">
    <header className="sticky top-0 z-30 border-b border-[#cfc6b5] bg-[#e9e2d3]/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1180px] items-center justify-between px-5 md:px-8"><a href="/karate/" className="group flex items-center gap-3 text-[.62rem] font-bold uppercase tracking-[.22em]"><ArrowLeft className="h-4 w-4 group-hover:-translate-x-1"/>Dhanurveda</a><div className="hidden items-center gap-6 text-[.58rem] font-bold uppercase tracking-[.2em] text-[#69635a] md:flex"><a href="/karate/kihon/tachi">Tachi</a><a href="/karate/kihon/uke">Uke</a><a href="/karate/kihon/tsuki">Tsuki</a><a href="/karate/kihon/keri" className="text-[#9b3d18]">Keri</a><a href="/karate/kihon/uchi">Uchi</a></div><span className="text-[.58rem] font-bold uppercase tracking-[.2em] text-[#9b3d18]">Kihon 04</span></div></header>
    <main>
      <section className="border-b border-[#cfc6b5] px-5 pb-14 pt-16 md:px-8 md:pb-20 md:pt-24"><div className="mx-auto grid max-w-[1180px] gap-10 lg:grid-cols-[1.05fr_.95fr] lg:items-end"><div><p className="mb-5 text-[.62rem] font-bold uppercase tracking-[.32em] text-[#9b3d18]">Kihon 04 · Kicks</p><h1 className="font-[var(--font-display)] text-[clamp(4.5rem,13vw,10rem)] font-bold uppercase leading-[.78] tracking-[-.055em]">Keri</h1><p className="mt-7 max-w-2xl font-serif text-[1rem] leading-[1.65] text-[#36322d] md:text-[1.08rem]">{intro}</p></div><div className="relative overflow-hidden border border-[#bfb5a4] bg-[#f0eadf] p-5"><div className="absolute left-0 top-0 h-1 w-20 bg-[#9b3d18]"/><div className="flex min-h-[280px] items-center justify-center"><div className="relative h-[260px] w-full overflow-hidden"><div className="absolute left-[12%] top-[56%] h-px w-[72%] -rotate-[20deg] bg-[#9b3d18]/50"/><div className="absolute left-[30%] top-[28%] h-[150px] w-px rotate-[20deg] bg-[#111]/20"/><div className="absolute left-[29%] top-[23%] h-20 w-20 rounded-full border border-[#111]/20"/><div className="absolute right-[10%] top-[20%] font-[var(--font-display)] text-[6rem] font-bold leading-none text-[#9b3d18]/25">蹴</div><div className="absolute bottom-5 left-0 right-0 text-center font-serif text-lg italic">Reach · Balance · Return</div></div></div><div className="flex items-end justify-between border-t border-[#cfc6b5] pt-4"><div><p className="font-serif text-lg italic">Keri</p><p className="text-[.56rem] font-bold uppercase tracking-[.2em] text-[#777067]">Kicking techniques</p></div><a href="https://commons.wikimedia.org/" target="_blank" rel="noreferrer" className="text-[#9b3d18]"><ArrowUpRight className="h-4 w-4"/></a></div></div></div></section>
      <section className="px-5 py-14 md:px-8 md:py-20"><div className="mx-auto grid max-w-[1180px] gap-10 border-b border-[#cfc6b5] pb-14 lg:grid-cols-[1fr_.45fr]"><p className="font-serif text-[.94rem] leading-[1.72] text-[#3f3a34] md:text-[1rem]">The leg offers extraordinary power and range, but every kick asks the karateka to temporarily trade stability for reach. That trade makes timing, control and recovery central to effective keri practice.</p><aside className="border-l-2 border-[#9b3d18] pl-6 font-serif text-xl italic leading-[1.45] text-[#4b453e]">Power is useful only when balance survives the technique.</aside></div></section>
      <nav className="border-y border-[#cfc6b5] px-5 py-4 md:px-8"><div className="mx-auto flex max-w-[1180px] gap-2 overflow-x-auto pb-1">{sections.map(s=><a key={s.number} href={`#keri-${s.number}`} className="shrink-0 border border-[#cfc6b5] px-4 py-2 text-[.56rem] font-bold uppercase tracking-[.18em] hover:border-[#9b3d18] hover:text-[#9b3d18]">{s.number} · {s.title}</a>)}</div></nav>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1180px]"><div className="mb-12 flex items-end justify-between border-b border-[#cfc6b5] pb-5"><div><p className="text-[.58rem] font-bold uppercase tracking-[.25em] text-[#9b3d18]">The four families</p><h2 className="mt-2 font-[var(--font-display)] text-3xl font-bold uppercase tracking-[-.02em] md:text-5xl">The art of keri</h2></div><span className="hidden text-[.55rem] font-bold uppercase tracking-[.2em] text-[#7b746b] md:block">Speed · timing · balance</span></div><div className="space-y-16 md:space-y-24">{sections.map(s=><article id={`keri-${s.number}`} key={s.number} className="scroll-mt-24 border-t-2 border-[#111] pt-7"><div className="grid gap-8 lg:grid-cols-[90px_1fr_300px] lg:gap-10"><div><span className="font-[var(--font-display)] text-4xl font-bold text-[#9b3d18]">{s.number}</span></div><div><h3 className="font-[var(--font-display)] text-3xl font-bold uppercase leading-none tracking-[-.02em] md:text-4xl">{s.title}</h3><p className="mt-6 font-serif text-[.94rem] leading-[1.72] text-[#3f3a34] md:text-[1rem]">{s.description}</p><Vocabulary items={s.techniques}/></div><div className="border border-[#cfc6b5] bg-[#f0eadf] p-4"><div className="flex h-[240px] items-center justify-center overflow-hidden"><img src={s.image} alt={s.label} className="max-h-full max-w-full object-contain mix-blend-multiply" loading="lazy"/></div><div className="border-t border-[#cfc6b5] pt-3 text-[.56rem] font-bold uppercase tracking-[.16em] text-[#716a61]">{s.label} · reference diagram</div></div></div></article>)}</div></div></section>
      <section className="border-t border-[#cfc6b5] px-5 py-12 md:px-8"><div className="mx-auto flex max-w-[1180px] flex-col gap-5 md:flex-row md:items-center md:justify-between"><a href="/karate/kihon/uke" className="group inline-flex items-center gap-3 text-[.62rem] font-bold uppercase tracking-[.2em]"><ArrowLeft className="h-4 w-4 group-hover:-translate-x-1"/>Previous · Uke</a><span className="text-[.55rem] font-bold uppercase tracking-[.2em] text-[#777067]">Discipline builds freedom</span><a href="/karate/kihon/uchi" className="group inline-flex items-center gap-3 text-[.62rem] font-bold uppercase tracking-[.2em] text-[#9b3d18]">Next · Uchi<ArrowRight className="h-4 w-4 group-hover:translate-x-1"/></a></div></section>
    </main>
  </div>;
}
