type KumiteItem = { name: string; label: string; description: string; href: string };

const training: KumiteItem[] = [
  { name: "Kihon-Gohon-Kumite", label: "5-step sparring", description: "Foundational announced sparring: repeat the same attack and target while developing distance, timing, stance and clean defensive movement.", href: "/karate/kumite/kihon-gohon-kumite" },
  { name: "Kihon-Sanbon-Kumite", label: "3-step sparring", description: "A shorter progression that sharpens rhythm, ma-ai and the transition from block to counter-attack.", href: "/karate/kumite/kihon-sanbon-kumite" },
  { name: "Kihon-Ippon-Kumite", label: "1-step sparring", description: "One announced attack followed by a decisive defense and counter. A bridge from basic drills toward free movement.", href: "/karate/kumite/kihon-ippon-kumite" },
  { name: "Jiyu-Ippon-Kumite", label: "Semi-free one-step", description: "The attacker chooses the attack while both partners move more naturally, demanding sharper timing, distance and control.", href: "/karate/kumite/jiyu-ippon-kumite" },
  { name: "Jiyu-Kumite", label: "Freestyle sparring", description: "Unannounced attacks and combinations from both partners. Control, awareness, composure and technical accuracy become paramount.", href: "/karate/kumite/jiyu-kumite" },
  { name: "Shiai-Kumite", label: "Competition sparring", description: "Sport-oriented sparring where timing, scoring awareness, movement and disciplined control meet competitive pressure.", href: "/karate/kumite/shiai-kumite" },
  { name: "Oyo-Kumite", label: "Application sparring", description: "Applied partner work that explores how karate techniques translate into practical defensive situations and combinations.", href: "/karate/kumite/oyo-kumite" },
];

const levels = [
  { name: "Beginner", href: "/karate/kumite/beginner", detail: "Foundation · control · announced attacks" },
  { name: "Intermediate", href: "/karate/kumite/intermediate", detail: "Timing · distance · combinations" },
  { name: "Advanced", href: "/karate/kumite/advanced", detail: "Freestyle · pressure · precision" },
];

function KumiteCard({ item, index }: { item: KumiteItem; index: number }) {
  return <a href={item.href} className="group block border-t border-[#bfb5a4] py-5 transition-colors hover:border-[#9b3d18]"><div className="flex gap-4"><span className="pt-1 font-[var(--font-display)] text-[.65rem] font-bold tracking-[.15em] text-[#9b3d18]">0{index + 1}</span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-4"><div><h3 className="font-[var(--font-display)] text-xl font-bold uppercase leading-none tracking-[-.02em] group-hover:text-[#9b3d18]">{item.name}</h3><p className="mt-2 text-[.53rem] font-bold uppercase tracking-[.18em] text-[#777067]">{item.label}</p></div><span className="text-xl text-[#9b3d18] transition-transform group-hover:translate-x-1">→</span></div><p className="mt-4 max-w-xl font-serif text-[.78rem] leading-[1.65] text-[#514b44]">{item.description}</p></div></div></a>;
}

export function KumiteSection() {
  return <section id="kumite" aria-labelledby="kumite-title" className="relative overflow-hidden border-y border-[#cfc6b5] bg-[#e9e2d3] px-5 py-20 text-[#111] md:px-10 md:py-28"><div className="mx-auto max-w-[1180px]">
    <div className="mb-12 flex flex-col gap-5 border-b border-[#cfc6b5] pb-8 md:flex-row md:items-end md:justify-between"><div><p className="mb-3 text-[.62rem] font-bold uppercase tracking-[.3em] text-[#9b3d18]">Dhanurveda · Partner training</p><h2 id="kumite-title" className="font-[var(--font-display)] text-6xl font-bold uppercase leading-[.82] tracking-[-.03em] md:text-8xl">Kumite</h2></div><div className="max-w-sm font-serif text-sm leading-relaxed text-[#514b44]">Meeting of hands. Sparring that turns technique into timing, distance, control, pressure and awareness.</div></div>
    <div className="grid gap-10 border-b border-[#cfc6b5] pb-12 lg:grid-cols-[1.35fr_.65fr]"><div className="space-y-5 font-serif text-[.94rem] leading-[1.7] text-[#3f3a34] md:text-[1rem]"><p><em>Kumite</em> means “meeting of hands.” In karate, the term is translated as “sparring.” It is the only facet of karate that requires a partner to practice with.</p><p>Beginner and intermediate students usually train <em>yakusoku-kumite</em>, or sparring with announcement. The attacker announces the attack and target; the defender blocks or evades and launches an effective counter-attack. Contact is generally not permitted for beginners, and counter-attacks are controlled.</p><p>Advanced karateka practice <em>jiyu-kumite</em>, or freestyle sparring. Attacks and combinations are thrown at will by both partners without announcement. Good control remains of utmost importance.</p></div><aside className="border-l-2 border-[#9b3d18] pl-6"><p className="font-[var(--font-display)] text-5xl font-bold uppercase leading-[.9]">7</p><p className="mt-3 text-[.6rem] font-bold uppercase tracking-[.2em] text-[#777067]">Traditional training methods</p><p className="mt-6 font-serif text-sm leading-relaxed text-[#514b44]">From structured five-step practice to freestyle and application work, each method adds another layer of timing and control.</p></aside></div>
    <div className="mt-12"><div className="mb-7 flex items-end justify-between"><div><p className="text-[.58rem] font-bold uppercase tracking-[.25em] text-[#9b3d18]">The complete library</p><h3 className="mt-2 font-[var(--font-display)] text-3xl font-bold uppercase md:text-5xl">Kumite syllabus</h3></div><span className="hidden text-[.55rem] font-bold uppercase tracking-[.2em] text-[#777067] md:block">Click any method to open its reference</span></div><div className="grid gap-x-10 gap-y-12 md:grid-cols-2">{training.map((item, index) => <KumiteCard key={item.name} item={item} index={index} />)}</div></div>
    <div className="mt-14 border-t-2 border-[#111] pt-6"><div className="mb-6"><p className="text-[.58rem] font-bold uppercase tracking-[.25em] text-[#9b3d18]">Training level</p><h3 className="mt-2 font-[var(--font-display)] text-3xl font-bold uppercase md:text-4xl">Choose your stage</h3></div><div className="grid gap-4 md:grid-cols-3">{levels.map(level => <a key={level.name} href={level.href} className="group border border-[#bfb5a4] bg-[#e3dccd] p-5 transition-colors hover:border-[#9b3d18] hover:bg-[#ded5c4]"><div className="flex items-center justify-between gap-3"><h4 className="font-[var(--font-display)] text-2xl font-bold uppercase leading-none group-hover:text-[#9b3d18]">{level.name}</h4><span className="text-lg text-[#9b3d18]">↗</span></div><p className="mt-3 text-[.58rem] font-bold uppercase tracking-[.15em] text-[#777067]">{level.detail}</p></a>)}</div></div>
  </div></section>;
}
