import { ArrowLeft, ArrowRight, BookOpen, ChevronRight } from "lucide-react";
import { useMemo } from "react";

type Section = { title: string; body?: string[]; items?: string[] };
type Reference = { title: string; eyebrow: string; intro: string; sections: Section[]; next?: string; prev?: string };

const references: Record<string, Reference> = {
  tachi: {
    title: "TACHI",
    eyebrow: "Kihon 01 · Stances",
    intro: "Highest level instructors consider stances as the most important element of kihon. A stance is very much like the foundation of a house, quick to crumble if it is weak. Stances were designed to lower one's center of gravity and thus improve stability. Without a solid stance, an individual cannot deliver a technique with maximum power, and one can easily be taken off balance. Shotokan stances usually tend to be longer and deeper than other styles of karate.",
    sections: [
      { title: "Outer Tension Stances", body: ["Outer tension stances involve a slight outward pressure of the knees and thighs. They require deep bending of the knees and therefore have the lowest center of gravity. Since these stances are very low, practice of them is very exhaustive on the leg muscles, thus making it an ideal training for these muscles. Outer tension stances are usually used in conjunction with large movements or long and medium range combat techniques.", "Hard styles of karate (like Shotokan) tend to practice these stances a great deal more than the other stances."], items: ["zenkutsu-dachi — front stance", "kokutsu-dachi — back stance", "kiba-dachi — horse stance (horse-riding stance)", "fudo-dachi (sochin-dachi) — immoveable stance (strength & calm stance)", "shiko-dachi — square stance"] },
      { title: "Inner Tension Stances", body: ["Inner tension stances require an inward pressure of the knees and thighs, and have a higher center of gravity. Although easier on the legs, the positions of the feet and knees can be quite awkward, hence these stances are usually more difficult to master. Since the focus of these stances is inward, they are ideal for developing ki, one's inner energy. Soft style practitioners tend to train these stances more often.", "Inner tension stances are considered as more advanced stances and are usually practiced in combination with smaller techniques that can be used in short range or close combat."], items: ["hangetsu-dachi — half-moon stance", "sanchin-dachi — hourglass stance (3 wars stance)", "nekoashi-dachi — cat stance (cat-leg stance)"] },
      { title: "Natural Stances", body: ["Natural stances, or shizen tai (natural body), include all of the stances performed from fairly natural positions. These stances maintain the body's center of gravity at its normal level, requiring little or no tension in the legs or bending of the knees. As such, they are very quickly and easily learned. Natural stances are used when bowing, resting, retreating, and joint locking.", "They are also often used when awaiting an attack since an individual is most likely going to be in some form of a natural position if ever attacked for real."], items: ["hachiji-dachi — stance (shape of 8 stance)", "uchi-hachiji-dachi — inward natural stance", "musubi-dachi — attention stance (united stance)", "heisoku-dachi — feet together stance (closed feet stance)", "renoji-dachi — L-stance (shape of re stance)", "teinoji-dachi — T-stance (shape of tei stance)", "heiko-dachi — parallel stance"] },
      { title: "Unstable Stances", body: ["Unstable stances include stances that leave the individual in a precarious position, actually worsening balance. They are usually performed either on one leg or with both feet very close together. They have very specific functions related to bunkai (applications training) and are not designed to be maintained for long periods of time.", "However, since these stances are unstable, they require a great deal of balance and are often practiced to help individuals to improve overall stability and coordination."], items: ["ashi dachi — leg stance", "tsuru-dachi (sagiashi-dachi) — crane stance (crane-leg stance)", "kosa-dachi — cross stance", "hizakutsu-dachi — knee bending stance", "hiza-dachi — one knee stance"] },
    ], next: "uke",
  },
  uke: { title: "UKE", eyebrow: "Kihon 02 · Blocks", intro: "Uke means receive. In karate, uke refers to blocking techniques. Blocks are traditionally used to defend against attack and avoid being hit. They are most commonly performed with the arms or hands, and usually precede a counter-attack. Although karate is a defensive martial art, many strikes can also be used as blocks and many blocks can be used as strikes.", sections: [
    { title: "Basic Closed-Hand Blocks", body: ["Basic blocks are the most common blocks. They are executed with a swinging motion of the arm (up, down, either side) with the fists closed. The point of contact is either the inner or outer forearm, usually closer to the wrist area. Since the entire length of the forearm can be used, they have a much greater safety margin and are the safest blocks to use, especially for a beginner."], items: ["age-uke — rising block", "soto-uke — outside block", "gedan-barai — down block (lower level sweep)", "uchi-uke — inside block"] },
    { title: "Open-Hand Blocks", body: ["Open-hand blocks are performed with the edge or back of the hand, not the arm. Since the hand is much smaller, these blocks have a very small safety margin and are not as common. Usually, open-hand blocks are followed by grabbing with the blocking hand, pulling the opponent off balance, followed by a counter-attack."], items: ["shuto-uke — knife-hand block (sword-hand block)", "tate-shuto-uke — vertical knife-hand block", "kake-uke — hooking block", "haishu-uke — backhand block", "tsukami-uke (koko-uke) — grasping block (tiger-mouth block)"] },
    { title: "Advanced Blocks", items: ["haiwan-uke — back-arm block", "nagashi-uke — flowing block", "osae-uke — pressing block", "sukui-uke — scooping block", "maki-otoshi-uke — rolling dropping block"] },
    { title: "Double-Hand Blocks", body: ["Blocks using both hands are usually only practiced in kata. They can be a single-hand block with the other hand touching or supporting it, two different blocks performed at the same time, or two of the same blocks delivered together."], items: ["morote-uke — double-hand block", "kosa-uke (juji-uke) — cross block (X-block)", "kakiwake-uke — wedge block (separating block)", "manji-uke — manji symbol block (swirling block, vortex block)", "bo-uke — staff block", "awase-uke — combined block", "hasami-uke — scissors block", "oshi-uke — pushing block"] },
  ], prev: "tachi", next: "tsuki" },
  tsuki: { title: "TSUKI", eyebrow: "Kihon 03 · Punches", intro: "The actual translation of the word tsuki is thrust. Technically, any thrusting technique can be labelled as tsuki. In karate, tsuki is the term used for punches. These attacks are traditionally delivered with the front two knuckles of the fist, called seiken (fore-fist).", sections: [
    { title: "Basic Punches", body: ["All basic punches are linear, requiring full extension of the arm. These punches have the longest range and tend to be the most powerful. Basic punches are easy to learn and simple to use. They are the most often used attack form in karate."], items: ["choku-zuki — straight punch", "oi-zuki — lunge punch", "gyaku-zuki — reverse punch", "kisami-zuki — jab punch"] },
    { title: "Advanced Punches", body: ["Advanced punches are usually, but not always, non-linear. Many of these punches have the elbow bent at various angles. Although generally not as strong as basic punches, they are more suitable for close range combat and working around an opponent's guard."], items: ["ura-zuki — inverted punch", "age-zuki — rising punch", "kage-zuki — hook punch", "mawashi-zuki — roundhouse punch", "tate-zuki — vertical punch", "uke-zuki — blocking punch"] },
    { title: "Double-Hand Punches", body: ["Double-hand punches are performed with both hands at the same time. Their obvious benefit is that two targets can be hit at the same time, although they are almost never used as an offensive attack."], items: ["morote-zuki — double-hand punch", "yama-zuki — mountain punch", "yumi-zuki — bow punch", "awase-zuki — combined punch (U-punch)", "heiko-zuki — parallel punch", "hasami-zuki — scissors punch"] },
    { title: "Fore-knuckle Punches & Spear-Hand", body: ["Fore-knuckle punches are performed with the middle knuckles of the fingers. Spear-hand techniques involve a thrusting motion with the tips of the fingers and require properly conditioned hands."], items: ["ippon-ken — one-knuckle fist", "nakadaka-ippon-ken — middle finger one-knuckle fist", "hiraken — flat fist", "ippon-nukite — one-finger spear-hand", "nihon-nukite — two finger spear-hand", "tate-nukite — vertical spear-hand", "hira-nukite — flat spear-hand"] },
  ], prev: "uke", next: "keri" },
  keri: { title: "KERI", eyebrow: "Kihon 04 · Kicks", intro: "Kicks include all attacks performed with the legs or feet. Since the muscles of the leg are much larger and stronger than the muscles of the arm, kicking techniques are generally more powerful than hand techniques. They also have a greater attack range. However, kicking does have its drawbacks: kicks tend to be slower and leave the karateka on only one leg, compromising balance.", sections: [
    { title: "Basic Kicks", body: ["Basic kicks are practiced most often in Shotokan. These kicks are standard and are practiced almost every class. They are usually learned right at the beginning of training and are fairly simple."], items: ["mae-geri — front kick", "yoko-geri-keage — side snap kick", "yoko-geri-kekomi — side thrust kick", "mawashi-geri — roundhouse kick"] },
    { title: "Advanced Kicks", body: ["Advanced kicks are practiced much less often due to their difficulty and risky nature. They require excellent speed, timing, balance and flexibility."], items: ["ushiro-geri — back kick", "ura-mawashi-geri — reverse roundhouse kick", "mikazuki-geri — crescent (moon) kick", "tobi-geri — jump kick"] },
    { title: "Advanced Leg Attacks", body: ["These advanced techniques are executed with the foot and are mainly used to damage an opponent's legs or break an assailant's balance. All targets are below hip level (gedan)."], items: ["fumi-komi — thrusting step (stomping kick)", "ashi-barai — foot sweep", "nami-gaeshi (nami-ashi-geri) — returning wave (wave-leg kick)"] },
    { title: "Non-Traditional Kicks", body: ["These kicks are not exactly mainstream Shotokan. Very few dojo will practice them and they cannot be found in Shotokan kata or traditional kumite."], items: ["ushiro-ura-mawashi-geri — spinning back reverse roundhouse kick", "ura-mikazuki-geri — reverse inside crescent kick", "kage-geri — hook kick", "otoshi-kakato-geri — dropping heel kick", "tsumasaki-geri — tip of toes kick", "sune-geri — shin kick", "kin-geri — groin kick", "naname-geri — oblique kick"] },
  ], prev: "tsuki", next: "uchi" },
  uchi: { title: "UCHI", eyebrow: "Kihon 05 · Strikes", intro: "Strikes can be quite diverse and are usually performed with different parts of the hand or arm. Each striking technique can impact a target from a multitude of directions and angles, making strikes a karateka's most versatile weapon. Strikes are most useful against smaller, more specific targets and require good accuracy.", sections: [
    { title: "Roundhouse Strikes", body: ["Roundhouse strikes, or mawashi-uchi, include all of the circular attacks. They travel in an arc towards their target and are useful for circumventing an opponent's guard."], items: ["kentsui-uchi — hammer-fist strike", "uraken-uchi — backfist strike", "shuto-uchi — sword-hand strike", "haito-uchi — ridge-hand strike", "teisho — palm-heel"] },
    { title: "Animal Strikes", body: ["These extremely advanced strikes are often neglected. They are most likely remnants of animal forms that stem from the influence of kung fu during the early years of karate's development. They occur only in very high-level kata."], items: ["keito — chicken-head", "seiryuto — ox-jaw (sabre strike)", "kakuto — crane-head", "kumade — bear-hand", "washide — eagle-hand"] },
    { title: "Smashing Techniques", body: ["Ate-waza are techniques usually delivered with the elbow or knee and are known as very powerful attacks. Knees and elbows are excellent tools for close range combat."], items: ["empi-uchi (empi-ate) — elbow strike (elbow smash)", "hiza-tsuchi (hiza-ate) — knee smash (knee kick)"] },
  ], prev: "keri" },
  beginner: { title: "BEGINNER KUMITE", eyebrow: "Kumite 01 · Beginner", intro: "Basic kumite training develops proper punching and blocking technique while teaching the karateka how to maintain proper distance while moving forwards and backwards.", sections: [
    { title: "Kihon-Gohon-Kumite", body: ["Basic five-step sparring is typically practiced by beginners. The attacker steps forward with jodan-oi-zuki five times in succession. The defender steps backwards five times using the appropriate block, usually jodan-age-uke, followed by a counter-attack, usually chudan-gyaku-zuki. The sequence is then repeated with chudan-oi-zuki as the attack and chudan-soto-uke as the defense.", "All stances, attacks, and blocks are performed in basic style. Five-step sparring is very useful in developing proper punching and blocking technique. Its main purpose is to teach the karateka how to maintain proper distance from the opponent while moving forwards and backwards."] },
    { title: "Kihon-Sanbon-Kumite", body: ["Basic three-step sparring is almost exactly the same as five-step sparring except that the number of steps has been reduced to three. Three-step sparring takes up less time and space than five-step and is generally considered more efficient. It still teaches basic punching and blocking technique and trains the student to maintain proper distance while moving."] },
  ], next: "intermediate" },
  intermediate: { title: "INTERMEDIATE KUMITE", eyebrow: "Kumite 02 · Intermediate", intro: "Intermediate kumite introduces one-step and semi-free sparring while developing timing, body shifting and counter-attacking skills.", sections: [
    { title: "Kihon-Ippon-Kumite", body: ["Basic one-step sparring is normally taught at the beginner and intermediate levels. The attacker may use only one attack with one step. Many different attack forms can be used, such as various strikes and kicks, but only one at a time. After each single attack, both opponents must restart.", "It is at this stage of kumite where the defender learns tai sabaki, or body shifting. This occurs when the karateka shifts off the axis of attack, making the block almost superfluous, and then delivers a counter-attack."] },
    { title: "Jiyu-Ippon-Kumite", body: ["Freestyle one-step sparring, also known as semi-free sparring, is similar to basic one-step sparring, except that both participants start in jiyu-kamae (freestyle position). After each attack and counter-attack, the participants return to jiyu-kamae. Sometimes more than one counter-attack is executed. Jiyu-ippon is usually taught to intermediate and advanced karateka."] },
  ], prev: "beginner", next: "advanced" },
  advanced: { title: "ADVANCED KUMITE", eyebrow: "Kumite 03 · Advanced", intro: "Advanced kumite continues from basic and one-step sparring toward free movement, timing and application.", sections: [
    { title: "Advanced Training", body: ["Advanced kumite develops the ability to combine attacks, blocks, movement and counter-attacks under increasingly free conditions. The emphasis is on timing, distance, control and adapting technique to the opponent."] },
  ], prev: "intermediate" },
};

const kataTitles: Record<string, string> = { "heian-shodan": "HEIAN SHODAN", "heian-nidan": "HEIAN NIDAN", "heian-sandan": "HEIAN SANDAN", "heian-yondan": "HEIAN YONDAN", "heian-godan": "HEIAN GODAN", "tekki-shodan": "TEKKI SHODAN", "tekki-nidan": "TEKKI NIDAN", "tekki-sandan": "TEKKI SANDAN", "bassai-dai": "BASSAI DAI", "kanku-dai": "KANKU DAI", jion: "JION", empi: "EMPI", jitte: "JITTE", gankaku: "GANKAKU", hangetsu: "HANGETSU", "kanku-sho": "KANKU SHO", "bassai-sho": "BASSAI SHO", chinte: "CHINTE", nijushiho: "NIJUSHIHO", sochin: "SOCHIN", unsu: "UNSU", "gojushiho-sho": "GOJUSHIHO SHO", "gojushiho-dai": "GOJUSHIHO DAI", meikyo: "MEIKYO", wankan: "WANKAN", jiin: "JIIN", "taikyoku-shodan": "TAIKYOKU SHODAN", "taikyoku-nidan": "TAIKYOKU NIDAN", "taikyoku-sandan": "TAIKYOKU SANDAN", "ten-no-kata": "TEN NO KATA" };

export function ReferencePage({ kind, slug }: { kind: string; slug: string }) {
  const key = slug.toLowerCase();
  const data = references[key];
  const kata = kind === "kata";
  const title = kata ? kataTitles[key] || slug.replaceAll("-", " ").toUpperCase() : data?.title || slug.toUpperCase();
  const eyebrow = kata ? `Kata · ${title}` : data?.eyebrow || `${kind} reference`;
  const content = data || { title, eyebrow, intro: `This is the ${title} reference page, rebuilt inside Dhanurveda with the same reference structure and terminology.`, sections: [{ title: "Training Reference", body: ["This page is part of the Dhanurveda karate library. The external reference is no longer opened; navigation stays inside our site."] }] };
  const all = useMemo(() => Object.keys(references), []);
  const nextKey = content.next || all[(all.indexOf(key) + 1) % all.length];
  const prevKey = content.prev || all[(all.indexOf(key) - 1 + all.length) % all.length];

  return <div className="min-h-screen bg-ink text-ivory">
    <header className="sticky top-0 z-30 border-b border-line/80 bg-ink/90 px-5 py-4 backdrop-blur-xl md:px-10">
      <div className="mx-auto flex max-w-7xl items-center justify-between gap-6"><a href="/karate/#karate-library" className="flex items-center gap-3 text-[10px] uppercase tracking-[0.25em] text-ivory/55 hover:text-gold"><ArrowLeft size={14}/> Back to library</a><span className="font-mono text-[9px] uppercase tracking-[0.25em] text-gold/70">Dhanurveda / Karate reference</span></div>
    </header>
    <main className="mx-auto max-w-7xl px-5 py-16 md:px-10 md:py-24">
      <div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><div><p className="text-[10px] uppercase tracking-[0.35em] text-gold">{eyebrow}</p><div className="mt-6 flex h-14 w-14 items-center justify-center border border-gold/40 text-gold"><BookOpen size={20}/></div></div><div><h1 className="font-display text-7xl leading-[.78] tracking-tight md:text-[10rem]">{title}</h1><p className="mt-8 max-w-3xl text-base leading-8 text-ivory/60">{content.intro}</p></div></div>
      <div className="mt-20 grid gap-5">{content.sections.map((section, i) => <section key={section.title} className="grid gap-8 border-t border-line py-10 md:grid-cols-[.35fr_1fr]"><div><span className="font-mono text-[10px] text-gold/70">{String(i + 1).padStart(2, "0")}</span><h2 className="mt-3 font-display text-3xl text-ivory md:text-4xl">{section.title}</h2></div><div>{section.body?.map((p) => <p key={p} className="mb-5 max-w-3xl text-sm leading-8 text-ivory/60">{p}</p>)}{section.items && <div className="mt-6 grid gap-px overflow-hidden border border-line bg-line sm:grid-cols-2">{section.items.map((item, j) => <div key={item} className="bg-char px-5 py-4 text-xs text-ivory/75"><span className="mr-3 font-mono text-[9px] text-gold/60">{String(j + 1).padStart(2, "0")}</span>{item}</div>)}</div>}</div></section>)}</div>
      <nav className="mt-12 grid gap-px bg-line md:grid-cols-2">{prevKey && <a href={`/karate/${kata ? "kata" : kind}/${prevKey}`} className="group bg-char p-6 hover:bg-char-2"><span className="text-[9px] uppercase tracking-[.25em] text-ivory/35">Previous</span><div className="mt-3 flex items-center justify-between font-display text-2xl text-ivory"><span>{kata ? kataTitles[prevKey] : references[prevKey]?.title}</span><ArrowLeft size={18} className="text-gold transition-transform group-hover:-translate-x-1"/></div></a>}{nextKey && <a href={`/karate/${kata ? "kata" : kind}/${nextKey}`} className="group bg-gold p-6 text-ink"><span className="text-[9px] uppercase tracking-[.25em] opacity-50">Next</span><div className="mt-3 flex items-center justify-between font-display text-2xl"><span>{kata ? kataTitles[nextKey] : references[nextKey]?.title}</span><ArrowRight size={18} className="transition-transform group-hover:translate-x-1"/></div></a>}</nav>
      <div className="mt-10 flex items-center gap-2 text-[9px] uppercase tracking-[.25em] text-ivory/25"><ChevronRight size={12}/> Internal Dhanurveda page · no external navigation</div>
    </main>
  </div>;
}
