import { ArrowLeft } from "lucide-react";

const movements = [
  ["1*", "oi-zuki", "lunge punch", "zenkutsu-dachi", "chudan", ""],
  ["2*", "oi-zuki", "lunge punch", "zenkutsu-dachi", "jodan", ""],
  ["3*", "gyaku-zuki", "reverse punch", "zenkutsu-dachi (or fudo-dachi)", "chudan", ""],
  ["4*", "gyaku-zuki", "reverse punch", "zenkutsu-dachi (or fudo-dachi)", "jodan", ""],
  ["5*", "gedan-barai & gyaku-zuki", "down block & reverse punch", "zenkutsu-dachi (or fudo-dachi)", "gedan / chudan", ""],
  ["6*", "uchi-uke & gyaku-zuki", "inside block & reverse punch", "zenkutsu-dachi (or fudo-dachi)", "chudan / chudan", ""],
  ["7*", "shuto-uke & shihon-tate-nukite", "knife-hand block & 4-finger vertical spear-hand", "kokutsu-dachi / zenkutsu-dachi", "chudan / chudan", ""],
  ["8*", "shuto-barai & gyaku-zuki", "knife-hand sweep & reverse punch", "kokutsu-dachi (fudo) / zenkutsu-dachi", "jodan / jodan", ""],
  ["9*", "age-uke & gyaku-zuki", "rising block & reverse punch", "zenkutsu-dachi (or fudo-dachi)", "jodan / chudan", ""],
  ["10*", "kentsui-uchi (soto-uke) & gyaku-zuki", "hammer-fist (outside block) & reverse punch", "zenkutsu-dachi (or fudo-dachi)", "jodan / chudan", ""],
];

const kataLinks = [
  ["Heian Shodan", "heian-shodan"], ["Heian Nidan", "heian-nidan"], ["Heian Sandan", "heian-sandan"], ["Heian Yondan", "heian-yondan"], ["Heian Godan", "heian-godan"],
  ["Tekki Shodan", "tekki-shodan"], ["Tekki Nidan", "tekki-nidan"], ["Tekki Sandan", "tekki-sandan"], ["Bassai Dai", "bassai-dai"], ["Kanku Dai", "kanku-dai"], ["Jion", "jion"], ["Empi", "empi"],
  ["Jitte", "jitte"], ["Gankaku", "gankaku"], ["Hangetsu", "hangetsu"], ["Kanku Sho", "kanku-sho"], ["Bassai Sho", "bassai-sho"], ["Chinte", "chinte"], ["Nijushiho", "nijushiho"], ["Sochin", "sochin"], ["Unsu", "unsu"], ["Gojushiho Sho", "gojushiho-sho"], ["Gojushiho Dai", "gojushiho-dai"], ["Meikyo", "meikyo"], ["Wankan", "wankan"], ["Jiin", "jiin"], ["Taikyoku Shodan", "taikyoku-shodan"], ["Taikyoku Nidan", "taikyoku-nidan"], ["Taikyoku Sandan", "taikyoku-sandan"], ["Ten No Kata", "ten-no-kata"],
];

export function TenNoKataPage() {
  return (
    <div className="min-h-screen bg-[#e9e2d3] text-[#111111]">
      <header className="sticky top-0 z-30 border-b border-[#bdb4a4] bg-[#e9e2d3]/95 px-5 py-4 backdrop-blur md:px-10"><div className="mx-auto flex max-w-[1180px] items-center justify-between gap-5"><a href="/karate/" className="inline-flex items-center gap-2 text-[0.65rem] font-bold uppercase tracking-[0.2em] hover:text-[#9b3d18]"><ArrowLeft size={14} /> Dhanurveda</a><a href="/karate/#kata" className="text-[0.65rem] font-bold uppercase tracking-[0.2em] hover:text-[#9b3d18]">Kata Library</a></div></header>
      <main className="mx-auto max-w-[1180px] px-5 pb-24 pt-10 md:px-10 md:pt-16">
        <div className="border-b border-[#bdb4a4] pb-8"><p className="mb-3 text-[0.65rem] font-bold uppercase tracking-[0.3em] text-[#9b3d18]">Kata 30 · Ten No Kata</p><h1 className="font-[var(--font-display)] text-5xl font-bold uppercase leading-[0.85] tracking-[-0.04em] md:text-8xl">Ten No Kata</h1></div>
        <section className="mx-auto max-w-[1080px] pt-8"><p className="font-serif text-[1rem] leading-[1.55] text-justify">It is generally accepted that <em>Ten no Kata</em> was created by Gigo Funakoshi as a simple training tool for beginners. <em>Ten</em> refers to "sky," "heaven," or "universe." The kata is usually translated as "Kata of the Universe," or "Kata of the Heavens," giving it an almost divine quality since perfection of basic technique has always been the ultimate goal of Shotokan karateka. <em>Ten no Kata</em> requires very little space and can be practiced almost anywhere by karateka of any age. It is not a kata in the traditional sense. It is divided into two parts, <em>Omote</em> (front) and <em>Ura</em> (back).</p><p className="mt-4 font-serif text-[1rem] leading-[1.55] text-justify"><em>Ten no Kata Omote</em> is more similar to <em>kihon</em> than kata. It consists of ten sets of techniques. The first four sets are punching attacks: <em>chudan-oi-zuki</em>, <em>jodan-oi-zuki</em>, <em>chudan-gyaku-zuki</em>, and <em>jodan-gyaku-zuki</em>. The following six sets are block/counter-attack combinations; three defenses against <em>chudan</em> and three for <em>jodan</em>. As with any kata, <em>Ten no Kata Omote</em> is practiced without a partner. All moves start from <em>hachiji-dachi</em> (natural stance). Each technique is performed first with the right side and then with the left side. Every attack and counter-attack must be accompanied by a <em>kiai</em>. Some instructors teach to <em>kiai</em> when blocking as well.</p><p className="mt-4 font-serif text-[1rem] leading-[1.55] text-justify"><em>Ten no Kata Ura</em> really isn't kata at all; it's actually <em>kihon-ippon-kumite</em> (basic one-step sparring). The six sets of block/counter maneuvers from <em>Ten no Kata Omote</em> are practiced with a partner. The opponent attacks with three sets of <em>chudan-oi-zuki</em> (remember to do both sides) and three sets of <em>jodan-oi-zuki</em>. The defender must then apply the appropriate defense.</p><p className="mt-4 font-serif text-[1rem] leading-[1.55] text-justify">The <em>Ten no Kata</em> reviewed on this website was taken from Gichin Funakoshi's book <em>Karate-Do Nyumon</em>. In his description of <em>Omote</em>, Funakoshi says to use the <em>fudo-dachi</em> stance for many of the blocks. However, when viewing the photos that accompany the book, this is clearly not the case as the karateka is obviously doing <em>zenkutsu-dachi</em> (or even <em>kokutsu-dachi</em>). Therefore, the chart below offers both options. Conforming to standard <em>kihon-ippon-kumite</em> requirements, any instructors who still teach <em>Ten no Kata</em> (and there aren't many of them) will usually use the <em>zenkutsu-dachi</em> rather than <em>fudo-dachi</em>. Since present day Shotokan karateka practice <em>kihon</em> and <em>kihon-ippon-kumite</em> regularly, <em>Ten no Kata</em> has become quite obsolete.</p></section>
        <section className="mt-12 overflow-x-auto"><table className="w-full min-w-[900px] border-collapse border border-[#777064] bg-[#d9ceb8] font-serif text-[0.78rem]"><thead><tr className="bg-[#cfc2aa] text-center font-bold">{['#','Technique','Translation','Stance','Target','Notes'].map(h=><th key={h} className="border border-[#777064] px-3 py-2">{h}</th>)}</tr></thead><tbody>{movements.map(row=><tr key={row[0]} className="hover:bg-[#e4dac7]">{row.map((cell,i)=><td key={i} className={`border border-[#777064] px-3 py-2 ${i===0?'text-center':''}`}>{cell}</td>)}</tr>)}</tbody></table></section>
        <section className="mt-12 border-t border-[#bdb4a4] pt-8"><div className="grid grid-cols-2 gap-2 md:grid-cols-5 lg:grid-cols-10">{kataLinks.map(([label,slug])=><a key={slug} href={`/karate/kata/${slug}`} className={`text-[0.6rem] uppercase tracking-[0.08em] underline underline-offset-2 hover:text-[#9b3d18] ${slug==='ten-no-kata'?'font-bold text-[#9b3d18]':''}`}>{label}</a>)}</div></section>
        <nav className="mt-10 flex items-center justify-between border-t border-[#bdb4a4] pt-7 text-[0.65rem] font-bold uppercase tracking-[0.18em]"><a href="/karate/kata/taikyoku-sandan" className="inline-flex items-center gap-2 hover:text-[#9b3d18]"><ArrowLeft size={14}/> Taikyoku Sandan</a><span className="text-[#8b8376]">End of Kata Library</span></nav>
      </main>
    </div>
  );
}
