import { ArrowLeft, ArrowRight, ArrowUpRight } from "lucide-react";

type Section = { number: string; title: string; description: string; techniques: [string, string][]; image: string; alt: string; label: string };

const sections: Section[] = [
  { number: "01", title: "Roundhouse Strikes", description: "Roundhouse strikes, or mawashi-uchi, include all of the circular attacks. Roundhouse strikes travel in an arc towards their target. In most cases, if the arc is travelling downwards toward the floor, the strike is referred to as tate (vertical), as in kentsui-tate-mawashi-uchi. If the arc moves in a sideways or horizontal motion, it is called yoko, as in uraken-yoko-mawashi-uchi. Keep in mind that some of the following techniques, especially teisho, can also be used in a linear manner, as in teisho-zuki. Because of their circular nature, mawashi-uchi are very useful for circumventing an opponent's guard.", techniques: [["kentsui-uchi", "hammer-fist strike"], ["uraken-uchi", "backfist strike"], ["shuto-uchi", "sword-hand strike"], ["haito-uchi", "ridge-hand strike (sword-ridge strike)"], ["teisho", "palm-heel"]], image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Uraken.svg", alt: "Uraken strike reference", label: "Roundhouse strike reference" },
  { number: "02", title: "Animal Strikes", description: "These extremely advanced strikes are often very neglected. These techniques are most likely remnants of the animal forms that stem from the influence of kung fu, during the early years of karate's development. They occur only in very high-level kata. Two of the strikes, kumade and kakuto, do not appear in any Shotokan kata at all. These attacks (or if used as blocks) are useful to strike an opponent's kyusho points, or vital areas.", techniques: [["keito", "chicken-head"], ["seiryuto", "ox-jaw (sabre strike)"], ["kakuto", "crane-head"], ["kumade", "bear-hand"], ["washide", "eagle-hand"]], image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Shuto.png", alt: "Hand strike reference", label: "Animal-form hand reference" },
  { number: "03", title: "Smashing Techniques", description: "These two techniques are often referred to as ate, or 'smashing' techniques. Ate-waza are techniques usually delivered with the elbow or knee and are known as very powerful attacks. They are not used to pinpoint small targets, but rather to shatter whatever their intended target may be. Although knee strikes come in a limited variety, elbow strikes can have a multitude of angles and directions. Knees and elbows are excellent tools for close range combat and are very popular in street self-defense.", techniques: [["empi-uchi (empi-ate)", "elbow strike (elbow smash)"], ["hiza-tsuchi (hiza-ate)", "knee smash (knee kick)"]], image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Empi.svg", alt: "Empi elbow strike reference", label: "Empi reference" },
];

const intro = "Strikes can be quite diverse and are usually performed with different parts of the hand or arm. Each striking technique can impact a target from a multitude of directions and angles, making strikes a karateka's most versatile weapon. Strikes are most useful against smaller, more specific targets and, as such, require good accuracy. Only those with a basic knowledge of human anatomy will find truly effective uses for striking techniques. They are extremely dangerous and should be practiced with utmost control. As mentioned previously, most of the striking techniques can also be quite effective as blocks as well. Uchi have been divided into 3 categories:";

function TechniqueList({ items }: { items: [string, string][] }) { return <div className="mt-8 border-t border-[#cfc6b5] pt-5"><p className="mb-4 text-[0.58rem] font-bold uppercase tracking-[0.25em] text-[#9b3d18]">Strike vocabulary</p>{items.map(([name, meaning]) => <div key={name} className="grid grid-cols-[minmax(0,.8fr)_minmax(0,1.2fr)] gap-5 border-b border-[#ded6c7] py-2 text-[.78rem] md:text-[.84rem]"><span className="font-serif italic">{name}</span><span className="text-[#555048]">{meaning}</span></div>)}</div>; }

export function UchiPage() { return <div className="min-h-screen bg-[#e9e2d3] text-[#111111]">
<header className="sticky top-0 z-30 border-b border-[#cfc6b5] bg-[#e9e2d3]/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1180px] items-center justify-between px-5 md:px-8"><a href="/karate/" className="group flex items-center gap-3 text-[.62rem] font-bold uppercase tracking-[.22em]"><ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-1"/>Dhanurveda</a><nav className="hidden items-center gap-6 text-[.58rem] font-bold uppercase tracking-[.2em] text-[#69635a] md:flex"><a href="/karate/kihon/tachi">Tachi</a><a href="/karate/kihon/uke">Uke</a><a href="/karate/kihon/tsuki">Tsuki</a><a href="/karate/kihon/keri">Keri</a><a href="/karate/kihon/uchi" className="text-[#9b3d18]">Uchi</a></nav><span className="text-[.58rem] font-bold uppercase tracking-[.2em] text-[#9b3d18]">Kihon 05</span></div></header>
<main>
<section className="border-b border-[#cfc6b5] px-5 pb-14 pt-16 md:px-8 md:pb-20 md:pt-24"><div className="mx-auto grid max-w-[1180px] gap-10 lg:grid-cols-[1.05fr_.95fr] lg:items-end"><div><p className="mb-5 text-[.62rem] font-bold uppercase tracking-[.32em] text-[#9b3d18]">Kihon 05 · Strikes</p><h1 className="font-[var(--font-display)] text-[clamp(4.5rem,13vw,10rem)] font-bold uppercase leading-[.78] tracking-[-.055em]">Uchi</h1><p className="mt-7 max-w-2xl font-serif text-[1rem] leading-[1.65] text-[#36322d] md:text-[1.08rem]">{intro}</p></div><div className="relative overflow-hidden border border-[#bfb5a4] bg-[#f0eadf] p-5"><div className="absolute left-0 top-0 h-1 w-20 bg-[#9b3d18]"/><div className="flex min-h-[280px] items-center justify-center"><div className="relative h-[260px] w-full overflow-hidden"><div className="absolute left-[10%] top-1/2 h-px w-[75%] -rotate-[24deg] bg-[#9b3d18]/50"/><div className="absolute left-[31%] top-[30%] h-16 w-[190px] rotate-[22deg] rounded-full border-2 border-[#111111]/70"/><div className="absolute right-[9%] top-[18%] font-[var(--font-display)] text-[7rem] font-bold leading-none text-[#9b3d18]/20">打</div><div className="absolute bottom-5 left-0 right-0 text-center font-serif text-lg italic">Angle · Accuracy · Control</div></div></div><div className="flex items-end justify-between border-t border-[#cfc6b5] pt-4"><div><p className="font-serif text-lg italic">Uchi</p><p className="text-[.56rem] font-bold uppercase tracking-[.2em] text-[#777067]">Striking techniques</p></div><a href="https://commons.wikimedia.org/" target="_blank" rel="noreferrer" className="text-[#9b3d18]"><ArrowUpRight className="h-4 w-4"/></a></div></div></div></section>
<section className="px-5 py-14 md:px-8 md:py-20"><div className="mx-auto grid max-w-[1180px] gap-10 border-b border-[#cfc6b5] pb-14 lg:grid-cols-[1fr_.45fr]"><p className="font-serif text-[.94rem] leading-[1.72] text-[#3f3a34] md:text-[1rem]">Striking techniques demand accuracy and control. Their versatility comes from the many surfaces of the hand and arm, and from the different directions and angles from which a target can be reached.</p><aside className="border-l-2 border-[#9b3d18] pl-6 font-serif text-xl italic leading-[1.45] text-[#4b453e]">Versatility without control is not technique.</aside></div></section>
<nav className="border-y border-[#cfc6b5] px-5 py-4 md:px-8"><div className="mx-auto flex max-w-[1180px] gap-2 overflow-x-auto pb-1">{sections.map(s=><a key={s.number} href={`#uchi-${s.number}`} className="shrink-0 border border-[#cfc6b5] px-4 py-2 text-[.56rem] font-bold uppercase tracking-[.18em] hover:border-[#9b3d18] hover:text-[#9b3d18]">{s.number} · {s.title}</a>)}</div></nav>
<section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1180px]"><div className="mb-12 flex items-end justify-between border-b border-[#cfc6b5] pb-5"><div><p className="text-[.58rem] font-bold uppercase tracking-[.25em] text-[#9b3d18]">The three families</p><h2 className="mt-2 font-[var(--font-display)] text-3xl font-bold uppercase tracking-[-.02em] md:text-5xl">The art of uchi</h2></div><span className="hidden text-[.55rem] font-bold uppercase tracking-[.2em] text-[#777067] md:block">Angle · timing · precision</span></div><div className="space-y-16 md:space-y-24">{sections.map(s=><article key={s.number} id={`uchi-${s.number}`} className="scroll-mt-24 border-t-2 border-[#111111] pt-7"><div className="grid gap-8 lg:grid-cols-[90px_1fr_300px] lg:gap-10"><div><span className="font-[var(--font-display)] text-4xl font-bold text-[#9b3d18]">{s.number}</span></div><div><h3 className="font-[var(--font-display)] text-3xl font-bold uppercase leading-none tracking-[-.02em] md:text-4xl">{s.title}</h3><p className="mt-6 font-serif text-[.94rem] leading-[1.72] text-[#3f3a34] md:text-[1rem]">{s.description}</p><TechniqueList items={s.techniques}/></div><div className="border border-[#cfc6b5] bg-[#f0eadf] p-4"><div className="flex h-[240px] items-center justify-center overflow-hidden"><img src={s.image} alt={s.alt} className="max-h-full max-w-full object-contain mix-blend-multiply" loading="lazy"/></div><div className="border-t border-[#cfc6b5] pt-3 text-[.56rem] font-bold uppercase tracking-[.16em] text-[#716a61]">{s.label} · reference diagram</div></div></div></article>)}</div></div></section>
<section className="border-t border-[#cfc6b5] px-5 py-12 md:px-8"><div className="mx-auto flex max-w-[1180px] flex-col gap-5 md:flex-row md:items-center md:justify-between"><a href="/karate/kihon/keri" className="group inline-flex items-center gap-3 text-[.62rem] font-bold uppercase tracking-[.2em]"><ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-1"/>Previous · Keri</a><span className="text-[.55rem] font-bold uppercase tracking-[.2em] text-[#777067]">Discipline builds freedom</span><a href="/karate/" className="group inline-flex items-center gap-3 text-[.62rem] font-bold uppercase tracking-[.2em] text-[#9b3d18]">Back to Dhanurveda<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1"/></a></div></section>
</main></div>; }
