import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowUpRight } from "lucide-react";
import { PageShell, Section } from "@/components/page-shell";
import { Reveal, SectionHeading } from "@/components/reveal";
import { ClipReveal, HorizontalRail, Parallax } from "@/components/motion";
import { Lightbox } from "@/components/lightbox";

export type ProjectDetailData = {
  title: string; kicker: string; hero: ImageItem; facts: [string,string][];
  brief: string[]; approach: string[]; approachImage: ImageItem;
  material: string[]; materialImage: ImageItem; gallery: ImageItem[]; detailImages: ImageItem[];
  outcome: string[]; outcomeFacts: [string,string][]; technical: { label:string; value:string }[];
  related: RelatedProject[];
};
export type ImageItem = { src:string; alt:string; label?:string };
export type RelatedProject = { category:string; title:string; client:string; year:string; location:string; area:string; href:string; image:ImageItem; description:string };

export function ProjectDetailPage({ data }: { data: ProjectDetailData }) {
  const [lightbox, setLightbox] = useState<number | null>(null);
  const allImages = [...data.gallery, ...data.detailImages];
  return <PageShell>
    <section className="mx-auto max-w-[1600px] px-4 pb-10 pt-28 sm:px-8 lg:px-10 lg:pt-36">
      <Reveal variant="text" as="p" className="text-[0.62rem] uppercase tracking-[0.4em] text-champagne">{data.kicker}</Reveal>
      <Reveal variant="up" delay={80}><h1 className="mt-6 max-w-6xl font-display text-[2.8rem] leading-[0.92] text-foreground sm:text-7xl lg:text-[7.5rem]">{data.title}</h1></Reveal>
    </section>
    <ClipReveal className="mx-auto max-w-[1600px] px-4 sm:px-8 lg:px-10"><Parallax className="aspect-[16/10] w-full border border-border lg:aspect-[21/9]" amount={70}><img src={data.hero.src} alt={data.hero.alt} className="h-full w-full object-cover" /></Parallax></ClipReveal>
    <Section className="lg:py-20"><p className="text-[0.62rem] uppercase tracking-[0.34em] text-champagne">Project facts</p><dl className="mt-8 grid gap-px border-t border-border sm:grid-cols-2 lg:grid-cols-4">{data.facts.map(([label,value],i)=><Reveal key={label} variant="row" delay={i*40} className="border-b border-border py-6 pr-6"><dt className="text-[0.6rem] uppercase tracking-[0.24em] text-muted-foreground">{label}</dt><dd className="mt-2 font-display text-lg leading-snug text-foreground">{value}</dd></Reveal>)}</dl></Section>
    <Section className="border-t border-border"><div className="grid gap-10 lg:grid-cols-[0.9fr_1.4fr] lg:gap-20"><SectionHeading eyebrow="Introduction" title="The brief"/><div className="space-y-6">{data.brief.map((p,i)=><Reveal key={i} variant="up" delay={i*90}><p className={i===0?"font-display text-2xl leading-snug text-foreground lg:text-3xl":"text-sm leading-relaxed text-muted-foreground lg:text-base"} dangerouslySetInnerHTML={{__html:p}}/></Reveal>)}</div></div></Section>
    <Section><div className="grid gap-12 lg:grid-cols-2 lg:gap-20"><div><SectionHeading eyebrow="Approach" title="How it was built"/><div className="mt-8 space-y-6">{data.approach.map((p,i)=><Reveal key={i} variant="up" delay={i*80}><p className="text-sm leading-relaxed text-muted-foreground lg:text-base" dangerouslySetInnerHTML={{__html:p}}/></Reveal>)}</div></div><Reveal variant="right" delay={120}><div className="aspect-[4/3] overflow-hidden border border-border metal-sheen"><img src={data.approachImage.src} alt={data.approachImage.alt} loading="lazy" className="h-full w-full object-cover"/></div></Reveal></div></Section>
    <Section className="border-t border-border"><div className="grid gap-12 lg:grid-cols-2 lg:gap-20"><Reveal variant="left"><div className="aspect-[4/3] overflow-hidden border border-border metal-sheen"><img src={data.materialImage.src} alt={data.materialImage.alt} loading="lazy" className="h-full w-full object-cover"/></div></Reveal><div><SectionHeading eyebrow="Material & surface" title="The finish story"/><div className="mt-8 space-y-6">{data.material.map((p,i)=><Reveal key={i} variant="up" delay={i*80}><p className="text-sm leading-relaxed text-muted-foreground lg:text-base" dangerouslySetInnerHTML={{__html:p}}/></Reveal>)}</div></div></div></Section>
    <Section><SectionHeading eyebrow="Gallery" title="Project gallery"/><p className="mt-4 text-xs uppercase tracking-[0.24em] text-muted-foreground">{String(data.gallery.length).padStart(2,"0")} images — click to enlarge</p><HorizontalRail className="mt-10" itemClassName="w-[80vw] sm:w-[46vw] lg:w-[32vw]">{data.gallery.map((image,i)=><button key={i} type="button" onClick={()=>setLightbox(i)} data-cursor="Explore" className="group block w-full text-left"><div className="aspect-[4/3] overflow-hidden border border-border metal-sheen"><img src={image.src} alt={image.alt} loading="lazy" className="h-full w-full object-cover transition-transform duration-[1200ms] group-hover:scale-105"/></div><p className="mt-3 flex items-center justify-between gap-4 text-[0.6rem] uppercase tracking-[0.18em] text-muted-foreground"><span className="truncate">{image.label}</span><span className="shrink-0 tabular-nums text-champagne">{String(i+1).padStart(2,"0")} / {String(data.gallery.length).padStart(2,"0")}</span></p></button>)}</HorizontalRail></Section>
    <Section className="border-t border-border lg:py-20"><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{data.detailImages.map((image,i)=><Reveal key={i} variant="up" delay={(i%4)*80}><button type="button" onClick={()=>setLightbox(data.gallery.length+i)} data-cursor="Explore" className="block w-full"><div className="aspect-square overflow-hidden border border-border metal-sheen"><img src={image.src} alt={image.alt} loading="lazy" className="h-full w-full object-cover"/></div></button></Reveal>)}</div></Section>
    <Section className="border-t border-border"><div className="grid gap-12 lg:grid-cols-[1.2fr_0.8fr] lg:gap-20"><div><SectionHeading eyebrow="Outcome" title="What was delivered"/><div className="mt-8 space-y-6">{data.outcome.map((p,i)=><Reveal key={i} variant="up" delay={i*80}><p className="text-sm leading-relaxed text-muted-foreground lg:text-base" dangerouslySetInnerHTML={{__html:p}}/></Reveal>)}</div></div><dl className="border-t border-border">{data.outcomeFacts.map(([label,value])=><div key={label} className="border-b border-border py-5"><dt className="text-[0.6rem] uppercase tracking-[0.24em] text-muted-foreground">{label}</dt><dd className="mt-2 text-sm text-foreground">{value}</dd></div>)}</dl></div></Section>
    <Section className="border-t border-border"><SectionHeading eyebrow="Technical" title="Specification"/><dl className="mt-10 grid gap-px border-t border-border sm:grid-cols-2">{data.technical.map(({label,value})=><div key={label} className="border-b border-border py-6 pr-6"><dt className="text-[0.6rem] uppercase tracking-[0.24em] text-muted-foreground">{label}</dt><dd className="mt-2 text-sm leading-relaxed text-foreground" dangerouslySetInnerHTML={{__html:value}}/></div>)}</dl></Section>
    <Section className="border-t border-border"><SectionHeading eyebrow="More work" title="Related projects"/><div className="mt-10 grid gap-6 lg:grid-cols-3">{data.related.map((project)=><article key={project.href} className="group border border-border"><Link to={project.href} className="block"><div className="aspect-[4/3] overflow-hidden"><img src={project.image.src} alt={project.image.alt} loading="lazy" className="h-full w-full object-cover transition-transform duration-1000 group-hover:scale-105"/></div><div className="p-6"><p className="text-[0.58rem] uppercase tracking-[0.24em] text-champagne">{project.category}</p><h3 className="mt-3 font-display text-2xl text-foreground">{project.title}</h3><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{project.description}</p><p className="mt-6 inline-flex items-center gap-2 text-[0.62rem] uppercase tracking-[0.2em] text-foreground">View project <ArrowUpRight className="size-3"/></p></div></Link></article>)}</div></Section>
    <Section className="border-t border-border"><div className="flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div><SectionHeading eyebrow="Start a project" title="Bring us the detail."/><p className="mt-6 max-w-2xl text-sm leading-relaxed text-muted-foreground">Send us the drawings, the finish you have in mind, or just a photograph of a surface you like. We will come back with samples.</p></div><Link to="/contact" className="inline-flex items-center gap-2 border border-foreground px-6 py-4 text-[0.62rem] uppercase tracking-[0.2em] text-foreground">Start a project <ArrowUpRight className="size-4"/></Link></div></Section>
    {lightbox !== null && <Lightbox images={allImages.map(i=>({src:i.src,alt:i.alt}))} index={lightbox} onClose={()=>setLightbox(null)} onIndexChange={setLightbox}/>} 
  </PageShell>;
}
