import { motion } from "motion/react";
import { useState } from "react";
const IMG=["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=90","https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=90","https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=90"];
const F=({children}:{children:React.ReactNode})=><div className="relative mx-4 overflow-hidden border border-white/10 bg-[#11110f] md:mx-10">{children}</div>; const K=({children}:{children:React.ReactNode})=><p className="text-[9px] uppercase tracking-[.3em] text-white/40">{children}</p>;

export function ScrollTypography(){return <F><div className="relative min-h-[560px] overflow-hidden bg-[#0b0b0a] p-8 md:p-14"><K>49 / Scroll Typography</K><div className="mt-20 space-y-3"><motion.p whileInView={{x:[-80,0],opacity:[0,1]}} transition={{duration:.7}} className="font-serif text-[10vw] leading-[.8] text-white">SURFACE</motion.p><motion.p whileInView={{x:[80,0],opacity:[0,1]}} transition={{duration:.7}} className="ml-[12%] font-serif text-[10vw] leading-[.8] text-white/25">BECOMES</motion.p><motion.p whileInView={{x:[-80,0],opacity:[0,1]}} transition={{duration:.7}} className="font-serif text-[10vw] leading-[.8] text-white">SPACE.</motion.p></div></div></F>}

export function VariableWeightTypography(){return <F><div className="flex min-h-[520px] items-center bg-[#151512] p-8 md:p-14"><motion.h2 whileHover={{fontWeight:900}} transition={{duration:.4}} className="font-serif text-[11vw] leading-[.8] text-white" style={{fontWeight:300}}>MATERIAL<br/>INTELLIGENCE</motion.h2></div></F>}

export function ImageFilledTypography(){return <F><div className="relative flex h-[520px] items-center justify-center overflow-hidden bg-[#0b0b0a]"><img src={IMG[1]} className="absolute inset-0 h-full w-full object-cover opacity-40" alt="Typography material"/><h2 className="relative font-serif text-[13vw] leading-[.75] text-white mix-blend-screen">PVD<br/>SURFACES</h2></div></F>}

export function TextLoop(){const [i,setI]=useState(0);const words=["stainless steel","PVD finish","architecture","precision"];return <F><div className="flex min-h-[420px] items-center justify-center bg-[#0d0d0c] p-8 text-center"><div><K>50 / Text Loop</K><h2 className="mt-5 font-serif text-6xl text-white">Built for <motion.span key={i} initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="inline-block">{words[i]}</motion.span>.</h2><button onClick={()=>setI((i+1)%words.length)} className="mt-10 border border-white/20 px-5 py-3 text-[9px] uppercase tracking-[.2em] text-white">Change material</button></div></div></F>}

export function MagneticMenu(){const [open,setOpen]=useState(false);return <F><div className="relative h-[520px] bg-[#0b0b0a] p-8"><button onClick={()=>setOpen(v=>!v)} className="relative z-30 border border-white/20 px-5 py-3 text-[9px] uppercase tracking-[.2em] text-white">{open?"Close":"Menu"}</button><motion.div initial={false} animate={{clipPath:open?"circle(150% at 0 0)":"circle(0% at 0 0)"}} transition={{duration:.7}} className="absolute inset-0 z-20 bg-[#171714] p-8 pt-32"><div className="space-y-4 font-serif text-6xl text-white"><p>Projects</p><p>Materials</p><p>Capabilities</p><p>Contact</p></div></motion.div><div className="absolute bottom-8 left-8"><K>51 / Expanding Navigation</K><h2 className="mt-4 font-serif text-5xl text-white">A menu that behaves like a spatial reveal.</h2></div></div></F>}

export function FocusCards(){const [active,setActive]=useState<number|null>(null);return <F><div className="grid min-h-[560px] gap-3 bg-[#0b0b0a] p-6 md:grid-cols-3">{IMG.map((src,i)=><motion.button key={src} onPointerEnter={()=>setActive(i)} onPointerLeave={()=>setActive(null)} animate={{opacity:active===null||active===i?1:.3,scale:active===i?1.02:1}} className="relative h-[430px] overflow-hidden"><img src={src} className="h-full w-full object-cover" alt="Focus project"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent"/><span className="absolute bottom-6 left-6 font-serif text-3xl text-white">Focus {i+1}</span></motion.button>)}</div></F>}

export function StickySectionNav(){const [active,setActive]=useState(0);return <F><div className="relative min-h-[560px] bg-[#11110f] p-8 md:p-14"><div className="sticky top-8 z-10 flex w-fit gap-2 rounded-full border border-white/10 bg-black/60 p-1 backdrop-blur">{["Material","Projects","Process"].map((x,i)=><button key={x} onClick={()=>setActive(i)} className={`rounded-full px-4 py-2 text-[9px] uppercase tracking-widest ${active===i?"bg-white text-black":"text-white/40"}`}>{x}</button>)}</div><motion.div key={active} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="mt-20 max-w-3xl"><K>52 / Sticky Section Navigation</K><h2 className="mt-5 font-serif text-7xl text-white">{["Material intelligence.","Projects with presence.","Precision from drawing to installation."][active]}</h2></motion.div></div></F>}

export function ImageSlider(){const [i,setI]=useState(0);return <F><div className="relative h-[600px]"><img src={IMG[i]} className="h-full w-full object-cover" alt="Image slider"/><div className="absolute inset-x-8 bottom-8 flex items-center justify-between"><div><K>53 / Image Slider</K><p className="mt-2 font-serif text-4xl text-white">Project {i+1}</p></div><div className="flex gap-2">{IMG.map((_,n)=><button key={n} onClick={()=>setI(n)} className="h-1 w-12 bg-white/30"><span className="block h-full bg-white" style={{width:i===n?"100%":"0"}}/></button>)}</div></div></div></F>}

export function AnimatedTabs(){const [active,setActive]=useState(0);const tabs=["Material","Fabrication","Installation"];return <F><div className="min-h-[480px] bg-[#0c0c0b] p-8 md:p-14"><K>54 / Animated Tabs</K><div className="mt-10 flex border-b border-white/10">{tabs.map((t,i)=><button key={t} onClick={()=>setActive(i)} className="relative px-6 py-4 text-[9px] uppercase tracking-[.2em] text-white/50">{t}{active===i&&<motion.span layoutId="tab" className="absolute inset-x-0 bottom-0 h-px bg-white"/>}</button>)}</div><motion.div key={active} initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="mt-16"><h2 className="font-serif text-6xl text-white">{tabs[active]}</h2><p className="mt-5 max-w-lg text-sm leading-6 text-white/40">A reusable editorial tab pattern for explaining the STEELX process without turning it into a dashboard.</p></motion.div></div></F>}

export function AnimatedModal(){const [open,setOpen]=useState(false);return <F><div className="flex h-[450px] items-center justify-center bg-[#0b0b0a]"><button onClick={()=>setOpen(true)} className="border border-white/20 px-6 py-4 text-[9px] uppercase tracking-[.2em] text-white">Open project detail</button>{open&&<div className="absolute inset-0 z-30 flex items-center justify-center bg-black/70 p-6 backdrop-blur-sm" onClick={()=>setOpen(false)}><motion.div initial={{scale:.9,opacity:0}} animate={{scale:1,opacity:1}} onClick={e=>e.stopPropagation()} className="grid max-w-4xl overflow-hidden bg-[#171714] md:grid-cols-2"><img src={IMG[0]} className="h-80 w-full object-cover md:h-full" alt="Project modal"/><div className="p-8"><K>55 / Project Detail</K><h2 className="mt-4 font-serif text-5xl text-white">Nikhil Gupta Residence</h2><p className="mt-5 text-sm leading-6 text-white/40">Material palette, architectural application and installation notes.</p><button onClick={()=>setOpen(false)} className="mt-10 border border-white/20 px-5 py-3 text-[9px] uppercase tracking-widest text-white">Close</button></div></motion.div></div>}</div></F>}

export function InfiniteMaterialMarquee(){return <F><div className="flex h-[360px] items-center overflow-hidden bg-[#151512]"><motion.div animate={{x:[0,-1200]}} transition={{duration:18,repeat:Infinity,ease:"linear"}} className="whitespace-nowrap font-serif text-[12vw] text-white">CHAMPAGNE · BRONZE · GRAPHITE · BLACK · TITANIUM · CHAMPAGNE ·</motion.div></div></F>}

export function MovingBorderCTA(){return <F><div className="flex h-[380px] items-center justify-center bg-[#0b0b0a]"><div className="relative p-px"><motion.div animate={{rotate:360}} transition={{duration:5,repeat:Infinity,ease:"linear"}} className="absolute -inset-1 rounded-full bg-[conic-gradient(from_0deg,transparent,white,transparent)]"/><button className="relative rounded-full bg-[#11110f] px-10 py-5 text-[9px] uppercase tracking-[.25em] text-white">Start a material conversation</button></div></div></F>}

export function GlareProjectCard(){return <F><div className="flex min-h-[500px] items-center justify-center bg-[#0c0c0b] p-8"><motion.div whileHover={{rotateX:4,rotateY:-5}} className="group relative h-[390px] w-[300px] overflow-hidden [transform-style:preserve-3d]"><img src={IMG[2]} className="h-full w-full object-cover" alt="Glare project"/><motion.div initial={{x:"-120%"}} whileHover={{x:"120%"}} transition={{duration:.8}} className="absolute inset-y-0 w-1/3 skew-x-[-20deg] bg-white/20 blur-sm"/><div className="absolute bottom-0 inset-x-0 bg-gradient-to-t from-black/80 p-6 pt-24"><K>56 / Glare Card</K><p className="mt-2 font-serif text-3xl text-white">Reflective Residence</p></div></motion.div></div></F>}
