import { motion } from "motion/react";
import { useState } from "react";
const IMG=["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=90","https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=90","https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=90","https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1600&q=90","https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=90"];
const Frame=({children}:{children:React.ReactNode})=><div className="relative mx-4 overflow-hidden border border-white/10 bg-[#11110f] md:mx-10">{children}</div>;
const K=({children}:{children:React.ReactNode})=><p className="text-[9px] uppercase tracking-[.3em] text-white/40">{children}</p>;
const titles=["Residence 01","Hospitality 02","Retail 03","Facade 04","Interior 05"];

export function ArchitecturalProjectCarousel(){const [active,setActive]=useState(0);return <Frame><div className="relative h-[650px] bg-[#0b0b0a]"><div className="absolute left-7 top-7 z-20"><K>19 / Project Carousel</K><h2 className="mt-4 font-serif text-5xl text-white">Projects that move like architecture.</h2></div><div className="flex h-full items-center gap-5 overflow-hidden px-[14vw]">{IMG.map((src,i)=><motion.button key={src} onClick={()=>setActive(i)} animate={{scale:active===i?1.05:.88,opacity:active===i?1:.4,y:active===i?0:Math.abs(i-active)*18}} className="relative h-[410px] w-[290px] shrink-0 overflow-hidden text-left"><img src={src} className="h-full w-full object-cover" alt={titles[i]}/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black p-6 pt-28"><p className="font-serif text-3xl text-white">{titles[i]}</p></div></motion.button>)}</div></div></Frame>}

export function AppleProjectCards(){const [open,setOpen]=useState<number|null>(null);return <Frame><div className="relative min-h-[650px] bg-[#0b0b0a] p-7 md:p-12"><K>20 / Project Spotlight Cards</K><h2 className="mt-4 max-w-2xl font-serif text-5xl text-white">One project takes the whole frame.</h2><div className="mt-16 grid gap-4 md:grid-cols-3">{IMG.slice(0,3).map((src,i)=><motion.button layout onClick={()=>setOpen(open===i?null:i)} key={src} animate={{gridColumn:open===i?"span 3":"span 1"}} className="relative h-[360px] overflow-hidden text-left"><img src={src} className="h-full w-full object-cover" alt={titles[i]}/><div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent"/><div className="absolute bottom-6 left-6"><K>{String(i+1).padStart(2,"0")} / Project</K><p className="mt-2 font-serif text-3xl text-white">{titles[i]}</p></div></motion.button>)}</div></div></Frame>}

export function HorizontalProjectRail(){return <Frame><div className="relative h-[620px] overflow-hidden bg-[#0c0c0b]"><div className="absolute left-7 top-7 z-10"><K>21 / Horizontal Rail</K><h2 className="mt-4 font-serif text-5xl text-white">A continuous architectural archive.</h2></div><motion.div drag="x" dragConstraints={{left:-1000,right:100}} className="absolute left-0 top-1/2 flex -translate-y-1/2 cursor-grab gap-5 px-12 active:cursor-grabbing">{IMG.map((src,i)=><div key={src} className="h-[390px] w-[300px] shrink-0 overflow-hidden"><img src={src} className="h-full w-full object-cover" alt="Project archive"/><div className="absolute"/></div>)}</motion.div></div></Frame>}

export function ProjectImageReveal(){const [hover,setHover]=useState(false);return <Frame><div className="relative h-[620px] overflow-hidden" onPointerEnter={()=>setHover(true)} onPointerLeave={()=>setHover(false)}><img src={IMG[0]} className="h-full w-full object-cover" alt="Project reveal"/><motion.div animate={{x:hover?0:"-100%"}} transition={{duration:.8}} className="absolute inset-0 bg-[#151512] p-8 md:p-14"><K>22 / Image Reveal</K><h2 className="mt-5 max-w-xl font-serif text-6xl text-white">The project appears after the material.</h2><p className="mt-6 max-w-md text-sm leading-6 text-white/45">Hover the frame to reveal the completed architectural application.</p></motion.div></div></Frame>}

export function ProjectBeforeAfter(){const [p,setP]=useState(50);return <Frame><div className="relative h-[620px] overflow-hidden"><img src={IMG[1]} className="h-full w-full object-cover grayscale" alt="Before"/><div className="absolute inset-y-0 left-0 overflow-hidden" style={{width:`${p}%`}}><img src={IMG[4]} className="h-full w-full object-cover" alt="After"/></div><input aria-label="Compare project" type="range" min="0" max="100" value={p} onChange={e=>setP(+e.target.value)} className="absolute bottom-8 left-8 right-8"/><div className="absolute left-7 top-7"><K>23 / Before + After</K><h2 className="mt-4 font-serif text-5xl text-white">See the intervention, not just the result.</h2></div></div></Frame>}

export function ProjectSpotlight(){const [active,setActive]=useState(0);return <Frame><div className="grid min-h-[620px] md:grid-cols-[.65fr_1.35fr] bg-[#0b0b0a]"><div className="p-8 md:p-12"><K>24 / Project Spotlight</K><h2 className="mt-5 font-serif text-5xl text-white">Material decisions, project by project.</h2><div className="mt-12 space-y-2">{titles.map((t,i)=><button key={t} onClick={()=>setActive(i)} className={`block w-full border-b border-white/10 py-4 text-left text-[10px] uppercase tracking-[.2em] ${active===i?"text-white":"text-white/35"}`}>{t}</button>)}</div></div><motion.img key={active} initial={{opacity:0,scale:1.04}} animate={{opacity:1,scale:1}} src={IMG[active]} className="min-h-[500px] h-full w-full object-cover" alt="Project spotlight"/></div></Frame>}

export function ProjectTimeline(){return <Frame><div className="relative min-h-[620px] bg-[#0d0d0c] p-8 md:p-14"><K>25 / Project Timeline</K><h2 className="mt-5 max-w-2xl font-serif text-5xl text-white">From first drawing to installed surface.</h2><div className="mt-20 grid gap-8 md:grid-cols-5">{["Brief","Material","Prototype","Fabricate","Install"].map((x,i)=><motion.div whileHover={{y:-8}} key={x} className="border-t border-white/20 pt-5"><p className="text-[10px] text-white/30">0{i+1}</p><p className="mt-3 font-serif text-2xl text-white">{x}</p><p className="mt-3 text-xs leading-5 text-white/40">A precise project checkpoint where surface and architecture meet.</p></motion.div>)}</div></div></Frame>}

export function FullscreenProjectTransition(){const [active,setActive]=useState(0);return <Frame><div className="relative h-[650px] overflow-hidden"><motion.img key={active} initial={{scale:1.15,opacity:0}} animate={{scale:1,opacity:1}} transition={{duration:1}} src={IMG[active]} className="h-full w-full object-cover" alt="Fullscreen project"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 to-transparent"/><div className="absolute bottom-8 left-8"><K>26 / Fullscreen Transition</K><h2 className="mt-3 font-serif text-5xl text-white">{titles[active]}</h2><div className="mt-5 flex gap-2">{IMG.map((_,i)=><button key={i} onClick={()=>setActive(i)} className="h-1 w-10 bg-white/30"><span className="block h-full bg-white" style={{width:active===i?"100%":"0%"}}/></button>)}</div></div></div></Frame>}

export function ProjectMap(){return <Frame><div className="relative h-[620px] overflow-hidden bg-[#11110f] p-8 md:p-12"><K>27 / Project Map</K><h2 className="mt-4 font-serif text-5xl text-white">A project network, not a grid.</h2><div className="absolute inset-x-10 bottom-12 top-48">{titles.map((t,i)=><motion.button whileHover={{scale:1.2}} key={t} className="absolute h-4 w-4 rounded-full border border-white bg-white/20" style={{left:`${15+i*18}%`,top:`${25+(i%2)*30}%`}}><span className="absolute left-5 top-0 whitespace-nowrap text-[9px] uppercase tracking-[.15em] text-white/50">{t}</span></motion.button>)}</div></div></Frame>}
