import { motion, useScroll, useTransform } from "motion/react";
import { useRef, useState } from "react";
const IMG=["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=90","https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=90","https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=90","https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1800&q=90"];
const F=({children}:{children:React.ReactNode})=><div className="relative mx-4 overflow-hidden border border-white/10 bg-[#11110f] md:mx-10">{children}</div>; const K=({children}:{children:React.ReactNode})=><p className="text-[9px] uppercase tracking-[.3em] text-white/40">{children}</p>;

export function StickyArchitecturalStory(){const ref=useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:["start end","end start"]});const y=useTransform(scrollYProgress,[0,1],[80,-80]);return <F><div ref={ref} className="relative min-h-[760px] bg-[#0c0c0b] p-8 md:p-14"><K>28 / Sticky Architectural Story</K><div className="mt-12 grid md:grid-cols-2"><div className="sticky top-20 h-fit"><h2 className="font-serif text-6xl text-white">Architecture changes when the surface changes.</h2></div><div className="space-y-20"><motion.img style={{y}} src={IMG[0]} className="h-[430px] w-full object-cover" alt="Architecture story"/><p className="max-w-md text-sm leading-7 text-white/45">A scroll narrative for explaining why material, proportion, light and fabrication belong in the same conversation.</p><img src={IMG[1]} className="h-[430px] w-full object-cover" alt="Architectural material"/></div></div></div></F>}

export function ParallaxBuilding(){const ref=useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:["start end","end start"]});const y=useTransform(scrollYProgress,[0,1],[100,-100]);return <F><div ref={ref} className="relative h-[650px] overflow-hidden"><motion.img style={{y,scale:1.2}} src={IMG[1]} className="absolute inset-x-0 top-[-10%] h-[120%] w-full object-cover" alt="Parallax building"/><div className="absolute inset-0 bg-black/25"/><div className="absolute bottom-8 left-8"><K>29 / Parallax Building</K><h2 className="mt-3 font-serif text-6xl text-white">Depth without spectacle.</h2></div></div></F>}

export function LayeredFacade(){const [active,setActive]=useState(0);return <F><div className="relative h-[650px] bg-[#0d0d0c]"><div className="absolute left-7 top-7 z-20"><K>30 / Layered Facade</K><h2 className="mt-4 font-serif text-5xl text-white">Peel the facade back.</h2></div>{[0,1,2,3].map(i=><motion.img key={i} onClick={()=>setActive(i)} animate={{x:(i-active)*34,y:(i-active)*18,scale:1-i*.045,opacity:i<active?.22:1}} src={IMG[i]} className="absolute left-1/2 top-1/2 h-[470px] w-[330px] -translate-x-1/2 -translate-y-1/2 cursor-pointer object-cover" style={{zIndex:10-i}} alt="Facade layer"/> )}</div></F>}

export function InteriorExteriorSplit(){const [p,setP]=useState(50);return <F><div className="relative h-[620px] overflow-hidden"><img src={IMG[2]} className="h-full w-full object-cover" alt="Exterior"/><div className="absolute inset-y-0 left-0 overflow-hidden" style={{width:`${p}%`}}><img src={IMG[3]} className="h-full w-full object-cover" alt="Interior"/></div><input type="range" min="0" max="100" value={p} onChange={e=>setP(+e.target.value)} className="absolute bottom-8 left-8 right-8"/><div className="absolute left-7 top-7"><K>31 / Interior + Exterior</K><h2 className="mt-4 font-serif text-5xl text-white">One material language, two worlds.</h2></div></div></F>}

export function MaterialCrossSection(){const [open,setOpen]=useState(false);return <F><div className="relative h-[650px] overflow-hidden bg-[#151512]"><div className="absolute inset-x-8 top-8"><K>32 / Material Cross-section</K><h2 className="mt-4 font-serif text-5xl text-white">See the assembly, not only the skin.</h2></div><div className="absolute bottom-12 left-1/2 w-[78%] -translate-x-1/2 space-y-2">{["Architectural substrate","Formed stainless steel","PVD coating","Protective finish","Installation interface"].map((x,i)=><motion.div key={x} animate={{x:open?i*16:0}} className="border border-white/15 bg-[#22221d] p-5 text-xs uppercase tracking-[.18em] text-white/60">{x}</motion.div>)}</div><button onClick={()=>setOpen(v=>!v)} className="absolute bottom-8 right-8 border border-white/20 px-5 py-3 text-[9px] uppercase tracking-[.2em] text-white">{open?"Flatten":"Explode"}</button></div></F>}

export function FacadeReveal(){const [p,setP]=useState(false);return <F><div className="relative h-[650px] overflow-hidden"><img src={IMG[0]} className="h-full w-full object-cover" alt="Facade"/><motion.div animate={{y:p?"-100%":0}} transition={{duration:.9}} className="absolute inset-0 bg-[#171714] p-8 md:p-14"><K>33 / Facade Reveal</K><h2 className="mt-5 max-w-xl font-serif text-6xl text-white">Reveal the building beneath the material study.</h2></motion.div><button onClick={()=>setP(v=>!v)} className="absolute bottom-8 right-8 border border-white/20 bg-black/40 px-5 py-3 text-[9px] uppercase tracking-[.2em] text-white">Reveal facade</button></div></F>}

export function ScrollThroughArchitecture(){const ref=useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:["start end","end start"]});const scale=useTransform(scrollYProgress,[0,.5,1],[.82,1,1.15]);return <F><div ref={ref} className="relative h-[700px] overflow-hidden bg-[#0b0b0a]"><motion.img style={{scale}} src={IMG[2]} className="absolute inset-0 h-full w-full object-cover" alt="Scroll through architecture"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-black/20"/><div className="absolute bottom-8 left-8"><K>34 / Scroll Through Architecture</K><h2 className="mt-3 font-serif text-6xl text-white">Scroll into the building.</h2></div></div></F>}

export function PerspectiveGrid(){return <F><div className="relative h-[620px] overflow-hidden bg-[#0d0d0c]"><div className="absolute inset-0 opacity-25" style={{backgroundImage:"linear-gradient(rgba(255,255,255,.16) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.16) 1px,transparent 1px)",backgroundSize:"70px 70px",transform:"perspective(500px) rotateX(62deg) scale(1.5)"}}/><div className="absolute left-7 top-7"><K>35 / Perspective Grid</K><h2 className="mt-4 max-w-xl font-serif text-5xl text-white">A technical layer for material intelligence.</h2></div><div className="absolute bottom-10 left-7 flex gap-10 text-[9px] uppercase tracking-[.2em] text-white/35"><span>Scale 1:50</span><span>Facade datum</span><span>Finish tolerance</span></div></div></F>}

export function ArchitecturalImageLens(){return <F><div className="relative h-[620px] overflow-hidden"><img src={IMG[3]} className="h-full w-full object-cover" alt="Architectural image lens"/><div className="absolute inset-0 bg-gradient-to-r from-black/40 to-transparent"/><div className="absolute bottom-8 left-8 max-w-xl"><K>36 / Architectural Image Lens</K><h2 className="mt-3 font-serif text-6xl text-white">Move from the whole building to the detail that defines it.</h2></div></div></F>}
