import { motion, useMotionValue, useSpring } from "motion/react";
import { useState } from "react";
const IMG=["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=90","https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=90","https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=90","https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1800&q=90"];
const F=({children}:{children:React.ReactNode})=><div className="relative mx-4 overflow-hidden border border-white/10 bg-[#11110f] md:mx-10">{children}</div>; const K=({children}:{children:React.ReactNode})=><p className="text-[9px] uppercase tracking-[.3em] text-white/40">{children}</p>;

export function MagneticNavigation(){const x=useMotionValue(0);const y=useMotionValue(0);const sx=useSpring(x,{stiffness:250,damping:18});const sy=useSpring(y,{stiffness:250,damping:18});return <F><div className="flex h-[420px] items-center justify-center bg-[#0c0c0b]"><motion.nav onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)*.12);y.set((e.clientY-r.top-r.height/2)*.12)}} onPointerLeave={()=>{x.set(0);y.set(0)}} style={{x:sx,y:sy}} className="flex gap-8 border border-white/10 bg-white/[.03] px-8 py-5 text-[10px] uppercase tracking-[.25em] text-white/70"><a href="#projects">Projects</a><a href="#materials">Materials</a><a href="#process">Process</a><a href="#contact">Contact</a></motion.nav></div></F>}

export function MaterialCursor(){const x=useMotionValue(0);const y=useMotionValue(0);const sx=useSpring(x,{stiffness:200,damping:20});const sy=useSpring(y,{stiffness:200,damping:20});return <F><div onPointerMove={e=>{x.set(e.nativeEvent.offsetX);y.set(e.nativeEvent.offsetY)}} className="relative h-[420px] overflow-hidden bg-[#141411]"><motion.div style={{x:sx,y:sy}} className="pointer-events-none absolute -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/30 px-5 py-3 text-[8px] uppercase tracking-[.25em] text-white">Inspect finish</motion.div><div className="absolute left-7 top-7"><K>37 / Material Cursor</K><h2 className="mt-4 font-serif text-5xl text-white">The cursor becomes part of the material system.</h2></div></div></F>}

export function FloatingProjectNavigator(){return <F><div className="relative h-[560px] bg-[#0b0b0a] p-8"><div className="absolute left-8 top-8"><K>38 / Floating Project Navigator</K><h2 className="mt-4 font-serif text-5xl text-white">Keep the archive within reach.</h2></div><div className="absolute bottom-8 left-1/2 flex -translate-x-1/2 gap-2 rounded-full border border-white/10 bg-black/70 p-2 backdrop-blur"><button className="rounded-full bg-white px-4 py-2 text-[9px] uppercase tracking-widest text-black">01</button>{[2,3,4,5].map(i=><button key={i} className="px-4 py-2 text-[9px] uppercase tracking-widest text-white/40">0{i}</button>)}</div></div></F>}

export function SplitHero(){return <F><div className="grid min-h-[650px] md:grid-cols-2"><div className="flex flex-col justify-end bg-[#151512] p-8 md:p-14"><K>39 / Split Hero</K><h2 className="mt-5 font-serif text-7xl leading-[.88] text-white">Surface is architecture.</h2><p className="mt-7 max-w-sm text-sm leading-6 text-white/45">A restrained editorial hero built around the material, not around interface chrome.</p></div><img src={IMG[0]} className="h-full min-h-[500px] w-full object-cover" alt="STEELX split hero"/></div></F>}

export function ImageDistortionHero(){const [p,setP]=useState({x:0,y:0});return <F><div onPointerMove={e=>setP({x:e.nativeEvent.offsetX/800-.5,y:e.nativeEvent.offsetY/600-.5})} className="relative h-[650px] overflow-hidden"><motion.img animate={{x:p.x*40,y:p.y*30,scale:1.08}} src={IMG[1]} className="h-full w-full object-cover" alt="Distorted hero"/><div className="absolute inset-0 bg-black/20"/><div className="absolute bottom-8 left-8"><K>40 / Image Distortion Hero</K><h2 className="mt-3 font-serif text-7xl text-white">Quiet motion. Heavy material.</h2></div></div></F>}

export function HorizontalScrollHero(){return <F><div className="relative h-[620px] overflow-hidden bg-[#0b0b0a]"><motion.div drag="x" dragConstraints={{left:-900,right:0}} className="flex h-full w-max cursor-grab items-center gap-5 px-10 active:cursor-grabbing">{IMG.map((src,i)=><div key={src} className="relative h-[450px] w-[520px] shrink-0"><img src={src} className="h-full w-full object-cover" alt="Horizontal hero"/><div className="absolute bottom-7 left-7"><K>STEELX / 0{i+1}</K><p className="mt-2 font-serif text-4xl text-white">Architectural surface</p></div></div>)}</motion.div><div className="absolute left-7 top-7"><K>41 / Horizontal Scroll Hero</K></div></div></F>}

export function EditorialTextReveal(){const [show,setShow]=useState(false);return <F><div className="flex min-h-[520px] items-center bg-[#11110f] p-8 md:p-16"><button onClick={()=>setShow(v=>!v)} className="text-left"><K>42 / Editorial Text Reveal</K><motion.h2 animate={{y:show?0:25,opacity:show?1:.5}} className="mt-5 max-w-5xl font-serif text-7xl leading-[.9] text-white">The finish should not decorate the architecture. It should complete it.</motion.h2><p className="mt-8 text-[9px] uppercase tracking-[.2em] text-white/30">Click to reveal / editorial transition</p></button></div></F>}

export function MaskedHeadline(){return <F><div className="relative flex h-[520px] items-center overflow-hidden bg-[#0b0b0a] p-8 md:p-14"><img src={IMG[2]} className="absolute inset-0 h-full w-full object-cover opacity-30" alt="Masked headline"/><h2 className="relative font-serif text-[11vw] leading-[.82] tracking-[-.06em] text-white">MATERIAL<br/>MATTERS.</h2></div></F>}

export function KineticProjectTitles(){return <F><div className="min-h-[520px] bg-[#0c0c0b] p-8 md:p-14"><K>43 / Kinetic Project Titles</K><div className="mt-16 space-y-1">{["Nikhil Gupta Residence","Private Villa","Boutique Hospitality","Corporate Lobby"].map((x,i)=><motion.p key={x} whileHover={{x:35}} className="cursor-default border-b border-white/10 py-5 font-serif text-5xl text-white/70 hover:text-white md:text-7xl">{x}<span className="ml-5 align-middle text-[9px] uppercase tracking-[.2em] text-white/25">0{i+1}</span></motion.p>)}</div></div></F>}

export function MagneticButton(){const x=useMotionValue(0);const y=useMotionValue(0);const sx=useSpring(x,{stiffness:300,damping:20});const sy=useSpring(y,{stiffness:300,damping:20});return <F><div className="flex h-[360px] items-center justify-center bg-[#11110f]"><motion.button style={{x:sx,y:sy}} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)*.25);y.set((e.clientY-r.top-r.height/2)*.25)}} onPointerLeave={()=>{x.set(0);y.set(0)}} className="rounded-full border border-white/25 px-10 py-5 text-[9px] uppercase tracking-[.25em] text-white">View projects</motion.button></div></F>}

export function DirectionAwareProjectCard(){const [side,setSide]=useState("top");return <F><div className="flex min-h-[500px] items-center justify-center bg-[#0b0b0a] p-8"><motion.div onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();const dx=e.clientX-r.left-r.width/2;const dy=e.clientY-r.top-r.height/2;setSide(Math.abs(dx)>Math.abs(dy)?(dx>0?"right":"left"):(dy>0?"bottom":"top"))}} whileHover={{scale:1.02}} className="relative h-[380px] w-[300px] overflow-hidden"><img src={IMG[3]} className="h-full w-full object-cover" alt="Direction aware project"/><div className="absolute inset-0 flex items-center justify-center bg-black/20"><span className="border border-white/30 px-4 py-2 text-[9px] uppercase tracking-[.2em] text-white">Enter from {side}</span></div></motion.div></div></F>}

export function ImageHoverPreview(){const [active,setActive]=useState<number|null>(null);return <F><div className="relative min-h-[500px] bg-[#0d0d0c] p-8 md:p-14"><K>44 / Image Hover Preview</K><div className="mt-14 space-y-2">{IMG.map((src,i)=><button key={src} onPointerEnter={()=>setActive(i)} className="group flex w-full items-center justify-between border-b border-white/10 py-5 text-left"><span className="font-serif text-4xl text-white/60 group-hover:text-white">Project {String(i+1).padStart(2,"0")}</span><span className="text-[9px] uppercase tracking-widest text-white/25">Preview</span></button>)}</div>{active!==null&&<motion.img initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} src={IMG[active]} className="pointer-events-none absolute right-10 top-1/2 h-64 w-48 -translate-y-1/2 object-cover" alt="Project preview"/>}</div></F>}

export function SmoothImageDisplacement(){const [p,setP]=useState(0);return <F><div className="relative h-[560px] overflow-hidden" onPointerMove={e=>setP(e.nativeEvent.offsetX/900-.5)}><motion.img animate={{x:p*50,scale:1.12}} transition={{type:"spring",stiffness:80,damping:18}} src={IMG[0]} className="h-full w-full object-cover" alt="Image displacement"/><div className="absolute left-7 top-7"><K>45 / Smooth Image Displacement</K><h2 className="mt-4 font-serif text-5xl text-white">Material follows your attention.</h2></div></div></F>}

export function DragPhysics(){const [x,setX]=useState(0);return <F><div className="relative h-[500px] overflow-hidden bg-[#0b0b0a]"><motion.div drag="x" dragConstraints={{left:-280,right:280}} dragElastic={.18} animate={{x}} onDragEnd={(_,info)=>setX(x+info.velocity.x*.08)} className="absolute left-1/2 top-1/2 h-[330px] w-[240px] -translate-x-1/2 -translate-y-1/2 cursor-grab overflow-hidden active:cursor-grabbing"><img src={IMG[2]} className="h-full w-full object-cover" alt="Drag physics project"/></motion.div><div className="absolute left-7 top-7"><K>46 / Drag Physics</K><h2 className="mt-4 font-serif text-5xl text-white">Drag the project through space.</h2></div></div></F>}

export function ScrollVelocityEffect(){return <F><div className="flex h-[500px] items-center overflow-hidden bg-[#12120f]"><motion.div animate={{x:[-400,400]}} transition={{duration:7,repeat:Infinity,ease:"linear"}} className="whitespace-nowrap font-serif text-[13vw] text-white/[.08]">STEELX · PVD · ARCHITECTURE · MATERIAL ·</motion.div><div className="absolute left-7 top-7"><K>47 / Scroll Velocity</K><h2 className="mt-4 font-serif text-5xl text-white">A slow-moving typographic atmosphere.</h2></div></div></F>}

export function PageTransitionPanel(){const [open,setOpen]=useState(false);return <F><div className="relative h-[520px] overflow-hidden bg-[#0c0c0b]"><motion.div animate={{x:open?"0%":"100%"}} transition={{duration:.8,ease:[.76,0,.24,1]}} className="absolute inset-y-0 right-0 w-full bg-[#171714] p-8 md:p-14"><K>48 / Page Transition</K><h2 className="mt-5 font-serif text-6xl text-white">Projects can enter like spaces.</h2></motion.div><button onClick={()=>setOpen(v=>!v)} className="absolute bottom-8 left-8 z-20 border border-white/20 px-5 py-3 text-[9px] uppercase tracking-[.2em] text-white">Open transition</button></div></F>}
