/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExhibitionsRouteImport } from './routes/exhibitions'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MaterialLightSpaceRouteImport } from './routes/material-light-space'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PvdSurfacesRouteImport } from './routes/pvd-surfaces'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SsDecorativeMeshPvdRouteImport } from './routes/ss-decorative-mesh-pvd'
import { Route as StainlessSteelDesignerSheetsRouteImport } from './routes/stainless-steel-designer-sheets'
import { Route as SteelCollectionRouteImport } from './routes/steel-collection'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as DesignerSheetsIndexRouteImport } from './routes/designer-sheets/index'
import { Route as DesignerSheetsEmbossedRouteImport } from './routes/designer-sheets/embossed'
import { Route as DesignerSheetsHairlineRouteImport } from './routes/designer-sheets/hairline'
import { Route as DesignerSheetsMirrorRouteImport } from './routes/designer-sheets/mirror'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as TagSlugRouteImport } from './routes/tag/$slug'
import { Route as DesignerSheetsFinishIndexRouteImport } from './routes/designer-sheets/$finish/index'
import { Route as DesignerSheetsFinishProductRouteImport } from './routes/designer-sheets/$finish/$product'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsRoute = ExhibitionsRouteImport.update({
  id: '/exhibitions',
  path: '/exhibitions',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialLightSpaceRoute = MaterialLightSpaceRouteImport.update({
  id: '/material-light-space',
  path: '/material-light-space',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PvdSurfacesRoute = PvdSurfacesRouteImport.update({
  id: '/pvd-surfaces',
  path: '/pvd-surfaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SsDecorativeMeshPvdRoute = SsDecorativeMeshPvdRouteImport.update({
  id: '/ss-decorative-mesh-pvd',
  path: '/ss-decorative-mesh-pvd',
  getParentRoute: () => rootRouteImport,
} as any)
const StainlessSteelDesignerSheetsRoute =
  StainlessSteelDesignerSheetsRouteImport.update({
    id: '/stainless-steel-designer-sheets',
    path: '/stainless-steel-designer-sheets',
    getParentRoute: () => rootRouteImport,
  } as any)
const SteelCollectionRoute = SteelCollectionRouteImport.update({
  id: '/steel-collection',
  path: '/steel-collection',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerSheetsIndexRoute = DesignerSheetsIndexRouteImport.update({
  id: '/designer-sheets/',
  path: '/designer-sheets/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerSheetsEmbossedRoute = DesignerSheetsEmbossedRouteImport.update({
  id: '/designer-sheets/embossed',
  path: '/designer-sheets/embossed',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerSheetsHairlineRoute = DesignerSheetsHairlineRouteImport.update({
  id: '/designer-sheets/hairline',
  path: '/designer-sheets/hairline',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerSheetsMirrorRoute = DesignerSheetsMirrorRouteImport.update({
  id: '/designer-sheets/mirror',
  path: '/designer-sheets/mirror',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagSlugRoute = TagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerSheetsFinishIndexRoute =
  DesignerSheetsFinishIndexRouteImport.update({
    id: '/designer-sheets/$finish/',
    path: '/designer-sheets/$finish/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesignerSheetsFinishProductRoute =
  DesignerSheetsFinishProductRouteImport.update({
    id: '/designer-sheets/$finish/$product',
    path: '/designer-sheets/$finish/$product',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/journal': typeof JournalRouteWithChildren
  '/material-light-space': typeof MaterialLightSpaceRoute
  '/materials': typeof MaterialsRoute
  '/people': typeof PeopleRoute
  '/process': typeof ProcessRoute
  '/pvd-surfaces': typeof PvdSurfacesRoute
  '/services': typeof ServicesRoute
  '/ss-decorative-mesh-pvd': typeof SsDecorativeMeshPvdRoute
  '/stainless-steel-designer-sheets': typeof StainlessSteelDesignerSheetsRoute
  '/steel-collection': typeof SteelCollectionRoute
  '/studio': typeof StudioRoute
  '/category/$slug': typeof CategorySlugRoute
  '/designer-sheets/embossed': typeof DesignerSheetsEmbossedRoute
  '/designer-sheets/hairline': typeof DesignerSheetsHairlineRoute
  '/designer-sheets/mirror': typeof DesignerSheetsMirrorRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/designer-sheets/': typeof DesignerSheetsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/designer-sheets/$finish/$product': typeof DesignerSheetsFinishProductRoute
  '/designer-sheets/$finish/': typeof DesignerSheetsFinishIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/journal': typeof JournalRouteWithChildren
  '/material-light-space': typeof MaterialLightSpaceRoute
  '/materials': typeof MaterialsRoute
  '/people': typeof PeopleRoute
  '/process': typeof ProcessRoute
  '/pvd-surfaces': typeof PvdSurfacesRoute
  '/services': typeof ServicesRoute
  '/ss-decorative-mesh-pvd': typeof SsDecorativeMeshPvdRoute
  '/stainless-steel-designer-sheets': typeof StainlessSteelDesignerSheetsRoute
  '/steel-collection': typeof SteelCollectionRoute
  '/studio': typeof StudioRoute
  '/category/$slug': typeof CategorySlugRoute
  '/designer-sheets/embossed': typeof DesignerSheetsEmbossedRoute
  '/designer-sheets/hairline': typeof DesignerSheetsHairlineRoute
  '/designer-sheets/mirror': typeof DesignerSheetsMirrorRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/designer-sheets': typeof DesignerSheetsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/designer-sheets/$finish/$product': typeof DesignerSheetsFinishProductRoute
  '/designer-sheets/$finish': typeof DesignerSheetsFinishIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/journal': typeof JournalRouteWithChildren
  '/material-light-space': typeof MaterialLightSpaceRoute
  '/materials': typeof MaterialsRoute
  '/people': typeof PeopleRoute
  '/process': typeof ProcessRoute
  '/pvd-surfaces': typeof PvdSurfacesRoute
  '/services': typeof ServicesRoute
  '/ss-decorative-mesh-pvd': typeof SsDecorativeMeshPvdRoute
  '/stainless-steel-designer-sheets': typeof StainlessSteelDesignerSheetsRoute
  '/steel-collection': typeof SteelCollectionRoute
  '/studio': typeof StudioRoute
  '/category/$slug': typeof CategorySlugRoute
  '/designer-sheets/embossed': typeof DesignerSheetsEmbossedRoute
  '/designer-sheets/hairline': typeof DesignerSheetsHairlineRoute
  '/designer-sheets/mirror': typeof DesignerSheetsMirrorRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/designer-sheets/': typeof DesignerSheetsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/designer-sheets/$finish/$product': typeof DesignerSheetsFinishProductRoute
  '/designer-sheets/$finish/': typeof DesignerSheetsFinishIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capabilities'
    | '/careers'
    | '/contact'
    | '/exhibitions'
    | '/journal'
    | '/material-light-space'
    | '/materials'
    | '/people'
    | '/process'
    | '/pvd-surfaces'
    | '/services'
    | '/ss-decorative-mesh-pvd'
    | '/stainless-steel-designer-sheets'
    | '/steel-collection'
    | '/studio'
    | '/category/$slug'
    | '/designer-sheets/embossed'
    | '/designer-sheets/hairline'
    | '/designer-sheets/mirror'
    | '/journal/$slug'
    | '/product/$slug'
    | '/projects/$slug'
    | '/tag/$slug'
    | '/designer-sheets/'
    | '/projects/'
    | '/designer-sheets/$finish/$product'
    | '/designer-sheets/$finish/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capabilities'
    | '/careers'
    | '/contact'
    | '/exhibitions'
    | '/journal'
    | '/material-light-space'
    | '/materials'
    | '/people'
    | '/process'
    | '/pvd-surfaces'
    | '/services'
    | '/ss-decorative-mesh-pvd'
    | '/stainless-steel-designer-sheets'
    | '/steel-collection'
    | '/studio'
    | '/category/$slug'
    | '/designer-sheets/embossed'
    | '/designer-sheets/hairline'
    | '/designer-sheets/mirror'
    | '/journal/$slug'
    | '/product/$slug'
    | '/projects/$slug'
    | '/tag/$slug'
    | '/designer-sheets'
    | '/projects'
    | '/designer-sheets/$finish/$product'
    | '/designer-sheets/$finish'
  id:
    | '__root__'
    | '/'
    | '/capabilities'
    | '/careers'
    | '/contact'
    | '/exhibitions'
    | '/journal'
    | '/material-light-space'
    | '/materials'
    | '/people'
    | '/process'
    | '/pvd-surfaces'
    | '/services'
    | '/ss-decorative-mesh-pvd'
    | '/stainless-steel-designer-sheets'
    | '/steel-collection'
    | '/studio'
    | '/category/$slug'
    | '/designer-sheets/embossed'
    | '/designer-sheets/hairline'
    | '/designer-sheets/mirror'
    | '/journal/$slug'
    | '/product/$slug'
    | '/projects/$slug'
    | '/tag/$slug'
    | '/designer-sheets/'
    | '/projects/'
    | '/designer-sheets/$finish/$product'
    | '/designer-sheets/$finish/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ExhibitionsRoute: typeof ExhibitionsRoute
  JournalRoute: typeof JournalRouteWithChildren
  MaterialLightSpaceRoute: typeof MaterialLightSpaceRoute
  MaterialsRoute: typeof MaterialsRoute
  PeopleRoute: typeof PeopleRoute
  ProcessRoute: typeof ProcessRoute
  PvdSurfacesRoute: typeof PvdSurfacesRoute
  ServicesRoute: typeof ServicesRoute
  SsDecorativeMeshPvdRoute: typeof SsDecorativeMeshPvdRoute
  StainlessSteelDesignerSheetsRoute: typeof StainlessSteelDesignerSheetsRoute
  SteelCollectionRoute: typeof SteelCollectionRoute
  StudioRoute: typeof StudioRoute
  CategorySlugRoute: typeof CategorySlugRoute
  DesignerSheetsEmbossedRoute: typeof DesignerSheetsEmbossedRoute
  DesignerSheetsHairlineRoute: typeof DesignerSheetsHairlineRoute
  DesignerSheetsMirrorRoute: typeof DesignerSheetsMirrorRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  TagSlugRoute: typeof TagSlugRoute
  DesignerSheetsIndexRoute: typeof DesignerSheetsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  DesignerSheetsFinishProductRoute: typeof DesignerSheetsFinishProductRoute
  DesignerSheetsFinishIndexRoute: typeof DesignerSheetsFinishIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions': {
      id: '/exhibitions'
      path: '/exhibitions'
      fullPath: '/exhibitions'
      preLoaderRoute: typeof ExhibitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-light-space': {
      id: '/material-light-space'
      path: '/material-light-space'
      fullPath: '/material-light-space'
      preLoaderRoute: typeof MaterialLightSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pvd-surfaces': {
      id: '/pvd-surfaces'
      path: '/pvd-surfaces'
      fullPath: '/pvd-surfaces'
      preLoaderRoute: typeof PvdSurfacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ss-decorative-mesh-pvd': {
      id: '/ss-decorative-mesh-pvd'
      path: '/ss-decorative-mesh-pvd'
      fullPath: '/ss-decorative-mesh-pvd'
      preLoaderRoute: typeof SsDecorativeMeshPvdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stainless-steel-designer-sheets': {
      id: '/stainless-steel-designer-sheets'
      path: '/stainless-steel-designer-sheets'
      fullPath: '/stainless-steel-designer-sheets'
      preLoaderRoute: typeof StainlessSteelDesignerSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steel-collection': {
      id: '/steel-collection'
      path: '/steel-collection'
      fullPath: '/steel-collection'
      preLoaderRoute: typeof SteelCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer-sheets/': {
      id: '/designer-sheets/'
      path: '/designer-sheets'
      fullPath: '/designer-sheets/'
      preLoaderRoute: typeof DesignerSheetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer-sheets/embossed': {
      id: '/designer-sheets/embossed'
      path: '/designer-sheets/embossed'
      fullPath: '/designer-sheets/embossed'
      preLoaderRoute: typeof DesignerSheetsEmbossedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer-sheets/hairline': {
      id: '/designer-sheets/hairline'
      path: '/designer-sheets/hairline'
      fullPath: '/designer-sheets/hairline'
      preLoaderRoute: typeof DesignerSheetsHairlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer-sheets/mirror': {
      id: '/designer-sheets/mirror'
      path: '/designer-sheets/mirror'
      fullPath: '/designer-sheets/mirror'
      preLoaderRoute: typeof DesignerSheetsMirrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$slug': {
      id: '/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof TagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer-sheets/$finish/': {
      id: '/designer-sheets/$finish/'
      path: '/designer-sheets/$finish'
      fullPath: '/designer-sheets/$finish/'
      preLoaderRoute: typeof DesignerSheetsFinishIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer-sheets/$finish/$product': {
      id: '/designer-sheets/$finish/$product'
      path: '/designer-sheets/$finish/$product'
      fullPath: '/designer-sheets/$finish/$product'
      preLoaderRoute: typeof DesignerSheetsFinishProductRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ExhibitionsRoute: ExhibitionsRoute,
  JournalRoute: JournalRouteWithChildren,
  MaterialLightSpaceRoute: MaterialLightSpaceRoute,
  MaterialsRoute: MaterialsRoute,
  PeopleRoute: PeopleRoute,
  ProcessRoute: ProcessRoute,
  PvdSurfacesRoute: PvdSurfacesRoute,
  ServicesRoute: ServicesRoute,
  SsDecorativeMeshPvdRoute: SsDecorativeMeshPvdRoute,
  StainlessSteelDesignerSheetsRoute: StainlessSteelDesignerSheetsRoute,
  SteelCollectionRoute: SteelCollectionRoute,
  StudioRoute: StudioRoute,
  CategorySlugRoute: CategorySlugRoute,
  DesignerSheetsEmbossedRoute: DesignerSheetsEmbossedRoute,
  DesignerSheetsHairlineRoute: DesignerSheetsHairlineRoute,
  DesignerSheetsMirrorRoute: DesignerSheetsMirrorRoute,
  ProductSlugRoute: ProductSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  TagSlugRoute: TagSlugRoute,
  DesignerSheetsIndexRoute: DesignerSheetsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  DesignerSheetsFinishProductRoute: DesignerSheetsFinishProductRoute,
  DesignerSheetsFinishIndexRoute: DesignerSheetsFinishIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
