import { useEffect, useRef, useState, type RefObject } from "react";
import { ArrowDownRight, ArrowUpRight, Menu, Search, X } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { WebGLChandelier } from "@/components/chandelier/webgl-chandelier";

const CATEGORIES = [
  ["01", "Chandeliers", "Sculptural forms for extraordinary spaces."],
  ["02", "Pendants", "Suspended light with architectural rhythm."],
  ["03", "Table Lights", "Objects of light, intimate and tactile."],
  ["04", "Floor Lights", "Vertical gestures that reshape a room."],
  ["05", "Wall Lights", "Light that draws architecture forward."],
  ["06", "Ceiling Lights", "Quiet constellations above the space."],
  ["07", "Outdoor", "Atmosphere beyond the threshold."],
  ["08", "Bespoke", "Lighting composed for one space only."],
] as const;

function useReducedMotion() {
  const [reduced, setReduced] = useState(false);
  useEffect(() => {
    const media = window.matchMedia("(prefers-reduced-motion: reduce)");
    const update = () => setReduced(media.matches);
    update();
    media.addEventListener?.("change", update);
    return () => media.removeEventListener?.("change", update);
  }, []);
  return reduced;
}

function useScrollProgress(ref: RefObject<HTMLElement | null>) {
  const [progress, setProgress] = useState(0);
  useEffect(() => {
    const update = () => {
      const el = ref.current;
      if (!el) return;
      const rect = el.getBoundingClientRect();
      const total = Math.max(1, el.offsetHeight - window.innerHeight);
      setProgress(Math.min(1, Math.max(0, -rect.top / total)));
    };
    update();
    window.addEventListener("scroll", update, { passive: true });
    window.addEventListener("resize", update);
    return () => {
      window.removeEventListener("scroll", update);
      window.removeEventListener("resize", update);
    };
  }, [ref]);
  return progress;
}

function CustomCursor() {
  const [pos, setPos] = useState({ x: -100, y: -100 });
  const [active, setActive] = useState(false);
  useEffect(() => {
    if (window.matchMedia("(pointer: coarse)").matches) return;
    const move = (e: MouseEvent) => setPos({ x: e.clientX, y: e.clientY });
    const over = (e: MouseEvent) => setActive(Boolean((e.target as HTMLElement)?.closest?.("[data-light-cursor]")));
    window.addEventListener("mousemove", move);
    window.addEventListener("mouseover", over);
    return () => { window.removeEventListener("mousemove", move); window.removeEventListener("mouseover", over); };
  }, []);
  return <div className={`pointer-events-none fixed z-[100] hidden h-7 w-7 -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#A78655]/70 md:block ${active ? "scale-150 bg-[#FFE2A8]/10" : ""}`} style={{ left: pos.x, top: pos.y, transition: "transform .25s ease, background .25s ease" }} aria-hidden="true" />;
}

function Navigation({ onMenu }: { onMenu: () => void }) {
  return <header className="fixed inset-x-0 top-0 z-50 px-5 py-5 sm:px-8 lg:px-10"><div className="mx-auto flex max-w-[1500px] items-center justify-between rounded-full border border-white/10 bg-black/10 px-5 py-3 backdrop-blur-md transition-colors duration-700 hover:bg-[#191817]/40"><Link to="/" className="font-serif text-sm tracking-[.32em] text-[#F2EEE6]" data-light-cursor>STEELX</Link><nav className="hidden items-center gap-9 text-[10px] uppercase tracking-[.22em] text-white/65 lg:flex">{[["Collection", "#collection"], ["Spaces", "#spaces"], ["Bespoke", "#bespoke"], ["About", "#philosophy"]].map(([label, href]) => <a key={label} href={href} className="transition-colors hover:text-[#F2EEE6]" data-light-cursor>{label}</a>)}</nav><div className="flex items-center gap-2"><button className="hidden h-9 w-9 place-items-center rounded-full text-white/60 transition hover:text-white sm:grid" aria-label="Search" data-light-cursor><Search className="h-4 w-4" /></button><button onClick={onMenu} className="grid h-9 w-9 place-items-center rounded-full border border-white/10 text-white/75 transition hover:border-[#A78655]/50 hover:text-white" aria-label="Open menu" data-light-cursor><Menu className="h-4 w-4" /></button></div></div></header>;
}

function MenuOverlay({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [hovered, setHovered] = useState("Chandeliers");
  if (!open) return null;
  const menu = ["Collection", "Chandeliers", "Pendants", "Table Lights", "Spaces", "Bespoke", "Journal", "About", "Showroom", "Contact"];
  return <div className="fixed inset-0 z-[90] overflow-hidden bg-[#191817] text-[#F2EEE6]"><div className="absolute inset-0 opacity-30" style={{ background: "radial-gradient(circle at 70% 35%, rgba(255,226,168,.18), transparent 34%), linear-gradient(120deg,#191817,#0b0b0a)" }} /><div className="relative mx-auto flex h-full max-w-[1500px] flex-col px-6 py-6 sm:px-10 lg:px-14"><div className="flex items-center justify-between"><span className="font-serif text-sm tracking-[.32em]">STEELX</span><button onClick={onClose} className="grid h-11 w-11 place-items-center rounded-full border border-white/15" aria-label="Close menu"><X className="h-5 w-5" /></button></div><div className="my-auto grid gap-12 lg:grid-cols-[1fr_360px] lg:items-end"><div>{menu.map((item) => <a key={item} href={item === "Collection" ? "#collection" : item === "Spaces" ? "#spaces" : item === "Bespoke" ? "#bespoke" : "#philosophy"} onMouseEnter={() => setHovered(item)} onClick={onClose} className={`block w-fit font-serif text-[clamp(2.5rem,6vw,6.2rem)] leading-[.9] transition-opacity ${hovered === item ? "text-[#F2EEE6]" : "text-white/25 hover:text-white/70"}`}>{item}</a>)}</div><div className="hidden border-l border-white/10 pl-10 lg:block"><p className="text-[9px] uppercase tracking-[.28em] text-[#A78655]">Now illuminating</p><p className="mt-4 font-serif text-3xl text-white/90">{hovered}</p><div className="mt-8 aspect-[4/5] overflow-hidden rounded-[2px] bg-[#2b2721]"><div className="h-full w-full" style={{ background: "radial-gradient(circle at 50% 34%, rgba(255,226,168,.8), transparent 8%), radial-gradient(circle at 50% 40%, rgba(167,134,85,.25), transparent 30%), linear-gradient(135deg,#3c3428,#141310 55%,#2c251b)" }} /></div></div></div></div></div>;
}

function Hero({ reduced }: { reduced: boolean }) {
  const ref = useRef<HTMLElement | null>(null);
  const progress = useScrollProgress(ref);
  const [ready, setReady] = useState(false);
  useEffect(() => { const t = window.setTimeout(() => setReady(true), reduced ? 0 : 900); return () => window.clearTimeout(t); }, [reduced]);
  return <section ref={ref} className="relative h-[230vh] bg-[#0B0B0A]" aria-label="Immersive lighting introduction"><div className="sticky top-0 h-screen overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_45%,rgba(255,226,168,.075),transparent_26%),radial-gradient(circle_at_50%_90%,rgba(167,134,85,.08),transparent_38%)]" /><div className="absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-[#0B0B0A] to-transparent" /><div className="absolute inset-0 z-[1] opacity-70" style={{ background: "radial-gradient(circle at 50% 45%, rgba(255,226,168,.05), transparent 34%)" }} /><div className="absolute inset-0 z-[2] pointer-events-none"><WebGLChandelier lightsOn={true} /></div><div className={`absolute left-1/2 top-[18%] z-20 -translate-x-1/2 text-center transition-opacity duration-[1800ms] ${ready ? "opacity-100" : "opacity-0"}`}><p className="text-[9px] uppercase tracking-[.42em] text-[#A78655]">A digital flagship experience</p><h1 className="mt-5 max-w-[900px] font-serif text-[clamp(2.8rem,7vw,7.5rem)] leading-[.9] text-[#F2EEE6]">Light is not placed.<br /><em className="font-normal text-[#FFE2A8]">It transforms.</em></h1></div><div className="absolute left-6 top-1/2 z-20 hidden -translate-y-1/2 text-[8px] uppercase tracking-[.35em] text-white/35 md:block [writing-mode:vertical-rl]">LIGHT ↓ EXPLORE</div><div className="absolute bottom-8 left-1/2 z-20 flex -translate-x-1/2 items-center gap-4 text-[8px] uppercase tracking-[.3em] text-white/40"><span className="h-10 w-px bg-gradient-to-b from-[#A78655] to-transparent" /> Explore the object</div><div className="absolute bottom-10 right-6 z-20 hidden max-w-[190px] text-right text-[10px] leading-relaxed text-white/35 md:block">Scroll forward to enter the chandelier. The object becomes the collection.</div><div className="absolute bottom-10 left-6 z-20 max-w-[260px] text-[9px] uppercase tracking-[.24em] text-white/35">The chandelier physically rotates with your cursor.</div></div></section>;
}

function Philosophy() { return <section id="philosophy" className="relative overflow-hidden bg-[#F2EEE6] px-6 py-32 text-[#191817] sm:px-10 lg:px-16 lg:py-48"><div className="mx-auto grid max-w-[1400px] gap-20 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="text-[9px] uppercase tracking-[.32em] text-[#A78655]">02 — Philosophy</p><h2 className="mt-8 max-w-4xl font-serif text-[clamp(3.4rem,7vw,8rem)] leading-[.86] tracking-[-.035em]">More than light.<br /><em className="font-normal">A form of space.</em></h2></div><div className="max-w-md lg:pt-32"><p className="text-lg leading-relaxed text-[#4f4a43]">Every piece is conceived to alter the atmosphere, rhythm and character of a space. Light is the material; architecture is the canvas.</p><div className="mt-14 h-px w-24 bg-[#A78655]" /></div></div><div className="pointer-events-none absolute -right-24 top-1/4 h-[500px] w-[500px] rounded-full border border-[#B8AA99]/45" /><div className="pointer-events-none absolute -right-10 top-[28%] h-[350px] w-[350px] rounded-full bg-[#D7CEC1]/55 blur-3xl" /></section>; }

function Collection() {
  const [active, setActive] = useState(0);
  return <section id="collection" className="bg-[#F2EEE6] text-[#191817]"><div className="h-[100svh] min-h-[680px] overflow-hidden px-6 py-8 sm:px-10 lg:px-16"><div className="mx-auto flex h-full max-w-[1500px] flex-col"><div className="flex items-end justify-between"><div><p className="text-[9px] uppercase tracking-[.32em] text-[#A78655]">03 — The collection</p><h2 className="mt-3 font-serif text-4xl sm:text-6xl">The collection</h2></div><span className="hidden text-[9px] uppercase tracking-[.25em] text-[#6c655c] md:block">Drag / scroll / explore</span></div><div className="relative mt-10 min-h-0 flex-1 overflow-hidden"><div className="flex h-full gap-5 transition-transform duration-700 ease-[cubic-bezier(.16,1,.3,1)]" style={{ transform: `translateX(calc(-${active * 73}% - ${active * 20}px))` }}>{CATEGORIES.map(([num, name, copy], i) => <article key={name} className="group relative h-full min-w-[78vw] overflow-hidden bg-[#D7CEC1] sm:min-w-[55vw] lg:min-w-[45vw] xl:min-w-[39vw]" onMouseEnter={() => setActive(i)}><div className="absolute inset-0" style={{ background: i % 3 === 0 ? "radial-gradient(circle at 52% 36%, rgba(255,226,168,.78), transparent 11%), radial-gradient(circle at 50% 38%, rgba(167,134,85,.32), transparent 33%), linear-gradient(135deg,#cfc5b5,#a99b8a 55%,#e4ddd2)" : i % 3 === 1 ? "radial-gradient(circle at 45% 35%, rgba(255,240,206,.78), transparent 8%), linear-gradient(145deg,#d9d0c3,#b6aa9b)" : "radial-gradient(circle at 52% 45%, rgba(255,226,168,.45), transparent 10%), linear-gradient(135deg,#c4b8a8,#ece6dc 60%,#b0a395)" }} /><div className="absolute left-[12%] top-[20%] h-[42%] w-[76%] rounded-[50%] border border-[#A78655]/45 shadow-[inset_0_0_90px_rgba(255,255,255,.2),0_40px_90px_rgba(46,39,30,.12)] transition-transform duration-1000 group-hover:scale-[1.03]" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#191817]/75 via-[#191817]/10 to-transparent p-7 pt-32 sm:p-10"><span className="text-[9px] tracking-[.3em] text-[#FFE2A8]">{num}</span><h3 className="mt-3 font-serif text-4xl text-white sm:text-6xl">{name}</h3><p className="mt-3 max-w-xs text-sm leading-relaxed text-white/65">{copy}</p><a href="#object" className="mt-6 inline-flex items-center gap-2 text-[9px] uppercase tracking-[.28em] text-white" data-light-cursor>Explore <ArrowUpRight className="h-3.5 w-3.5" /></a></div></article>)}</div></div><div className="mt-5 flex items-center justify-between"><div className="flex gap-2">{CATEGORIES.map(([,name],i)=><button key={name} onClick={()=>setActive(i)} aria-label={`Go to ${name}`} className={`h-px w-7 transition-all ${i===active ? "bg-[#A78655] w-12" : "bg-[#B8AA99]"}`} />)}</div><span className="text-[9px] uppercase tracking-[.25em] text-[#6c655c]">{String(active+1).padStart(2,"0")} / 08</span></div></div></div></section>;
}

function FeaturedObject() { return <section id="object" className="relative min-h-screen overflow-hidden bg-[#D7CEC1] px-6 py-32 text-[#191817] sm:px-10 lg:px-16"><div className="mx-auto grid min-h-[75vh] max-w-[1450px] gap-14 lg:grid-cols-[.7fr_1.3fr] lg:items-center"><div className="relative z-10"><p className="text-[9px] uppercase tracking-[.32em] text-[#A78655]">04 — The object</p><h2 className="mt-7 font-serif text-[clamp(4rem,8vw,9rem)] leading-[.82]">The<br /><em className="font-normal">Object</em></h2><p className="mt-8 max-w-sm text-sm leading-relaxed text-[#625b52]">A statement piece is not an accessory. It is an architectural event. Move through the object and discover its material language.</p><div className="mt-12 space-y-5 border-t border-[#191817]/15 pt-5 text-[10px] uppercase tracking-[.22em]"><div className="flex justify-between"><span>Material</span><span className="text-[#6d5c45]">Hand-finished brass</span></div><div className="flex justify-between"><span>Light</span><span className="text-[#6d5c45]">2700K warm illumination</span></div><div className="flex justify-between"><span>Finish</span><span className="text-[#6d5c45]">Brushed antique brass</span></div></div></div><div className="relative flex min-h-[520px] items-center justify-center"><div className="absolute h-[360px] w-[360px] rounded-full bg-[#FFE2A8]/25 blur-[90px]" /><div className="relative h-[520px] w-[520px] max-w-[90vw]" data-light-cursor><div className="absolute left-1/2 top-[4%] h-[90%] w-px -translate-x-1/2 bg-gradient-to-b from-transparent via-[#8f7148] to-transparent" />{Array.from({length:9}).map((_,i)=><div key={i} className="absolute left-1/2 top-[45%] h-[2px] origin-left bg-gradient-to-r from-[#765b37] via-[#C3A16A] to-transparent" style={{width:`${170+i*22}px`,transform:`translateX(-50%) rotate(${i*40}deg)`}}><span className="absolute right-0 top-1/2 h-7 w-7 -translate-y-1/2 translate-x-1/2 rounded-full bg-[#FFE2A8] shadow-[0_0_28px_10px_rgba(255,226,168,.42)]" /></div>)}<div className="absolute left-1/2 top-[40%] h-24 w-24 -translate-x-1/2 rounded-full border border-[#8f7148] bg-[#3a3022]/90 shadow-[0_0_90px_rgba(255,226,168,.25)]" /></div></div></div></section>; }

function Spaces() { return <section id="spaces" className="bg-[#191817] px-6 py-32 text-[#F2EEE6] sm:px-10 lg:px-16 lg:py-44"><div className="mx-auto max-w-[1450px]"><div className="flex flex-wrap items-end justify-between gap-10"><div><p className="text-[9px] uppercase tracking-[.32em] text-[#A78655]">05 — Light in context</p><h2 className="mt-6 font-serif text-[clamp(3.5rem,7vw,7.5rem)] leading-[.85]">Light in<br /><em className="font-normal">context.</em></h2></div><p className="max-w-sm text-sm leading-relaxed text-white/50">Residential, hospitality, retail and architectural spaces become the stage. The fixture is only the beginning.</p></div><div className="mt-20 grid gap-3 md:grid-cols-2"><SpaceCard title="Residential" copy="Warmth, rhythm, intimacy." /><SpaceCard title="Hospitality" copy="Arrival, drama, memory." /><SpaceCard title="Retail" copy="Identity, focus, atmosphere." /><SpaceCard title="Architectural" copy="Scale, shadow, proportion." /></div></div></section>; }
function SpaceCard({ title, copy }: { title: string; copy: string }) { return <article className="group relative aspect-[4/3] overflow-hidden bg-[#29251f]" data-light-cursor><div className="absolute inset-0 transition duration-[1200ms] group-hover:scale-105" style={{background:"radial-gradient(circle at 55% 45%, rgba(255,226,168,.58), transparent 8%), radial-gradient(circle at 55% 45%, rgba(255,226,168,.14), transparent 30%), linear-gradient(135deg,#40382d,#151412 65%)"}}/><div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent"/><div className="absolute bottom-7 left-7 right-7 flex items-end justify-between"><div><p className="font-serif text-3xl">{title}</p><p className="mt-2 text-xs text-white/45">{copy}</p></div><span className="text-[9px] uppercase tracking-[.22em] text-[#FFE2A8]">View space →</span></div></article>; }

function LightingSlider() { const [value, setValue] = useState(52); return <section className="bg-[#F2EEE6] px-6 py-32 text-[#191817] sm:px-10 lg:px-16 lg:py-44"><div className="mx-auto max-w-[1450px]"><p className="text-[9px] uppercase tracking-[.32em] text-[#A78655]">06 — The transformation</p><div className="mt-6 flex flex-wrap items-end justify-between gap-8"><h2 className="font-serif text-[clamp(3.2rem,6vw,7rem)] leading-[.86]">Light changes<br /><em className="font-normal">architecture.</em></h2><p className="max-w-sm text-sm leading-relaxed text-[#655e55]">Move through darkness, atmosphere and light. The architecture remains; the room does not.</p></div><div className="relative mt-16 aspect-[16/8] overflow-hidden bg-[#211f1c]"><div className="absolute inset-0" style={{background:`linear-gradient(90deg, rgba(5,5,4,${1-value/100*.7}), rgba(5,5,4,.15)), radial-gradient(circle at ${20+value*.55}% 48%, rgba(255,226,168,${.08+value/130}), transparent 17%), linear-gradient(135deg,#28241f,#62584a)`}}/><div className="absolute inset-x-[9%] bottom-[15%] h-[44%] border border-white/10"/><div className="absolute left-[14%] top-[22%] h-[54%] w-[1px] bg-white/10"/><div className="absolute right-[22%] top-[18%] h-[58%] w-[1px] bg-white/10"/><div className="absolute left-[14%] top-[22%] h-[1px] w-[64%] bg-white/10"/><div className="absolute inset-x-[10%] bottom-8 flex items-center gap-5"><span className="text-[8px] uppercase tracking-[.3em] text-white/45">Dark</span><input aria-label="Lighting intensity" type="range" min="0" max="100" value={value} onChange={e=>setValue(Number(e.target.value))} className="h-px flex-1 accent-[#A78655]"/><span className="text-[8px] uppercase tracking-[.3em] text-[#FFE2A8]">Light</span></div><div className="absolute left-8 top-8 text-[9px] uppercase tracking-[.25em] text-white/40">{value < 34 ? "01 — Darkness" : value < 68 ? "02 — Atmosphere" : "03 — Light"}</div></div></div></section>; }

function Materials() { return <section className="overflow-hidden bg-[#D7CEC1] px-6 py-32 text-[#191817] sm:px-10 lg:px-16 lg:py-44"><div className="mx-auto max-w-[1450px]"><p className="text-[9px] uppercase tracking-[.32em] text-[#A78655]">07 — Material</p><h2 className="mt-6 max-w-4xl font-serif text-[clamp(3.3rem,7vw,8rem)] leading-[.86]">Light has a<br /><em className="font-normal">material language.</em></h2><div className="mt-20 flex gap-4 overflow-x-auto pb-4 snap-x">{["Glass","Brass","Stone","Metal","Texture","Craft"].map((x,i)=><article key={x} className="min-w-[72vw] snap-start sm:min-w-[38vw] lg:min-w-[24vw]"><div className="aspect-[4/5]" style={{background:i%2===0?"radial-gradient(circle at 50% 40%,rgba(255,226,168,.65),transparent 14%),linear-gradient(145deg,#e4ddd2,#8f8271)":"linear-gradient(135deg,#4a4034,#b49a73 52%,#29241e)"}}/><p className="mt-4 text-[9px] uppercase tracking-[.28em] text-[#6b6258]">0{i+1} / {x}</p></article>)}</div></div></section>; }

function Bespoke() { return <section id="bespoke" className="relative overflow-hidden bg-[#191817] px-6 py-36 text-[#F2EEE6] sm:px-10 lg:px-16 lg:py-52"><div className="absolute right-[8%] top-1/2 h-[500px] w-[500px] -translate-y-1/2 rounded-full bg-[#A78655]/10 blur-[110px]"/><div className="relative mx-auto max-w-[1450px]"><p className="text-[9px] uppercase tracking-[.32em] text-[#A78655]">08 — Bespoke studio</p><h2 className="mt-8 max-w-5xl font-serif text-[clamp(3.2rem,7vw,8rem)] leading-[.84]">Some spaces<br />require something<br /><em className="font-normal text-[#FFE2A8]">extraordinary.</em></h2><div className="mt-14 grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><p className="max-w-xl text-sm leading-relaxed text-white/55">From a single statement piece to an entire architectural lighting composition, our bespoke studio works with architects, designers and private clients to create lighting made for a space.</p><a href="#contact" className="inline-flex items-center gap-3 border-b border-[#A78655] pb-3 text-[9px] uppercase tracking-[.3em] text-[#F2EEE6]">Discover bespoke <ArrowUpRight className="h-4 w-4" /></a></div></div></section>; }

function Showroom() { return <section id="showroom" className="bg-[#F2EEE6] px-6 py-32 text-[#191817] sm:px-10 lg:px-16 lg:py-44"><div className="mx-auto max-w-[1450px]"><p className="text-[9px] uppercase tracking-[.32em] text-[#A78655]">09 — The showroom</p><div className="mt-8 grid gap-4 lg:grid-cols-[.72fr_1.28fr]"><div className="flex flex-col justify-end pb-10"><h2 className="font-serif text-[clamp(3.3rem,6vw,7rem)] leading-[.84]">Experience<br /><em className="font-normal">the space.</em></h2><p className="mt-8 max-w-sm text-sm leading-relaxed text-[#625b52]">A physical gallery of light, material and proportion. The digital world should feel like a threshold into it.</p><a href="#contact" className="mt-10 inline-flex w-fit items-center gap-2 border-b border-[#A78655] pb-3 text-[9px] uppercase tracking-[.28em]">Visit the showroom <ArrowUpRight className="h-4 w-4" /></a></div><div className="grid grid-cols-2 gap-3"><div className="mt-14 aspect-[3/4] bg-[#C2B7A7]" style={{background:"radial-gradient(circle at 60% 32%,rgba(255,226,168,.8),transparent 9%),linear-gradient(150deg,#d8d0c4,#847869)"}}/><div className="aspect-[3/4] bg-[#B7AA99]" style={{background:"radial-gradient(circle at 35% 46%,rgba(255,226,168,.6),transparent 10%),linear-gradient(35deg,#9d8f7e,#e5dfd6)"}}/></div></div></div></section>; }

function Journal() { return <section className="bg-[#F2EEE6] px-6 pb-32 text-[#191817] sm:px-10 lg:px-16"><div className="mx-auto max-w-[1450px] border-t border-[#191817]/15 pt-20"><div className="flex items-end justify-between"><div><p className="text-[9px] uppercase tracking-[.32em] text-[#A78655]">10 — Journal</p><h2 className="mt-5 font-serif text-5xl sm:text-7xl">The journal</h2></div><span className="hidden text-[9px] uppercase tracking-[.25em] text-[#6b6258] md:block">Ideas / Objects / Spaces</span></div><div className="mt-14 grid gap-3 lg:grid-cols-3">{[["The art of light","Why atmosphere begins before the fixture."],["Lighting as architecture","Shadow, rhythm and the emotional room."],["The making of a statement piece","Inside a slower way of designing light."]].map(([title,copy],i)=><article key={title} className={`bg-[#D7CEC1] p-8 ${i===1?"lg:mt-16":""}`}><p className="text-[9px] uppercase tracking-[.28em] text-[#A78655]">0{i+1}</p><h3 className="mt-24 font-serif text-4xl leading-[.95]">{title}</h3><p className="mt-4 text-sm leading-relaxed text-[#625b52]">{copy}</p><span className="mt-10 inline-flex text-[9px] uppercase tracking-[.28em]">Read story →</span></article>)}</div></div></section>; }

function FinalCTA() { return <section id="contact" className="bg-[#F2EEE6] px-6 py-36 text-[#191817] sm:px-10 lg:px-16 lg:py-52"><div className="mx-auto max-w-[1400px] text-center"><p className="text-[9px] uppercase tracking-[.35em] text-[#A78655]">The world of light</p><h2 className="mt-8 font-serif text-[clamp(4rem,10vw,11rem)] leading-[.8]">Let there<br /><em className="font-normal">be atmosphere.</em></h2><p className="mx-auto mt-10 max-w-lg text-sm leading-relaxed text-[#625b52]">Discover lighting that changes the way a space feels.</p><div className="mt-10 flex flex-wrap justify-center gap-3"><a href="#collection" className="inline-flex min-h-12 items-center gap-2 bg-[#191817] px-7 text-[9px] uppercase tracking-[.25em] text-[#F2EEE6]">Explore the collection <ArrowDownRight className="h-4 w-4" /></a><a href="#contact" className="inline-flex min-h-12 items-center border border-[#191817]/20 px-7 text-[9px] uppercase tracking-[.25em]">Book a consultation</a></div></div></section>; }

function Footer() { return <footer className="bg-[#0B0B0A] px-6 py-16 text-[#F2EEE6] sm:px-10 lg:px-16"><div className="mx-auto max-w-[1450px]"><div className="grid gap-12 lg:grid-cols-[1.4fr_1fr_1fr_1fr]"><div><div className="font-serif text-2xl tracking-[.28em]">STEELX</div><p className="mt-4 max-w-xs text-sm leading-relaxed text-white/40">The world of architectural light. Sculptural objects, atmosphere and bespoke compositions.</p></div>{[["Collection","Chandeliers","Pendants","Table Lights","Floor Lights"],["Discover","Spaces","Bespoke","Journal","About"],["Client","Contact","Installation","Care","Warranty"]].map(([head,...items])=><div key={head}><p className="text-[9px] uppercase tracking-[.28em] text-[#A78655]">{head}</p><ul className="mt-5 space-y-3">{items.map(x=><li key={x}><a href="#" className="text-sm text-white/55 transition hover:text-white">{x}</a></li>)}</ul></div>)}</div><div className="mt-16 flex flex-wrap justify-between gap-6 border-t border-white/10 pt-6 text-[9px] uppercase tracking-[.22em] text-white/30"><span>© {new Date().getFullYear()} SteelX</span><span>Enter the world of light.</span></div></div></footer>; }

export function ChandelierPage() {
  const reduced = useReducedMotion();
  const [menuOpen, setMenuOpen] = useState(false);
  return <div className="min-h-screen bg-[#F2EEE6]" style={{ fontFamily: '"Inter", "Manrope", ui-sans-serif, system-ui, sans-serif' }}>
    <CustomCursor />
    <Navigation onMenu={() => setMenuOpen(true)} />
    <MenuOverlay open={menuOpen} onClose={() => setMenuOpen(false)} />
    <Hero reduced={reduced} />
    <Philosophy />
    <Collection />
    <FeaturedObject />
    <Spaces />
    <LightingSlider />
    <Materials />
    <Bespoke />
    <Showroom />
    <Journal />
    <FinalCTA />
    <Footer />
  </div>;
}
